### ISSUE TITLE
flux hangs on April 2019 CORAL stack

### ISSUE THREAD

**Issue by damora** [flux-framework/flux-core#2166] opened 2019-05-18 12:33 UTC
Updated to April 2019 CORAL stack which includes updates to JSM, CSM, LSF, and CUDA and although flux-broker is starting it seems to stall before it generates the FLUX_URI flux.info

Using flux-core.0.11.0 and flux-sched.0.7.0
JSRUN is based on pmix3.1.3rc2.

The debug doesn't show errors:
[249978.txt](https://github.com/flux-framework/flux-core/files/3194052/249978.txt)

The traceLog from strace just seems like it is hung at a futex call:
[traceLog.txt](https://github.com/flux-framework/flux-core/files/3194055/traceLog.txt)

Does anyone have any suggestions on how to debug this?

**Comment by dongahn** [comment] 2019-05-18 16:19
@damora: 

A few questions and suggestions. 

1. What is your `jsrun` command line to launch flux?

2. What process is this `strace` performed on? flux command itself? I guess a better question would be how did you run `strace`? 

3. I wonder what `FLUX_PMI_DEBUG` says about this. Can you run your reproducer with that environment variable? 

4. Can you run flux start with `-o,-S,log-filename=out` and send the generated trace `out` file? It can tell us what phase of startup, flux is hung up.

**Comment by damora** [comment] 2019-05-18 17:09
1,2,3.4. FLUX_PMI_DEBUG=1  /opt/ibm/spectrum_mpi/jsm_pmix/bin/jsrun -a 1 -c ALL_CPUS -g ALL_GPUS --bind=none -n $1 $SCRIPTDIR/env_clean.sh **strace -o $PERSISTDIR/traceLog.txt** $FLUX start  -o,-S,log-filename=flux.log $SCRIPTDIR/ip.sh

env_clean.sh just unsets some env variables related to JSM, LSF
ip.sh is what the MuMMI team does to get the FLUX_URI info in the users launch directory
$FLUX wreck exclude $(hostname) # Makeflux not schedule on flux headnode 
echo "ssh://$(hostname)$(flux getattr broker.rundir)" | tee flux.info
sleep inf

**Comment by dongahn** [comment] 2019-05-18 19:40
So nothing gets printed out with `FLUX_PMI_DEBUG=1`? That's odd.

Could you also post `flux.log`? 

> env_clean.sh just unsets some env variables related to JSM, LSF

I wonder if some variables that are needed for flux launching are cleaned up with this script. Were you able to launch an MPI hello world with the same command line?

`/opt/ibm/spectrum_mpi/jsm_pmix/bin/jsrun -a 1 -c ALL_CPUS -g ALL_GPUS --bind=none -n $1 $SCRIPTDIR/env_clean.sh ./hw`?

**Comment by damora** [comment] 2019-05-19 12:23
It never gets to point where it produces a flux.log.
My simple cuda mpi hello world program fails with env_clean.sh and succeeds without. This behavior is different than on our previous CORAL stack (one that is currently being used at LLNL). Not sure why the env_clean.sh script was needed, but the stripping of  [[ $n = OMPI_* ]] && unset $n && continue is what is preventing launch of my hello world mpi program. Not the reason flux isn't launching though. 
The only debug info that gets printed out is:
pmi_wrap_create: using /shared/flux/pmi//libpmi.so
pmi_wrap_create: using /shared/flux/pmi//libpmi.so
pmi_wrap_create: using /shared/flux/pmi//libpmi.so
The trace log final entries:
futex(0x100d5a04, FUTEX_WAIT_PRIVATE, 1, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex() = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
futex(0x100bc7b8, FUTEX_WAIT_PRIVATE, 2, NULL(To be restarted if SA_RESTART is set)

**Comment by dongahn** [comment] 2019-05-19 15:47
> It never gets to point where it produces a flux.log.
> My simple cuda mpi hello world program fails with env_clean.sh and succeeds without. 

Thanks. At least one variable less then! 

> Not the reason flux isn't launching though.
The only debug info that gets printed out is:
pmi_wrap_create: using /shared/flux/pmi//libpmi.so
pmi_wrap_create: using /shared/flux/pmi//libpmi.so
pmi_wrap_create: using /shared/flux/pmi//libpmi.so

@damora: I know you told me you ported and using PMI backward combat library that I provided. I want to make sure if that library is working under the new stack and being used by flux. 

1. I might had a test case in that library. Could you check if that's running ok under the new environment? 

2. Also could you add `PMI_LIBRARY=<your backward compatible libpmi>` ? as in:

`PMI_LIBRARY=$BACKCOMPAT_LIBPMI FLUX_PMI_DEBUG=1 /opt/ibm/spectrum_mpi/jsm_pmix/bin/jsrun -a 1 -c ALL_CPUS -g ALL_GPUS --bind=none -n $1 $SCRIPTDIR/env_clean.sh strace -o $PERSISTDIR/traceLog.txt $FLUX start -o,-S,log-filename=flux.log $SCRIPTDIR/ip.sh`

That is, with and without $SCRIPTDIR/env_clean.sh.

3. If that still doesn't work, could you set $1 = 1 to see if it works for at least one node case?

**Comment by damora** [comment] 2019-05-20 13:30
1. ./pmi_test 
rc from PMI_Init() is 0
rc from PMI_Get_size() is 0
rc from PMI_Get_rank() is 0
rc from PMI_Get_appnum() is 0
rc from PMI_Barrier() is 0
2,3
[traceLog.txt](https://github.com/flux-framework/flux-core/files/3198061/traceLog.txt)
[traceLog.noenv_clean.txt](https://github.com/flux-framework/flux-core/files/3198062/traceLog.noenv_clean.txt)
[traceLog.env_clean.txt](https://github.com/flux-framework/flux-core/files/3198063/traceLog.env_clean.txt)

Even the single node test is failing. I don't understand why the trace just seems to get to a point and then hangs.

**Comment by dongahn** [comment] 2019-05-20 14:53
So the backward compat library is broken with pmix3.1.3rc2! This is relevant for us as well since flux will stop working when we update PMIx on CORAL with that version. I don't have access to this version of PMIx to debug. Do you think you have tools to debug it yourself?

> Even the single node test is failing. I don't understand why the trace just seems to get to a point and then hangs.

I can imagine this could happen when PMI size returns like this.

**Comment by dongahn** [comment] 2019-05-20 14:54
Hold on. This is return code. Is this really a failure on PMI?

**Comment by damora** [comment] 2019-05-20 16:26
I think the PMI test runs fine so not sure if this is a PMI failure. 

seems like it is stuck in jsm component of CORAL stack. Consulting with JSM developer. Maybe he can make sense of the traceLog since it is full of jsm commands

**Comment by dongahn** [comment] 2019-05-20 16:46
> futex(0x100c7c80, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x100bc7b8, FUTEX_WAIT_PRIVATE, 2, NULL

This typically means some sort of a synchronization error (maybe within PMIx client code)... But I don't understand this as the PMI test seems ran fine. 

If JSM guys can deploy the PMI backward compatibility library with each CORAL stack release, this will make one variable less to worry about. Maybe you can again push for it?

**Comment by dongahn** [comment] 2019-05-21 21:57
FYI -- @SteVwonder and I had a call with @damora and Josh. We currently suspect a regression bug (memory corruption?) in the new PMIx version. Josh is looking into this. This needs to be communicated to LLNL team as well as this CORAL stack would be our next target.

**Comment by dongahn** [comment] 2019-05-21 22:02
Ok. Dropped a line to John G. and Adam Bertch.

**Comment by grondo** [comment] 2021-12-14 19:09
This issue is against the older execution system, so closing.

**Closed by grondo** 2021-12-14 19:09 UTC
