### ISSUE TITLE
libpmi "single" personality should use pid for appnum

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#797] opened 2016-09-07 17:14 UTC
As noted in #793, `flux list-instances` seems not to be working.  It needs fixing, and a test case.

```
$ ./flux start
$ flux list-instances
$ echo $FLUX_URI
local:///tmp/flux--1-TneJyv/0
$ ls /tmp/flux--1-TneJyv/0
broker.pid  local=
$
```

**Comment by trws** [comment] 2016-09-08 20:57
@garlick and I talked about this, it's clearly that the instance temporary directory name doesn't conform to the pattern list-instances looks for, but it's because the directory has an empty session id.  One valid fix for this would be to change the `+` in the regex to a `*`, but I have never seen that pattern happen and actually haven't been able to reproduce the problem.  There may be an issue with session IDs in here somewhere that's resulting in list-instances flaking out.

**Comment by garlick** [comment] 2016-09-08 21:01
On my Ubuntu system:
```
$ flux start
$ flux getattr session-id
-1
$ echo $FLUX_URI
local:///tmp/flux--1-jSUb29/0
$ 
```

**Comment by trws** [comment] 2016-09-08 21:07
That makes sense, the pattern is looking for something that isn't another dash as the ID, I guess I'd been assuming the session IDs would be unsigned integers, is -1 an intentional result?

**Comment by garlick** [comment] 2016-09-08 21:07
Ah - the problem is that `flux-start` just execs the broker if size = 1, and then when the broker tries to bootstrap, it uses the PMI "single" personality which...
```C
int pmi_single_get_appnum (struct pmi_single *pmi, int *appnum)
{
    *appnum = -1;
    return PMI_SUCCESS;
}
```
is wrong I guess.

**Closed** 2016-10-03 23:33 UTC
