### ISSUE TITLE
cannot find -lpgm

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#538] opened 2016-02-02 23:39 UTC
I'm suddenly seeing this error building on ipa:
```
make[3]: Entering directory `/g/g0/lipari/flux-core/src/common'
  CCLD   libflux-internal.la
  CCLD   libflux-core.la
/usr/bin/ld: cannot find -lpgm
collect2: ld returned 1 exit status
make[3]: *** [libflux-core.la] Error 1
make[3]: Leaving directory `/g/g0/lipari/flux-core/src/common'
```

**Comment by dongahn** [comment] 2016-02-03 00:29
ipa15{dahn}70: rpm -qa | grep pgm

pygpgme-0.1-18.20090824bzr68.el6.x86_64

openpgm-5.1.118-3.el6.x86_64

gpgme-1.1.8-3.el6.x86_64

gpgme-devel-1.1.8-3.el6.x86_64

Do we need openpgm dev package installed on LC systems as well?

Still baffled why this only shows up now…

Dong

**Comment by grondo** [comment] 2016-02-03 00:52
Yeah, I think the openpgm-devel package just got dropped somehow.

I'll request it get officially added.

**Comment by lipari** [comment] 2016-02-03 01:47
It is still on upgrade.
```$ rpm -qf libpgm.so
openpgm-devel-5.2.122-2.el7.x86_64
$ rpm -qi openpgm-devel-5.2.122-2.el7.x86_64
Name        : openpgm-devel
```

**Comment by lipari** [comment] 2016-02-04 01:20
openpgm-devel has been installed on hype and will be in the next TOSS 2.4-7.  It was never in TOSS 2, and it remains a mystery why it was suddenly needed.

**Comment by garlick** [comment] 2016-02-04 20:12
Ah, it looks like the new zeromq4 package, built on Jan 4, installed on ipa Feb 2, included the libtool .la file, e.g.
```
ipa15@garlick:rpm -ql zeromq4-devel | grep \\.la
/usr/lib64/libzmq.la
```
and inside it is
```
ipa15@garlick:grep pgm /usr/lib64/libzmq.la
dependency_libs=' -lsodium -lpgm -lgssapi_krb5 -lrt -lpthread'
```

So it's my fault.  I'll re-roll zeromq for TOSS 3 and TOSS 2.

**Comment by lipari** [comment] 2016-02-04 20:17
one more mystery bites the dust.

**Comment by dongahn** [comment] 2016-02-04 20:20
I noticed that too. But is that libtool archive included because we built our own RPM or is it part of prebuilt rpm available out there?

**Comment by garlick** [comment] 2016-02-04 20:21
I built that rpm.  It is my bad.

**Comment by dongahn** [comment] 2016-02-04 20:25
Thank you for looking further into this @garlick!

**Comment by garlick** [comment] 2016-02-04 20:35
No problem.

I built zeromq4-4.1.4-2 with this fix and requested it to be updated in the next TOSS2  release by reopening TOSS-3065.

**Comment by garlick** [comment] 2016-02-04 21:22
TOSS3 done as well, ticket is TOSS-3064.  I'm going to re-close this one.

**Closed by garlick** 2016-02-04 21:22 UTC

**Comment by trws** [comment] 2016-02-08 21:05
Is this working for others on hype and IPA right now? I'm having issues getting the current version to build on either one.

**Comment by trws** [comment] 2016-02-08 21:41
Also on rzalastor...

**Comment by lipari** [comment] 2016-02-08 21:47
Try hype.  It will go everywhere once TOSS 2.7 is released, but for now, I believe Trent only installed it  on hype login nodes.

**Comment by trws** [comment] 2016-02-08 21:52
Is it somewhere that I need to specify a path? I don't mind doing that, but it's still breaking out of the box on hype right now.  I guess that also needs to go into the spack package, suppose I'll do that in the meantime.

**Comment by dongahn** [comment] 2016-02-08 22:16
Perhaps you can have create a symlink in the build directory (libpgm.so) where the linking is failing? 

The symlink points to of course the number-versioned libpgm shared library?

**Comment by lipari** [comment] 2016-02-08 22:18
If you haven't already, try running:
```
module load python/2.7 python-cffi python-pycparser
```

**Comment by trws** [comment] 2016-02-08 22:33
Thanks @lipari.  That works for me on hype.  It seems interesting to me 
that the pgm library is coming in due to loading those modules though.  
I was using a speck-built python with cffi and pycparser available, but 
it failed on `-lpgm` until those modules were loaded.

**Comment by garlick** [comment] 2016-02-08 22:36
Is `zeromq4-4.1.4-2` installed on hype?  That should fix this.  Release 1 of that package included the libtool .la files which makes libzmq's transitive dependencies visible to libtool when libflux-core is built.

**Comment by trws** [comment] 2016-02-08 22:39
Or, at least, it builds but I can't actually run it on hype now... 
Somehow it works on the login node with those modules, but not on the 
compute nodes.  I must be doing something wrong here...

**Comment by garlick** [comment] 2016-02-08 22:44
I'd check `rpm -q zeromq4` on both login and compute nodes.

You might have to rebuild core and anything built on top of it if you picked up -lpgm before.

**Comment by trws** [comment] 2016-02-08 22:53
Nope, all of hype, ipa and rzalastor are running 4.1.4-1.  Evidently cab 
is using an older 4.0.5, and that seems to work ok.

**Comment by garlick** [comment] 2016-02-08 23:06
Really sorry for the trouble this caused, especially if it takes a while for those systems to get updated!

Anyway, the source of the problem is libzmq so if you want to work around it on these systems, you'll probably have to build your own side-installed copy like `travis-dep-builder.sh`.  Alternatively I guess you could do the same with openpgm.

**Comment by trws** [comment] 2016-02-08 23:08
Ok.  I can build a new environment with spack, actually that's probably 
why I only just noticed.  My spack tree got corrupted last night and I 
cleared it, must not have rebuilt all the internal flux dependencies 
yet. =/

Either way, at least I have some tests running on cab now.  I wanted to 
get a look at the memory and storage expansion with the new content 
modules as compared to the hash one to see if we can close the 
super-linear memory expansion issue.

**Comment by garlick** [comment] 2016-02-08 23:17
ah good.  See pr #543 which includes some fixes along those lines, including
* load content-sqlite by default
* provide a mechanism to redirect its db files to file system of your choosing (since /tmp is often a ramdisk)
