### ISSUE TITLE
travis: master build hanging

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1699] opened 2018-10-04 22:50 UTC
Looks like the builds of master on Travis are hanging.  Since the most recent PR was the py3 compatibility change, I figured the python bindings were the cause.  In [one hung build](https://travis-ci.org/flux-framework/flux-core/jobs/437311256), it looks like python/t0003-barrier.py doesn't have a TAP output line.  But in [another hung build](https://travis-ci.org/flux-framework/flux-core/jobs/437311259) it looks like all of the python tests ran successfully.  I'm not sure what the actual cause is or the best way to go about tracking it down (it is not clear to me how to determine which tests didn't run or which one was hung).

**Comment by grondo** [comment] 2018-10-04 23:17
I wonder if it is related to other issue we were seeing with builds on master? I'm going to try pushing to my own master branch and see if it reproduces there. (it could be related to the different output processor used by Travis when secret env vars are in use)

**Comment by grondo** [comment] 2018-10-04 23:46
well it worked in my branch :confused: (I thought maybe that would trigger the same output processing as master on flux-framework/flux-core).

I'm going to try restarting one of the builds to see if it was something temporary. Sometimes there just isn't a way to track these things down..

**Comment by grondo** [comment] 2018-10-04 23:55
The restart was successful, so I'm guessing travis hiccup, or difficult to reproduce problem...

**Comment by SteVwonder** [comment] 2018-10-05 04:04
Ok. I'll close this issue then, and chalk it up to Travis being Travis (while keeping my fingers crossed that the python bindings aren't in anyway connected).

**Comment by SteVwonder** [comment] 2018-10-05 17:30
Looks like the problem is more consistent than desirable.  I grabbed a log of a hung build from #1696 and compared it against a good log in the same PR.  [Gist of the raw logs and diffs.](https://gist.github.com/SteVwonder/1fdcc3ceb772fd486be433a0c6e21775)

It looks like the test that hung in #1696 was `t5000-valgrind.t`.

Side-note: `t4000-issues-test-driver.t` produced a different number of outputs in the good test.  I'm guessing that is because the good test was a distcheck?

**Comment by chu11** [comment] 2018-10-05 17:39
Possibly this is just #1311?

**Comment by grondo** [comment] 2018-10-05 17:52
> Side-note: t4000-issues-test-driver.t produced a different number of outputs in the good test. I'm guessing that is because the good test was a distcheck?

Interesting, were there less tests in the distcheck case? I wonder if one of the issues scripts needs to get added to `EXTRA_DIST`?

**Comment by SteVwonder** [comment] 2018-10-05 18:37
Yep.  There were fewer tests in the distcheck case (the `good-log.txt`).

```
# herbein1 at luigi.llnl.gov in ~/Repositories/flux-framework/flux-core on git:update-dependencies ✖︎  [10:28:02]
→ function get_summaries { grep 'PASS: N=' $1 | sort }
	

# herbein1 at luigi.llnl.gov in ~/Repositories/flux-framework/flux-core on git:update-dependencies ✖︎  [10:28:11]
→ diff <(get_summaries good-log.txt) <(get_summaries ./hung-log.txt)
	94d93
	<           t5000-valgrind.t:  PASS: N=1   PASS=1   FAIL=0 SKIP=0 XPASS=0 XFAIL=0
	155c154
	< t4000-issues-test-driver.t:  PASS: N=3   PASS=3   FAIL=0 SKIP=0 XPASS=0 XFAIL=0
	---
	> t4000-issues-test-driver.t:  PASS: N=4   PASS=4   FAIL=0 SKIP=0 XPASS=0 XFAIL=0
```

**Comment by grondo** [comment] 2018-10-05 18:47
Yes, one of the tests under `t/issues` was missing from EXTRA_DIST. Also, seems like we should add a timeout to the valgrind test.

I'll propose a PR

**Comment by trws** [comment] 2018-10-11 15:47
Since the timeout has been merged for valgrind, close?

**Comment by chu11** [comment] 2018-10-11 18:00
I thought I hit this issue in #1713, but I now see that #1713 was merged after the timeout went in.  So perhaps I jumped the gun thinking it was #1699?   Don't know if there's a way to get to an old failed log to double check.

**Closed** 2021-11-17 00:51 UTC
