### ISSUE TITLE
not ok 50 - instance can stop cleanly with subscribers (#1025)

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1126] opened 2017-07-25 17:12 UTC
I'm seeing sporadic failure of this test in Travis. Do you think the `--shutdown-grace=0.1` is too short on limited environment in Travis?

I've only seen this failure 1 times out of 50, so perhaps this doesn't need to fixed right now, and will go away when we can remove the artificially short grace period once #1006 is fixed?

```
expecting success: 
	flux start ${BUG1006} -s2 --bootstrap=selfpmi bash -c "nohup flux event sub hb &"
lt-flux-broker: module 'resource-hwloc' was not cleanly shutdown
lt-flux-broker: module 'barrier' was not cleanly shutdown
lt-flux-broker: module 'aggregator' was not cleanly shutdown
lt-flux-broker: module 'job' was not cleanly shutdown
lt-flux-broker: module 'kvs' was not cleanly shutdown
flux-event: flux_event_subscribe: Success
flux-start: 0 (pid 102905) Killed
not ok 50 - instance can stop cleanly with subscribers (#1025)
```

**Comment by garlick** [comment] 2017-08-29 23:20
duplicate of #1077

**Closed by garlick** 2017-08-29 23:20 UTC
