### ISSUE TITLE
flux-proxy on Lassen: service.add: missing sender uuid

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2685] opened 2020-01-28 01:26 UTC
Another issue @JaeseungYeom and I hit on Lassen (Issue #2684).

We launched the flux-0.11.x-20190425 version with `sleep -inf`:

```console
lassen259{dahn}32: env PMI_LIBRARY=/usr/global/tools/pmi4pmix/blueos_3_ppc64le_ib/20191120/lib/libpmi.so jsrun -a 1 -c ALL_CPUS -g ALL_GPUS --bind=none -n 4 /usr/global/tools/flux/blueos_3_ppc64le_ib/flux-0.11.x-20190425/bin/flux start flux ~/ip.sh
ssh://lassen259/var/tmp/flux-8pfahZ
```

Then, on a Lassen login node, we used `flux-proxy` to connect to this FLUX_URI and tried to run a parallel program.

```console
lassen708{dahn}9: /usr/global/tools/flux/blueos_3_ppc64le_ib/flux-0.11.x-20190425/bin/flux proxy ssh://lassen259/var/tmp/flux-8pfahZ
lassen708{dahn}21: flux wreckrun -N 4 -n 4 ~/testcases/parallel_dbg_target/parallel_dbg_target/virtual_ring_mpi
```

On the compute node, flux errored the following error message and the job didn't seem to run.
```
2020-01-28T01:18:58.210480Z proxy.err[0]: response_cb: topic service.add: missing sender uuid
```

This may be a problem that has been fixed in a newer version. But we couldn't test it because of issue #2684 .

**Comment by grondo** [comment] 2020-01-28 02:15
I think this may be a duplicate of flux-framework/flux-core-v0.11#21.

You can't use service.add over flux-proxy.

Just ssh to the host and set FLUX_URI instead.

**Comment by dongahn** [comment] 2020-01-28 06:09
Thanks @grondo. Of course, a better option will be to fix Issue #2684 and use the new version.

**Comment by grondo** [comment] 2020-01-29 19:11
I'm going to close this issue since it is against flux-core-v0.11, which has its own issue tracker, and this issue has been found to be a duplicate.

**Closed by grondo** 2020-01-29 19:11 UTC

**Comment by dongahn** [comment] 2020-01-29 19:12
Yes, this is fine. I will test this once we fix the other problem.
