### ISSUE TITLE
Broker doesn't return shell when killed

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#2661] opened 2020-01-21 17:53 UTC
I was running Flux interactively inside a Slurm allocation on rztopaz, when I found that killing the `srun` I used to launch the Flux broker resulted in a broken shell which wouldn't accept any input. The only way I was able to get control back was to kill the Slurm job from a different shell. Here is the console session:

```
[corbett8@rztopaz188:corbett8]$ salloc -N1 -ppdebug
salloc: Granted job allocation 3486025
bash-4.2$ srun -n1 --pty --mpibind=off $new_flux start python3 uqp/core/ensemble/test/speed_comparison.py 
cmd: ['flux', 'mini', 'run', '-n1', '-c1', 'sleep', '1'], resource manager: 'flux', total runs: 200, total cores: 36

managing resources:
Imitating management of 36 total cores
[here I kill the srun with Ctrl-C]
^CTraceback (most recent call last):
  File "uqp/core/ensemble/test/speed_comparison.py", line 142, in <module>
    main()
  File "uqp/core/ensemble/test/speed_comparison.py", line 132, in main
    manage_resources(cmd, total_runs, total_cores)
  File "uqp/core/ensemble/test/speed_comparison.py", line 58, in manage_resources
    for index, job in enumerate(jobs):
KeyboardInterrupt
2020-01-21T17:45:15.251445Z broker.err[0]: Run level 2 Exited with non-zero status (rc=1) 4.0s
2020-01-21T17:45:15.285099Z qmanager.err[0]: schedutil: error in responding to outstanding messages
2020-01-21T17:45:15.324366Z broker.err[0]: rc3: flux-module: cmb.rmmod[0] sched-simple: No such file or directory
exit
exit
^C^Z
[here I scancel the job from a different shell]
salloc: Job allocation 3486025 has been revoked.
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
srun: error: rztopaz1: task 0: Killed
[corbett8@rztopaz188:corbett8]$ 
```

**Comment by grondo** [comment] 2020-01-21 18:04
Hm, I'll play around with this, but it appears that the flux instance is exiting normally (at least trying to), after `srun` forwards ctrl-c to your job. It looks like `speed_comparison.py` (the initial program of the instance) receives the signal and exits, which then causes the broker to exit.

I think it must be that Slurm is still waiting for something in the job step to exit before it returns you to the shell spawned by salloc. If you can reproduce, output of `pstree -u` may be interesting on the compute node. Then we can know what is still running under the slurmstepd, if anything.

**Comment by grondo** [comment] 2020-01-21 18:05
BTW, I at least have often seen this behavior from `srun` where it becomes uninterruptible by SIGINT when the job step is exiting. I'm not sure there is much we can do about that. You could try killing the job step instead of the job as a  whole to preserve your allocation. Or try `ctrl-\` to send SIGQUIT.

**Comment by jameshcorbett** [comment] 2020-01-21 18:51
Yeah, I thought there was a fair chance it might be just a Slurm thing, but I wasn't sure. Here's the output from pstree after I Ctrl-c'd the `srun`:
```
bash-4.2$ pstree -u
systemd-+-2*[agetty]
|-auditd---{auditd}
|-bird(bird)---{bird}
|-cerebrod
|-crond
|-dbus-daemon(dbus)
|-dhclient
|-gssproxy---5*[{gssproxy}]
|-irqbalance
|-2*[iscsid]
|-multipathd---6*[{multipathd}]
|-2*[munged(munge)---3*[{munged}]]
|-ntpd(ntp)
|-rasdaemon
|-rdma-ndd
|-rpc.gssd
|-rpc.statd(rpcuser)
|-rpcbind(rpc)
|-slurmd
|-slurmstepd-+-bash(corbett8)---screen---screen-+-bash---srun-+-srun
|            |                                  |             `-5*[{srun}]
|            |                                  `-bash---pstree
|            `-5*[{slurmstepd}]
|-slurmstepd-+-flux-broker-0(corbett8)-+-30*[flux-shell]
|            |                         |-2*[python]
|            |                         |-rc3---flux-module
|            |                         `-7*[{flux-broker-0}]
|            `-6*[{slurmstepd}]
|-snmpd
|-syslog-ng---shutdown-hot
|-systemd-journal
|-systemd-logind
`-systemd-udevd
bash-4.2$ 
```

**Comment by grondo** [comment] 2020-01-21 19:06
Ah, I don't think it is just a Slurm thing in this case. :-(

This is a known deficiency in our shutdown path and is currently being addressed (#2659 #2503 ?). If there are still active jobs during termination, then the `rc3` shutdown script will just hang until the jobs exit or we hit a timeout (I think). Slurm thinks the job step is still active since the direct child process `flux-broker-0` hasn't exited yet.

**Comment by grondo** [comment] 2020-01-21 19:08
I didn't find an open issue for "shutdown hang with active jobs" -- mind if I rename this issue @jameshcorbett? or perhaps I just missed something @garlick?

**Comment by jameshcorbett** [comment] 2020-01-21 19:12
Sure, I don't mind if you rename it.

**Comment by dongahn** [comment] 2020-01-21 19:14
@grondo: this is a related issue? https://github.com/flux-framework/flux-core/issues/2600

**Comment by grondo** [comment] 2020-01-21 21:07
Yes, thanks! That is the issue I was searching for, thanks @dongahn 
This issue is the same as described in #2600, just under Slurm instead of flux-start.

**Comment by jameshcorbett** [comment] 2020-01-21 21:59
Ah, I saw that one before I posted, but I thought it was a different issue. Should I close this as a duplicate?

**Comment by grondo** [comment] 2020-01-21 22:02
Yeah, I've marked this as a duplicate and will paste your nice writeup into the other issue.

**Closed** 2020-01-21 22:04 UTC
Labels: duplicate
