### ISSUE TITLE
t2001-jsc not ok 1 - jstat 1: notification works for 1 wreckrun

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#500] opened 2015-12-17 14:27 UTC
This failure just occurred in a travis build.  It seems to occur intermittently:

expecting success: 
    run_flux_jstat 1 &&
    p=$( sync_flux_jstat 1) &&
    run_timeout 4 flux wreckrun -n4 -N4 hostname &&
    cat >expected1 <<-EOF &&
$trans
EOF
    cp output.1 output.1.cp &&
    kill -INT $p &&
    test_cmp expected1 output.1.cp 
testing-worker-linux-docker-8ea8c977-3196-linux-7
testing-worker-linux-docker-8ea8c977-3196-linux-7
testing-worker-linux-docker-8ea8c977-3196-linux-7
testing-worker-linux-docker-8ea8c977-3196-linux-7
./t2001-jsc.t: 9: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
not ok 1 - jstat 1: notification works for 1 wreckrun

**Comment by garlick** [comment] 2015-12-17 14:29
The build that failed is [9735922](https://travis-ci.org/flux-framework/flux-core/jobs/97352922).  There appear to be some errors in the broker log but as its rather long I'm just providing the link here.

**Comment by grondo** [comment] 2015-12-17 15:03
Looks like maybe `$(sync_flux_jstat 1)` returned an empty string  instead of the PID from the previous `run_flux_jstat`. Unfortunately it appears that when you restart a job in Travis it reuses the same build ID and thus the build [9735922](https://travis-ci.org/flux-framework/flux-core/jobs/97352922) now shows as successful.

I'll try recreating on one of my own branches.

**Comment by grondo** [comment] 2015-12-17 17:28
I couldn't reproduce a failure after a few runs through travis and repeated attempts on a c9.io instance. Next time this occurs, could someone download the raw travis build log and attach it to this issue?

**Comment by dongahn** [comment] 2015-12-17 18:02
Yes. That should be useful.

**Comment by grondo** [comment] 2015-12-19 15:50
I think we found the likely cause of this one in the discussion for #498, and probably fixed this specific issue in #504. Closing for now.

**Closed by grondo** 2015-12-19 15:50 UTC
