### ISSUE TITLE
Job timeouts when submitting 10,000 jobs

### ISSUE THREAD

**Issue by Treece-Burgess** [flux-framework/flux-core#4036] opened 2022-01-07 15:39 UTC
Upon submitting 10,000 short lived jobs to Flux, some of the jobs managed by Flux fail. 
We also do see a relationship of how many jobs fail depending on the job length, with shorter jobs being more likely to fail.

For example:
For a job length of 0, we observe a median of **860** failed jobs
For a job length of 5, we observe a median of **214** failed jobs
For a job length of 10, we observe a median of **98** failed jobs

Steps to replicate:
1. Have the batch script and the reproducer within the same directory
2. Submit the batch script to the LSF scheduler to run 

The job failures will be at the top of stdout.0.log.

We observe the problem for the following configuration: 
- Flux version c0.29.0 - s0.18.0
- 32 nodes @ 40 cores on Lassen
- Topology of 1

The following zip file will contain the reproducer.py which can reproduce this issue, and its subsequent batch script: [Reproducer_and_Batch.zip](https://github.com/flux-framework/flux-sched/files/7829634/Reproducer_and_Batch.zip)

**Comment by grondo** [comment] 2022-01-07 22:12
I've transferred this issue to flux-core since I was able to reproduce with the simple scheduler.

**Comment by grondo** [comment] 2022-01-08 05:13
@Treece-Burgess, we've added a fix in #4037 which will help avoid many, but not all, of the spurious timeouts we see when running this reproducer. The fix will be included in v0.33 of flux-core.

Even with the fix, some jobs still time out if the run during the initial submission phase. I believe this is because the instance is bogged down handling the 10k job submissions and this slows handling of events and messages related to running jobs.

Until we can address this issue in some more elegant manner, it might be wise to disable the job queue while doing large bulk submissions of jobs so that no jobs run during the submission phase. The queue can then be enabled once all jobs have been submitted.

This can be done with the `flux queue stop` and `flux queue start` commands, or special RPCs to the `job-manager.alloc-admin` service. For example, here's a patch to the reproducer which disables the queue during job submission using RPCs. I don't get any job failures with this change.

```diff
--- reproducer.py.orig	2022-01-07 20:44:17.615100868 -0800
+++ reproducer.py	2022-01-07 20:52:57.862814124 -0800
@@ -25,6 +25,17 @@
 subs_in_flight = 0  # current job submissions in flight
 job_ids = deque()
 
+def queue_stop(h):
+    h.rpc(
+        "job-manager.alloc-admin",
+        {"query_only": False, "enable": False, "reason": "benchmark"}
+    ).get()
+
+def queue_start(h):
+    h.rpc(
+        "job-manager.alloc-admin",
+        {"query_only": False, "enable": True, "reason": "benchmark"}
+    ).get()
 
 
 def make_jobspec():
@@ -39,7 +50,6 @@
 
 
 
-
 def submit_some_jobs(flux_handle):
     global subs_sent, subs_in_flight
 
@@ -52,6 +62,8 @@
 
     if prev_sub_sent_ct < N_JOBS and subs_sent >= N_JOBS:
         print("All jobs submitted!", file=sys.stderr, flush=True)
+        print("Starting queue", file=sys.stderr, flush=True)
+        queue_start(flux_handle)
 
 
 def job_init_cb(fut, arg=None):
@@ -106,6 +118,8 @@
     print("Connecting to broker...", file=sys.stderr, flush=True)
 
     h = flux.Flux()
+    print("Stopping queue...", file=sys.stderr, flush=True)
+    queue_stop(h)
 
     print("Submitting jobs...", file=sys.stderr, flush=True)
 

```

**Comment by Treece-Burgess** [comment] 2022-01-13 18:11
@grondo Thank you for the suggestions. I have tested out the additions you suggested with the `queue start` and the `queue_stop` with the RPC. My reproducer.py with those additions can be seen below: 



```
#!/usr/bin/env python3

import argparse
from collections import deque
import time
import sys
import os.path as osp
import json
from typing import Iterable, List

from numpy.random import default_rng

import flux  # pylint: disable=import-error
from flux import job  # pylint: disable=import-error
from flux.job import JobspecV1, JobID, EventLogEvent  # pylint: disable=import-error
from flux.kvs import ffi, RAW  # pylint: disable=import-error
#Added JobStats so job statistics can be contained
from flux.job.stats import JobStats

N_JOBS = 1219
SUBMISSION_WINDOW = 50  # max job submissions in flight
SLEEP_LENGTH = 10
RNG = default_rng()

subs_sent = 0
subs_in_flight = 0  # current job submissions in flight
job_ids = deque()

def queue_stop(h):
    h.rpc(
        "job-manager.alloc-admin",
        {"query_only": False, "enable": False, "reason": "benchmark"}
    ).get()

def queue_start(h):
    h.rpc(
        "job-manager.alloc-admin",
        {"query_only": False, "enable": True, "reason": "benchmark"}
    ).get()


def make_jobspec():
    if SLEEP_LENGTH is not None:
        l = SLEEP_LENGTH
    else:
        l = RNG.integers(1, 21)
    jobspec = JobspecV1.from_command(["sleep", str(l)], num_tasks=1, cores_per_task=1)
    jobspec.duration = l + 20.0
    return jobspec



def submit_some_jobs(flux_handle):
    global subs_sent, subs_in_flight

    prev_sub_sent_ct = subs_sent

    while subs_sent < N_JOBS and subs_in_flight < SUBMISSION_WINDOW:
        job.submit_async(flux_handle, make_jobspec()).then(job_init_cb)
        subs_sent += 1
        subs_in_flight += 1

    if prev_sub_sent_ct < N_JOBS and subs_sent >= N_JOBS:
        print("All jobs submitted!", file=sys.stderr, flush=True)
        print("Starting queue", file=sys.stderr, flush=True)
        queue_start(flux_handle)

def job_init_cb(fut, arg=None):
    global subs_in_flight, job_ids

    job_id = job.submit_get_id(fut)
    job_ids.append(job_id)

    subs_in_flight -= 1
    submit_some_jobs(fut.get_flux())

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--window",
        type=int,
        default=50,
        help="Maximum number of simultaneous job submissions in flight",
    )
    grp = parser.add_mutually_exclusive_group()
    grp.add_argument(
        "--sleep", type=float, default=10.0, help="Runtime of experiment jobs"
    )
    grp.add_argument(
        "--random-sleep",
        action="store_const",
        const=None,
        dest="sleep",
        help="Randomize job sleep lengths",
    )
    parser.add_argument(
        "--njobs", type=int, default=1219, help="Number of jobs to submit"
    )
    parser.add_argument(
        "--trial", type=int, help="Experiment trial number (recorded in output file)"
    )
    parser.add_argument(
        "outfile",
        nargs="?",
        default="-",
        help="Output file for job timing / status info",
    )
    args = parser.parse_args()

    N_JOBS = args.njobs
    SLEEP_LENGTH = args.sleep
    SUBMISSION_WINDOW = args.window

    print("Connecting to broker...", file=sys.stderr, flush=True)
    h = flux.Flux()
    print("Stopping queue...", file = sys.stderr, flush = True)
    queue_stop(h)

    print("Submitting jobs...", file=sys.stderr, flush=True)

    submit_some_jobs(h)
    if h.reactor_run() < 0:
        h.fatal_error("reactor start failed")
    stats = JobStats(h)
    stats.update_sync()

    while stats.active > 0:
        stats.update_sync()
        time.sleep(1)

    stats.update_sync()
    print(stats.failed)
```

However, upon testing with these additions I still had job failures occur. I went ahead and decided to increase the grace period from `l + 20.0` to `l + 50.0`. I tested the increased grace period with the addition of `queue start` and `queue stop`, and just with the increased grace period. Both resulted in 0 job failures. So it does seem increasing the grace period has a good effect on having the jobs not fail.

**Comment by grondo** [comment] 2022-01-13 18:19
Thank you @Treece-Burgess!

Just to clarify, did you test with flux-core v0.33.0 and still see many failures, or was the testing with queue stop/start also against the initially reported versions of flux-core/flux-sched (0.29.0, 0.19.0)?

Thanks again for the diligent bug reporting!

**Comment by Treece-Burgess** [comment] 2022-01-19 15:39
@grondo I did not test on flux-core v0.33.0. I currently ran the test with flux queue stop/flux queue start on c0.29.0 - s0.18.0. 

Just as a further note on the grace period: 

- `l + 20.0 ` resulted in 64 job failures
- `l + 50.0` resulted in 0 job failures as stated above

50.0 was just an arbitrary choice, and I have not tested more to find a lower bound to see when jobs again begin to fail with a lower grace period than 50.0.

**Comment by grondo** [comment] 2022-01-19 15:52
Thank you for the extra information @Treece-Burgess. When you are able to update to flux-core v0.33.0, I would expect a small improvement in results, as the main improvement to the timeout logic was added to that version. 

However, adding a longer grace time for jobs is not a bad plan if it does not otherwise affect your job throughput!

**Comment by Treece-Burgess** [comment] 2022-02-03 15:29
@grondo 

As an update, I updated Flux to version 0.33.0 - 0.19.0 and again ran 10,000 jobs with flux queue start/flux queue stop implemented. Specifics can be found below:

- Grace period: `l + 20.0` (original grace period where failures were noticed at 10,000 jobs)
- Job failures: 0 job failures noticed

So like yourself the job failures did decrease to 0 upon the update from flux-core v0.29.0 to flux-core v0.33.0 with the added flux queue start/stop.

**Comment by grondo** [comment] 2022-02-03 15:48
@Treece-Burgess, we really appreciate the report on the updated version. That is extremely helpful and my thanks go out to you. 

I'm going to close this issue, but please feel free to open new issues when you run into problems.

**Closed by grondo** 2022-02-03 15:48 UTC

**Comment by dongahn** [comment] 2022-02-03 16:59
Nice! Great job @Treece-Burgess and @grondo
