### ISSUE TITLE
resource.err[0]: verify: rank 0 (rzansel16) missing resources: gpu[2-3]

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3374] opened 2020-11-26 04:04 UTC
```console
rzansel61{dahn}26: flux mini alloc -n1 -c2 -g2
2020-11-26T03:57:50.840975Z resource.err[0]: verify: rank 0 (rzansel16) missing resources: gpu[2-3]
rzansel16{dahn}21: flux resource list
     STATE NNODES   NCORES    NGPUS
      free      1        2        2
 allocated      0        0        0
      down      0        0        0
```

When I get a nested allocation with GPUs, core's resource prints out a verification error message

**Comment by grondo** [comment] 2020-11-26 04:52
Can you paste the flux dmesg output and run `flux resource list -v` before and after the job?  I will look into it tomorrow

**Comment by garlick** [comment] 2020-11-30 22:43
As discussed on the phone, the root cause of this is #3375.  Closing.

**Closed by garlick** 2020-11-30 22:43 UTC
