### ISSUE TITLE
flux + spack + autotools = pain

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1118] opened 2017-07-21 20:32 UTC
This section of configure.ac:

```
AC_CONFIG_LINKS([ \
  t/fluxometer.lua:t/fluxometer.lua \
])
```

Produces a link of t/fluxometer.lua to t/fluxometer.lua for some reason.  This is causing problems in the spack installer where it manifests as a make error transitioning too many links, since it just loops back on itself.

**Comment by grondo** [comment] 2017-07-21 21:59
The link is required when builddir is different than srcdir, and I haven't seen any issue before where the link either removed its target (on a normal build) or linked to itself (in a vpath build). E.g. on hype, running configure in a separate build directory:

```
config.status: linking ../t/fluxometer.lua to t/fluxometer.lua
```

running configure from top_srcdir the AC_CONFIG_LINK appears to be ignored since the target exists.

What does `config.status` report in the spack build? Perhaps there is a bug in your version of autotools?

**Comment by trws** [comment] 2017-07-21 22:08
Using a different build dir fixes it for the space package, but building in-tree replaces the original file with a link for some reason. I'll check the config log when I get back to my machine, but if it is an auto tools bug it would either be in the version installed on manta or in an up to date spack built version.


---
Sent from VMware Boxer

On July 21, 2017 at 2:59:34 PM PDT, Mark Grondona <notifications@github.com> wrote:

The link is required when builddir is different than srcdir, and I haven't seen any issue before where the link either removed its target (on a normal build) or linked to itself (in a vpath build). E.g. on hype, running configure in a separate build directory:

config.status: linking ../t/fluxometer.lua to t/fluxometer.lua


running configure from top_srcdir the AC_CONFIG_LINK appears to be ignored since the target exists.

What does config.status report in the spack build? Perhaps there is a bug in your version of autotools?

**Comment by grondo** [comment] 2017-07-21 22:13
we did update to (relatively) new autotools in travis-ci and there doesn't *appear* to be an issue there, but I also tested on autoconf 2.63 (toss2) and 2.69 (toss3) and couldn't reproduce the problem.

**Comment by trws** [comment] 2017-07-21 22:26
Interestingly enough, it's autoconf 2.69 built by spack, and clearly something is fundamentally wrong here.  I'll try it on x86_64 and see if there's something going on there too, but after working around that the paths aren't fixed by install, so flux can't find any of its commands.

The build through spack is just the following with dependent packages added to the environment, I can't imagine why something would be breaking autoconf in there:

```
bash ./autogen.sh
./configure --prefix=... --disable-docs
make -j...
make -j... install
```

**Comment by garlick** [comment] 2017-09-26 17:58
Marking "help wanted" - maybe some of the research types that use spack all the time will have insight or a fix for us?

**Comment by grondo** [comment] 2017-10-18 21:59
I was able to reproduce the problem with config.status creating a circular `fluxometer.lua` file while working on #1240. However, I'm a bit stumped on how spack causes things to get into this state.

After ensuring all staging of the `flux` spack package is clean by running
```
grondo@peep:~/git/spack.git$ spack clean --all flux
==> Cleaning build stage [flux@0.8.0%gcc@6.2.0~docs arch=linux-ubuntu16.10-x86_64 /cw7hmxk]
grondo@peep:~/git/spack.git$ ls -l var/spack/stage/
total 0
grondo@peep:~/git/spack.git$ 
```
I then simply attempt a build of flux-core using spack, (with changes suggested in #1240):

```
grondo@peep:~/git/spack.git$ spack install flux@0.8.0
```

This breaks at the final stage because of the issue with `AC_CONFIG_LINKS` @trws notes above:
```
     956   Making all in t
     957   make[1]: Entering directory '/tmp/grondo/spack-stage/spack-stage-8ctxYa/flux-core-0.8.0/t'
     958   make[1]: stat: fluxometer.lua: Too many levels of symbolic links
     959   make[1]: stat: /home/grondo/git/spack.git/var/spack/stage/flux-0.8.0-cw7hmxkfhotx7iapmxxed7r2wy5co3wc/flux-core-0.8.0/t/fluxometer.lua: Too many levels of symbolic links
  >> 960   make[1]: *** No rule to make target '/home/grondo/git/spack.git/var/spack/stage/flux-0.8.0-cw7hmxkfhotx7iapmxxed7r2wy5co3wc/flux-core-0.8.0/t/fluxometer.lua', needed by 'all-am'.  Stop.
```

What I don't understand here is what spack is doing with the directories during the build, and I can't seem to find a verbose enough mode to run in to figure it out.

After this failure, we have *two* separate stage directories that are in use. One is under my `spack.git` repo under:
```
var/spack/stage/flux-0.8.0-cw7hmxkfhotx7iapmxxed7r2wy5co3wc/flux-core-0.8.0/
```
the other is a stage directory under `/tmp`
```
 /tmp/grondo/spack-stage/spack-stage-8ctxYa/flux-core-0.8.0/
```
It appears that both these directories are created as a result of `tar xvfz flux-core-0.8.0.tar.gz`, but I think the directory in `/tmp` is the actual builddir, yet for some reason spack is using `configure` from the `var/spack/stage/flux-0.8.0-*` directory, as evidenced by this line in the build.log:
```
==> Executing phase: 'configure'
==> '/home/grondo/git/spack.git/var/spack/stage/flux-0.8.0-cw7hmxkfhotx7iapmxxed7r2wy5co3wc/flux-core-0.8.0/configure' '--prefix=/home/grondo/git/spack.git/opt/spack/linux-ubuntu16.10-x86_64/gcc-6.2.0/flux-0.8.0-cw7hmxkfhotx7iapmxxed7r2wy5co3wc' '--disable-docs'
```

After `configure` completes, the build attempts to proceed in the `/tmp/*/spack-stage` directory:

```
==> Executing phase: 'build'
==> 'make' '-j32'
Making all in .
make[1]: Entering directory '/tmp/grondo/spack-stage/spack-stage-8ctxYa/flux-core-0.8.0'
```

However, both the `/tmp/grondo/spack-stage/...` and `var/spack/stage/flux-core*` directories *appear* to have had `configure` run on them... and both have had their `fluxometer.lua` files clobbered and replaced with symbolic links back to `/home/grondo/git/spack.git/var/spack/stage/flux-0.8.0-cw7hmxkfhotx7iapmxxed7r2wy5co3wc/flux-core-0.8.0/t/fluxometer.lua`

Does anyone know why there are these two build/stage directories in spack, why/how they each get `./configure` run on them?

**Comment by trws** [comment] 2017-10-18 22:04
This is beyond me, but maybe @alalazo or @tgamblin have an idea?

**Comment by tgamblin** [comment] 2017-10-18 22:26
The idea (originally) was to have everything tracked under the spack directory, but allow people to build in fast /tmp filesystems.  The links under `/var/spack/stage` are there to track build directories that may end up (especially in OS X) in really weird temporary locations.  It may be simpler for us just to get rid of those in the long run.

I suspect the issue here has something to do with changing directory to the symlinked stage path rather than the real path out in /tmp.  Does the problem go away if you add the following entry in `~/.spack/config.yaml`?

```yaml
config:
    build_stage:
    - $spack/var/spack/stage
```

**Comment by grondo** [comment] 2017-10-18 23:32
@tgamblin thanks for the hint, that is the clue I needed I think. Somehow I missed where there were symlinks between these two directories.

I did verify that if configure is run from a different populated srcdir while cwd is also a populated srcdir, this does cause `AC_CONFIG_LINKS` to overwrite the original destination with a symlink.

With autotools, it is more common to create an empty builddir and run `configure` from the srcdir in there. (this will populate all build products in the temporary builddir, but read all sources from srcdir, which may not be exactly what you wanted)

A fix on our end would be to w/a the issue by moving the affected source file to `fluxometer.lua.in`  and use AC_OUTPUT instead of AC_CONFIG_LINKS, so that the src and dst names are never the same, and we always copy. (or less likely, perhaps this is fixed in a future version of autotools)

**Comment by grondo** [comment] 2017-10-19 15:58
> Does the problem go away if you add the following entry in ~/.spack/config.yaml?

Yes, the build is successful with that change. Thanks @tgamblin!

**Comment by tgamblin** [comment] 2017-10-19 16:53
Ok we should probably switch things in Spack so that things using the stage `cd` to the real path pointed to by the symlink, not the path under the Spack tree.  I can see about making that change.

**Comment by garlick** [comment] 2022-08-17 13:30
Closing old issue.

**Closed by garlick** 2022-08-17 13:30 UTC
Labels: help wanted
