### ISSUE TITLE
support cancellation of jobs that are not running yet

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1359] opened 2018-03-15 19:08 UTC
We have `flux wreck kill` that terminates running jobs, but no `flux wreck cancel` to delete jobs from the queue before they have run.

@trws mention that `flux jstat` can be used to update a job's status, but the scheduler does not track this state change.

Where 1105 is the job id, 3 is "submitted" and 12 is "cancelled" IIRC:
```sh
$ flux jstat update 1105 state-pair '{ "state-pair":{"ostate":3,"nstate":12}}'
```

**Comment by dongahn** [comment] 2018-03-15 19:41
Modifying sched to track this state change should be straightforward, I think. I will look into this tonight.

**Comment by garlick** [comment] 2018-03-15 19:46
It might be nice if we added a `flux wreck cancel` subcommand.

**Comment by grondo** [comment] 2018-03-15 19:54
> It might be nice if we added a flux wreck cancel subcommand.

I thought the same thing. It should be trivial. Thinking about race conditions might be more tricky.

**Comment by dongahn** [comment] 2018-03-15 20:02
> Thinking about race conditions might be more tricky.

I think this is generally true for any externally invoked job control command.

Maybe we can make the semantics of `cancel` to be NOOP if the job's state isn't `pending` with a warning message? Or we can also make the semantics of `cancel` to be `kill` if the job's state is something other than `pending`. But the latter may make the control logic to be a bit more complex?

**Comment by grondo** [comment] 2018-03-15 20:43
Thanks @dongahn, I was thinking of your  first suggestion above, but the race condition is between when the state of a job is checked for `pending` and before the state is set to `canceled`. For the current implementation I don't think we need to spend too much time on this synchronization issue.

However, since the `cancel` operation only makes sense when a scheduler is loaded, would it make the problem more tractable if we sent a `sched.cancel` message to the scheduler instead of flipping the state directly in the kvs (accompanied with a message)? In the case where the scheduler has already begun to transition the job to "runrequested", it could issue an error response.

(I can't remember at the moment if we've devised other safe methods to manipulate these state values yet, I had thought not.)

**Comment by dongahn** [comment] 2018-03-15 22:10
> However, since the cancel operation only makes sense when a scheduler is loaded, would it make the problem more tractable if we sent a sched.cancel message to the scheduler instead of flipping the state directly in the kvs (accompanied with a message)?

I would think this should be fine. `wreck` already uses a message (`wreck.state.*`), which JSC subscribes to on behalf of the scheduler. So JSC can be modified to subscribed to `sched` message as well. If `sched` successfully canceled the pending job, it can update the state "synchronously" which can avoid race conditions?

**Comment by grondo** [comment] 2018-03-15 22:17
>  would think this should be fine. wreck already uses a message (wreck.state.*), which JSC subscribes to on behalf of the scheduler. So JSC can be modified to subscribed to sched message as well. If sched successfully canceled the pending job, it can update the state "synchronously" which can avoid race conditions?

Do you mean "message" or "event" here?

I'm also fine with sending an event to cancel the job, but it seems like overkill if we could instead send a direct message to the `sched.*` service.

Seems like once the job's state has been set to submitted, management of the state should be under control of the `sched` subsystem until it then changes the state to `runrequest`.

I apologize if I've confused the issue though...

**Comment by dongahn** [comment] 2018-03-16 03:31
@grondo: yes I meant an event. I think the direct message to the scheduler service should be cleaner!

**Comment by dongahn** [comment] 2018-03-16 03:49
Would `sched.cancel`=\<jobid\> message work?

**Comment by grondo** [comment] 2018-03-16 04:26
Yes, that's along the lines I was thinking. Thanks!

The cancel command in this iteration could then issue reasonable error if sched is not loaded, or when the job is not pending/submitted.

**Comment by dongahn** [comment] 2018-03-16 04:28
Yes, this sounds fine. I identified the sched code to change. So, if you do a PR on `flux wreck cancel` , I will hook it up with sched.

**Comment by grondo** [comment] 2018-03-16 15:04
@dongahn, started the work on my wreck-cancel branch if you want to use the new `flux wreck cancel ID` command to test sched changes while I finish adding tests and doc.

**Comment by dongahn** [comment] 2018-03-16 16:00
Sound great @grondo!

________________________________________

**Comment by dongahn** [comment] 2018-03-16 17:22
FYI -- just chat w/ @grondo. As part of this, I will also have a sched load option not to move the completed jobs from the run queue to the complete queue. Also the option will remove completed jobs from the job index (needed for a fast job lookup.)

Sched doesn't do this because we wanted to do this when a job REAP event is raised. But  w/ 1 - 2 million jobs, it seems this will help limit memory overhead.

**Comment by dongahn** [comment] 2018-03-17 17:15
@trws: I pushed a `sched.cancel` support in the `track_cancel` branch of my repo in case you need it soon. I need to work on some tests and other stuff before submitting a PR. But that will have to be next week.

**Comment by dongahn** [comment] 2018-03-17 17:18
@grondo: I used `errno` to pass an error code to `flux wreck cancel` like [here](https://github.com/dongahn/flux-sched/blob/track_cancel/sched/sched.c#L1760). But is this a right way to do things? This is an error in terms of the requester but it is a soft error for sched module and I'm afraid if there are other side-effect. Do you use `errno` this way for other modules?

**Comment by grondo** [comment] 2018-03-17 18:43
Use of errno seems correct there, thanks! If it is easy it would be nice if sched set the job state to "cancelled" as well. (sorry if I missed that you already did that, reading on my phone)

**Comment by dongahn** [comment] 2018-03-17 20:33
Thanks @grondo. Yes, I plan to do that next week. I couldn't get to everything I wanted to get to yesterday. But wanted to make sure @tws get minimal support if he wants to test soon.

**Comment by grondo** [comment] 2018-03-17 20:50
@dongahn, OK great, sorry to bug you on the weekend!

**Comment by trws** [comment] 2018-03-17 23:10
Thanks both of you. I’m workin on some unexpected build issues in integrating things, will check this out soon. Also looking at reducing the contents of resrc, maybe a filter list to reduce what it cares about from hwloc, or maybe figure out how to load a machine conf for it..?


---
Sent from VMware Boxer

On March 17, 2018 at 1:51:23 PM PDT, Mark Grondona <notifications@github.com> wrote:

@dongahn<https://github.com/dongahn>, OK great, sorry to bug you on the weekend!

**Comment by dongahn** [comment] 2018-03-18 04:08
> Also looking at reducing the contents of resrc, maybe a filter list to reduce what it cares about from hwloc, or maybe figure out how to load a machine conf for it..?

I think it will be good to see what operations are actually the scalability bottlenecks. If KVS-fetching 2000 individial xml buffers is the bottleneck, we may want to see if we can sligtly change its layout in KVS such that the scheduler can load in the entire thing at once. The scheduler then can iterate through each individual buffer off of its local memory.

The other optimization maybe, hwloc module combines all of the individual  hwloc profiles into a large profile. Then the scheduler calls hwloc_init once. Not sure how much it will reduce.

Right now, `verbosity=level` will print out more verbose info which includes resrc info. But this may print too much at large scale. We can add a few debug print statements under this load option to get some timing info. I can look into adding some debug statements Monday unless you beat me to it. If changing the layout is a reasonable venue, i will have to rely on you for the layout change as you are more familiar with hwloc module than me. But I can hook it into the scheduler easily and see the impact.

Reduced hwloc data into hwloc light is also an option although the changes may be a bit involved. Good for the long haul though.

**Comment by grondo** [comment] 2018-03-18 15:45
I think @garlick was already thinking about how a reduction or content store could be used here to squash the hwloc data in a scalable way. Might want to sync up with him on Monday. But it would seem trivial if hwloc data can be normalized per system so that identical nodes are only parsed once...

**Comment by garlick** [comment] 2018-03-18 16:37
Possibly this requires more thought, but to get things started, here's one idea for a simple reduction:  If we can normalize XML on like nodes as @grondo suggests,

1) each node writes XML directly to content store instead of KVS, getting back a blobref.  This is low overhead if blob already exists in the content cache (it is "squashed" if encountered on its way up the TBON).

2) the node then appends its rank to a KVS key named for the blobref.  The new KVS append operation allows this to be done atomically, e.g. without read-modify-write races.

3) sched iterates through unique keys (corresponding to unique hwloc XML's), fetching the key name from the content store, and fetching the KVS value to obtain the list of ranks that have that resource config.  (Possibly it could be arranged so that this can be parsed directly as a nodeset, if that is useful)

So for example you might have:
```
resource.hwloc.reduced.sha1:!!8843D7F92416211DE9EBB963FF4CE28125932878 = "0,"
resource.hwloc.reduced.sha1:!!0BEEC7B5EA3F0FDBC95D0DD47F3C5BC275DA8A33 = "1,4,3,2,42"
etc
```

Caveat:  since blobref contains URI-style sha1:// prefix and / is about to be used as a KVS namespace prefix, I converted it to sha1:!! in the example above.  It would have to be restored before fetching XML from the content store.

I would be happy to implement the resource-hwloc side of this on monday as an experiment, if it seems useful.

**Comment by dongahn** [comment] 2018-03-19 03:33
Sounds pretty promising @garlick!

A question is how reduceable the nodes' hwloc data are. I think 99% data would be identifical across nodes but there will be the node specific information, most notably hostname. Will this negatively affect the degree of reduction?

**Comment by trws** [comment] 2018-03-19 15:44
hwloc provides a diff function.  Unfortunately if it has cpusets it 
deems the differences too complex and fails.  Taking a few minutes to 
see if there's a way to normalize some of this out.

**Comment by trws** [comment] 2018-03-19 15:53
This may be more trouble than it is worth for sierra, the nodes don't 
seem to have a consistent hierarchy or physical core ID ordering, which 
causes the diff to fail between essentially every pair of nodes.  Out of 
500 nodes compressed, it managed to compress about 50.  Probably 
something to keep in mind, but not really helpful for the task at hand.

**Comment by dongahn** [comment] 2018-03-19 16:23
> Probably something to keep in mind, but not really helpful for the task at hand.

@trws: Agreed. Given the aggressive time frame of the Splash project, it seems we want to go for low hanging fruits for now.

I am going to create a branch in my repo with the debug statements in sched. I'd like to see where the time is going. 5 mins are bad but it is a one time cost which gets amortized over time.

**Comment by trws** [comment] 2018-03-19 16:27
The problem is that it really isn't one-time, there are too many places 
in sched that touch *everything* in the hardware tree that I can't 
factor out fast enough.  I'm going to hack together a "simple" reader 
that will read the by_rank directory and build a high-level resrc tree 
that only represents nodes, sockets and cores by count.  O(n) is still 
not good, but at least if I can take N from roughly 150*nodes to roughly 
30*nodes it should help with the slow progress in the scheduling loop.

**Comment by dongahn** [comment] 2018-03-19 16:36
> The problem is that it really isn't one-time, there are too many places
in sched that touch *everything* in the hardware tree that I can't
factor out fast enough. 

Yeah... unfortunately, this is serious and in a sense a known problem.

>  I'm going to hack together a "simple" reader
that will read the by_rank directory and build a high-level resrc tree
that only represents nodes, sockets and cores by count. 

Yes, if the scheduler doesn't have to schedule which particular cores to run jobs, this is an excellent way to coarsen the resource representation.

**Comment by dongahn** [comment] 2018-03-19 16:39
> Yes, if the scheduler doesn't have to schedule which particular cores to run jobs, this is an excellent way to coarsen the resource representation.

Flexible resource model is what @tpatki and I have been looking at with the new scheduling infrastructure piece as part of ECP. I believe I can use the lessons you learn here towards that effort as well. Cool.

**Comment by garlick** [comment] 2018-03-19 17:04
Would it be better to do this in conjunction with a `--lite` option in resource-hwloc that skips adding the data we aren't going to use, or reduces it as proposed above?

**Comment by trws** [comment] 2018-03-19 17:12
Quite possibly.  I may even implement it that way so that schedule 
doesn't have to care.

**Comment by grondo** [comment] 2018-03-28 23:45
I think with merge of flux-framework/flux-sched#291 this issue is resolved? OK to close it?

**Comment by trws** [comment] 2018-03-29 16:55
Agreed, thanks for the triage @grondo!

**Closed by trws** 2018-03-29 16:55 UTC
