### ISSUE TITLE
Spurious EBADF errno being set

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#253] opened 2015-07-09 02:11 UTC
After sitting down with @trws and working through some issues with the kvs python bindings (#236) , we are stumped by what seems to be an unhandled (and asymptomatic) EBADF being set somewhere in the comms system and bubbling up through the kvs API.  The kvs calls succeed and return 0, but the errno is set to 9.  The python bindings were set to throw an Exception anytime the errno was non-zero.  In this case, if we ignore the errno, the json response is correct.  So for now, that is what the python bindings do, ignore errno when the return is 0.

It might also be what I was seeing in #232.

**Comment by garlick** [comment] 2015-07-09 04:29
From [POSIX.1](http://pubs.opengroup.org/onlinepubs/9699919799/functions/errno.html):

> The value of errno should only be examined when it is indicated to be valid by a function's return value.

Somewhere we are probably handling an error and leaving the errno set.  AFAIK that's the usual practice so not a bug?  Python bindings definitely should not throw an error unless errno is valid as defined above.

**Comment by trws** [comment] 2015-07-09 15:00
Clearly that's a mistake on my part.  The idea was to generalize the error checks to get a reasonable pythonic response to error, and I had thought it would be reasonable to do it by saving/clearing errno, calling into flux, then checking errno afterwards.  It works the majority of the time, but clearly I need to more accurately represent our error conventions in the wrapper.

@garlick, would you say this pseudocode is a reasonable general error condition? I'll make it possible to override it for functions where it's inappropriate.  I don't know if there is a reasonable generalization for types other than pointer and signed integer types, do we have a convention for error reporting in double or other type functions?

```python
maybe_err = False
if return_type.kind == 'pointer' and result == NULL:
  maybe_err = True
elif return_type in ['int', 'char', 'long', 'long long', 'int64_t', 'int32_t', 'int16_t'] and result < 0:
  maybe_err = True
if maybe_err and errno != 0:
  raise ...
```

**Comment by garlick** [comment] 2015-07-09 16:19
That pseudo code looks good.  I don't think you need to cover other return types.  I think we can say that all functions that set errno return either a pointer or integer, however the converse is not always true.

**Comment by trws** [comment] 2015-07-09 18:19
The most recent version of the bindings has been reworked to check errors as discussed.  @SteVwonder  if you get a chance could you test the update and see if it addresses your test case? My unit tests seem to be getting the correct error, and non-error, behavior but you hit a pretty tricky corner case.

**Comment by SteVwonder** [comment] 2015-07-09 20:16
Yep.  Seems to work for me too.

```
4
result: 0, err: 0
4.nnodes = 8
result: 0, err: 0
4.ntasks = 128
result: 0, err: 9
4.create-time = 2015-07-09T13:16:10
result: 0, err: 9
4.state = submitted
result: 0, err: 9
4.user = 72ea8dd4f90557cd68b4da1475294fda
result: 0, err: 9
4.jobname = bc9879c7e9936d47bfed8e55a05e7ca3
result: 0, err: 9
4.account = 017a220790418f0a62dcd1e46b7db9ed
result: 0, err: 9
4.submit_time = 866.0
result: 0, err: 9
4.execution_time = 56227.0
result: 0, err: 9
4.time_limit = 57600.0
result: 0, err: 0
4.ncpus = 128
result: 0, err: 0
4.io_rate = 2
result: None, err: 0
result: 0, err: 0
result: None, err: 0
```

**Comment by trws** [comment] 2015-07-09 20:47
Glad to hear it.  Since this is really a problem with the bindings, and seems to be addressed, I'm closing the issue.

**Closed** 2015-07-09 20:47 UTC
