### ISSUE TITLE
GPU oversubscription with no GPU requested

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#4724] opened 2022-10-26 19:33 UTC
This example comes from @gyllenhaal1.  The thread distribution is at least for now what was requested, but there are no GPUs requested (unless we treat this as exclusive) and even if there were somehow all tasks receive GPU 1, not zero, not all of them, 1.  This hurts my brain thinking about how precisely this could have happened honestly, it's like getting a segfault on ptr==7.  Either way, something funny is going on that we probably want to clean up.

```console
$ flux mini run  -N 1 -n 8 ./print_openmp_mapping_tioga | sort
tioga25      Threads 1 Map 56 OMP_NUM_THREADS=1 OMP_PROC_BIND=spread OMP_PLACES=threads ROCR_VISIBLE_DEVICES=1
tioga25      Threads 1 Map 57 OMP_NUM_THREADS=1 OMP_PROC_BIND=spread OMP_PLACES=threads ROCR_VISIBLE_DEVICES=1
tioga25      Threads 1 Map 58 OMP_NUM_THREADS=1 OMP_PROC_BIND=spread OMP_PLACES=threads ROCR_VISIBLE_DEVICES=1
tioga25      Threads 1 Map 59 OMP_NUM_THREADS=1 OMP_PROC_BIND=spread OMP_PLACES=threads ROCR_VISIBLE_DEVICES=1
tioga25      Threads 1 Map 60 OMP_NUM_THREADS=1 OMP_PROC_BIND=spread OMP_PLACES=threads ROCR_VISIBLE_DEVICES=1
tioga25      Threads 1 Map 61 OMP_NUM_THREADS=1 OMP_PROC_BIND=spread OMP_PLACES=threads ROCR_VISIBLE_DEVICES=1
tioga25      Threads 1 Map 62 OMP_NUM_THREADS=1 OMP_PROC_BIND=spread OMP_PLACES=threads ROCR_VISIBLE_DEVICES=1
tioga25      Threads 1 Map 63 OMP_NUM_THREADS=1 OMP_PROC_BIND=spread OMP_PLACES=threads ROCR_VISIBLE_DEVICES=1
```

**Comment by grondo** [comment] 2022-10-26 19:50
Do you know if this was run from within an allocation or against a system instance with one of the exclusive node allocation policies? 

It would also help to include the R generated for this job. Without `-o gpu-affinity=per-task` all tasks running under a given shell will have the same `ROCR_VISIBLE_DEVICES`, and this should be set to the same set as in R, so I'm also confused what is going on here.

**Comment by grondo** [comment] 2022-10-26 20:44
Apparently in this case the `mpibind` plugin is making the ROCR_VISIBLE_DEVICES assignment here. According to @ryanday36:

> The specifics of the GPU assignments here is from the mpibind plugin, though it is related to https://github.com/flux-framework/flux-core/issues/4622 and Flux not being aware of the node hardware topology more generally. Mpibind is trying to assign the GPUs that are in the same NUMA domain as the assigned CPUs. In the example from John’s email, Flux assigns all of the tasks to cores from the same NUMA domain, so mpibind assigns them all the same GPU. That’s probably not the best behavior for mpibind in that specific case, but it would also be much better if ‘flux mini run -n8 -g1 …’ assigned those 8 tasks to cores from different NUMA domains.

Closing this issue as a duplicate of #4622

**Closed by grondo** 2022-10-26 20:44 UTC

**Comment by trws** [comment] 2022-10-27 16:36
Got it, thanks @grondo.
