### ISSUE TITLE
Unable to launch flux using OpenMPI 3.1.1

### ISSUE THREAD

**Issue by damora** [flux-framework/flux-core#1637] opened 2018-08-31 12:39 UTC
Executing:
 mpiexec -np 3  -host 172.17.0.16,172.17.1.0,172.17.1.1 /shared/libraries/flux-core/bin/flux start
 where the -host ip addresses are for the Mellanox IB NICs on 3 different servers

No errors are returned when passing -v, but the flux broker does not start on any servers other than the first (172.17.0.16).

I can launch a multi node flux-broker with mpich hydra and everything works as expected when running an MPI application

**Comment by garlick** [comment] 2018-08-31 13:48
Is it possible that all three brokers are launched but they each think they are a standalone instance?

It might be a PMI problem.  One thing to try is to turn up the PMI debugging in flux by setting `FLUX_PMI_DEBUG=1` in the environment which will cause Flux's PMI client to emit some traces of its PMI calls on stderr (which you could post here if you like).

If launching within an allocation of another RM, maybe some environment of the original RM are leaking through and confusing Flux, as in #1619?

@trws did you ever try launching Flux with OpenMPI's mpiexec/mpirun?

**Comment by trws** [comment] 2018-08-31 16:27
Yup, that's what I see when I try it on a local debian VM, (with 3.1.2, happens to be current sid ver).  It starts three independent brokers, then two immediately tear down.

I did try it, and this used to work perfectly, let me poke around for a bit and see if they changed something.

**Comment by trws** [comment] 2018-08-31 16:39
Ok, looks like two things.  One, this version of OpenMPI, at least on Debian, is packaged without the pmi library, it's in a separate package libpmi-pmi[01]-pmix or libpmi-pmix-dev.  The second problem is that `liblist_create` in wrap.c looks explicitly for "libpmi.so" and fails to find either the libpmi.so.1 or libpmi.so.2 that gets installed when pmi is installed.

**Comment by trws** [comment] 2018-08-31 16:40
I should say, when I add a symlink to libpmi.so.1 named libpmi.so, it all works as expected.

**Comment by grondo** [comment] 2018-08-31 16:53
Thanks @trws! Can you verify you have the `-dev` version of the package that installed libpmi.so.1? Typically the link from the `.so` to `.so.<version>` is in a `-dev` package, so I wonder if it is as simple as that?

**Comment by damora** [comment] 2018-08-31 16:53
umm, I linked openmpi using the libpmi that gets installed with flux. I am on RHEL and I don't think there is a libpmi distro. There is a libpmix distro that gets shipped with Spectum MPI, but wasn't sure if that would work

**Comment by trws** [comment] 2018-08-31 17:02
I do, it’s not there because the -dev package installs both a .1 and a 
.2, they must have decided not to default one of them.

**Comment by grondo** [comment] 2018-08-31 17:04
> I do, it’s not there because the -dev package installs both a .1 and a .2, they must have decided not to default one of them.

Ok, off-topic since @damora notes the issue is on RHEL, but this seems like a packaging problem since how would a linker find a version of libpmi if you were compiling with `-lpmi`? (maybe irrelevant since that is not the intended use of libpmi.so.X?)

**Comment by trws** [comment] 2018-08-31 17:07
It looks like I was partly wrong, it does install a libpmi.so, but it 
installs it into the lib subdirectory of pmix.

**Comment by SteVwonder** [comment] 2018-08-31 17:11
@damora which version of Flux are you using (a tagged version, or just master)?  And are you using RHEL 6 or RHEL 7?

**Comment by trws** [comment] 2018-08-31 17:14
Spectrum tells me this is on a sierra-like.  The version of OpenMPI, and spectrum itself, are sometimes compiled without the pmi compatibility library for pmix installed.  You can build and install it separately, or even locally to a project, but we need some kind of regular pmi1/2 to work currently.

**Comment by damora** [comment] 2018-08-31 17:18
RHEL7.5 (Maipo). ppc64le

I am using OpenMPI 3.1.1 and I linked with the libpmi.so that is installed with flux 0.9.0

**Comment by trws** [comment] 2018-08-31 17:19
That should work for your user application, but I mean that flux itself must have a PMI from the launcher to work, so you need to install the OpenMPI 3.1.1 libpmi compatibility library.

**Comment by damora** [comment] 2018-08-31 17:53
@trws flux builds its own version of libpmi, correct? If I build OpenMPI with that same libpmi, shouldn't that work? Bot flux and openmpi would be referencing the same library.

**Comment by trws** [comment] 2018-08-31 18:10
No, it wouldn’t.  Flux provides a pmi interface to launch 
applications.  If you want to launch flux with OpenMPI, then OpenMPI has 
to provide a pmi interface to launch flux, since the flux overlay 
doesn’t exist for it to use yet.  Does that make sense?

**Comment by grondo** [comment] 2018-08-31 18:11
> flux builds its own version of libpmi, correct? If I build OpenMPI with that same libpmi, shouldn't that work? Bot flux and openmpi would be referencing the same library.

PMI can cause a bit of confusion. The purpose of libpmi is for the "launcher" environment to provide an independent API to assist a parallel program with wireup and initialization.

Since Flux is both a parallel program and a launch environment, it is both a provider and user of libpmi. When launching a flux instance, the launch environment needs to be the provider of libpmi (in this case OpenMPI mpiexec). When *Flux* is launching applications (including flux itself), they then use Flux's libpmi.

Hope that helps.

**Comment by damora** [comment] 2018-08-31 18:32
yes, that does help. I need a version of OpenMPI that comes with libpmi as its launcher.

**Comment by damora** [comment] 2018-08-31 19:37
after consulting with some of our MPI experts, it seems that OpenMPI can be build with PMIx support but not PMI. Will I be able to launch multiple flux instances if my OpenMPI has PMIx support?

**Comment by dongahn** [comment] 2018-08-31 19:51
> after consulting with some of our MPI experts, it seems that OpenMPI can be build with PMIx support but not PMI. Will I be able to launch multiple flux instances if my OpenMPI has PMIx support?

Yes, you should be able to build the PMI library that comes with Flux against the public PMIX and bootstrapping a Flux instance. That's what we do on Sierra.

**Comment by garlick** [comment] 2018-08-31 19:52
The latest flux-core includes support for launching with libpmix.  You have to configure flux-core  `--with-pmix` though.   It basically implements the pmix pmi-1 compat library within flux, Spectrum MPI developers gave us the same "no" answer to supplying those compat libraries.

**Comment by trws** [comment] 2018-08-31 22:04
Thanks @garlick.  If that option works for you @damora, by all means use it.  

If you want to build them, the [pmix repository](https://github.com/pmix/pmix) includes the compatibility libraries, and in fact builds them by default as part of building pmix.  OpenMPI's source distribution admittedly does not, its internal pmix has evidently been stripped down for whatever reason.  RHEL and Fedora do not package pmix, or its compat libraries, separately either, hence this rather unfortunate snarl where we end up with a hard-to-use build of OpenMPI.

**Comment by dongahn** [comment] 2018-08-31 22:10
Also just FYI -- my experience was that porting pmi backward compatibility libraries against a public version of PMIX (bundled with Spectrum) was also straightforward. Just in case `--with-pmix` has issues, which I doubt.

**Comment by damora** [comment] 2018-09-06 14:08
downloaded pmix library. Compiled OpenMPI 3.1.1 using the pmix 2.1.3 external library. Can run mpi applications, but still can't start flux. I guess I don't really understand how this is supposed to work.

**Comment by dongahn** [comment] 2018-09-06 15:56
What is the output when FLUX_PMI_DEBUG=1 is set?

Did you build flux with `--with-pmix`?

**Comment by damora** [comment] 2018-09-06 15:58
yes, I did build flux using --with-pmix
**pmi_wrap_create: using /shared/libraries/pmix/lib/libpmi.so**
0: PMI_Init rc=0 
0: PMI_Get_size rc=0 
0: PMI_Get_rank rc=0 
0: PMI_Get_appnum rc=0 
0: PMI_KVS_Get_name_length_max rc=0 
0: PMI_KVS_Get_my_name ("456392705") rc=0
0: PMI_KVS_Get_key_length_max rc=0 
0: PMI_KVS_Get_value_length_max rc=0 
0: PMI_KVS_Put ("456392705", "cmbd.0.uri", "tcp://10.1.1.16:49152") rc=0 
0: PMI_KVS_Commit rc=0 
**PMI_Init: library search failed, use singleton**
0: PMI_Init rc=0 
0: PMI_Get_size rc=0 
0: PMI_Get_rank rc=0 
0: PMI_Get_appnum rc=0 
PMI_Init: library search failed, use singleton
0: PMI_Init rc=0 
0: PMI_Get_size rc=0 
0: PMI_Get_rank rc=0 
0: PMI_Get_appnum rc=0 
0: PMI_KVS_Get_name_length_max rc=0 
0: PMI_KVS_Get_my_name ("single-22452") rc=0
0: PMI_KVS_Get_key_length_max rc=0 
0: PMI_KVS_Get_value_length_max rc=0 
0: PMI_KVS_Get_name_length_max rc=0 
0: PMI_KVS_Get_my_name ("single-73421") rc=0
0: PMI_KVS_Get_key_length_max rc=0 
0: PMI_KVS_Get_value_length_max rc=0 
0: PMI_KVS_Put ("single-22452", "cmbd.0.uri", "tcp://10.1.3.1:49152") rc=0 
0: PMI_KVS_Commit rc=0 
0: PMI_Barrier rc=0 
0: PMI_Barrier rc=0 
0: PMI_Finalize rc=0 
0: PMI_KVS_Put ("single-73421", "cmbd.0.uri", "tcp://10.1.3.0:49152") rc=0 
0: PMI_KVS_Commit rc=0 
0: PMI_Barrier rc=0 
0: PMI_Barrier rc=0 
0: PMI_Finalize rc=0

**Comment by garlick** [comment] 2018-09-07 15:32
The trace is a little hard to sort out since all the ranks think they are rank 0, however, it looks like

* one rank bootstraps using side-built pmix, and determines rank=0, size=3
* two ranks don't find a PMI library and assume singleton, rank=0, size=1

As far as flux is concerned, the first case should be blocked waiting for ranks 1,2 to connect, and the second case should be booting up standalone.

Can you launch an mpi program using your setup?  What about running printenv on all three ranks and trying to see what's different in the environment?

**Comment by grondo** [comment] 2018-09-07 16:26
> two ranks don't find a PMI library and assume singleton, rank=0, size=1

`mpiexec` may not export the current environment to remote processes by default. Another experiement to try would be `mpiexec -x LD_LIBRARY_PATH ...`

**Comment by damora** [comment] 2018-09-07 16:46
@garlick  @grondo I can launch mpi program with correct results. The environments should be the same because user launching program has a mounted home directory. I am seeing an mca error though:
**pmix_mca_base_component_repository_open: "mca_psensor_file" does not appear to be a valid psensor MCA dynamic component (ignored): /shared/libraries/pmix/lib/pmix/mca_psensor_file.so: undefined symbol: mca_psensor_file_component. ret -1**

**Comment by dongahn** [comment] 2018-09-07 16:52
Maybe `PMIX_SERVER_URI` or `PMIX_SERVER_URI2` envVar isn't set on the other node...

**Comment by damora** [comment] 2018-09-07 16:54
PMIX_SERVER_URI21=pmix-server.122193;tcp4://127.0.0.1:48687
PMIX_SERVER_URI2=pmix-server.122193;tcp4://127.0.0.1:48687
PMIX_SERVER_URI21=pmix-server.5329;tcp4://127.0.0.1:43107
PMIX_SERVER_URI21=pmix-server.63130;tcp4://127.0.0.1:40745
PMIX_SERVER_URI2=pmix-server.5329;tcp4://127.0.0.1:43107
PMIX_SERVER_URI2=pmix-server.63130;tcp4://127.0.0.1:40745

**Comment by dongahn** [comment] 2018-09-07 16:56
Are they from different nodes or just one node?

Is each node setting `PMIX_SERVER_URI21` alone or both `PMIX_SERVER_URI2` and `PMIX_SERVER_URI21`?

**Comment by damora** [comment] 2018-09-07 18:28
@dongahn 
Hello world from host fstgb016, process 0 of 3 **PMIX_SERVER_URI21: pmix-server.115499;tcp4://127.0.0.1:43929
 PMIX_SERVER_URI2:pmix-server.115499;tcp4://127.0.0.1:43929**

Hello world from host mingb000, process 1 of 3 **PMIX_SERVER_URI21: pmix-server.81313;tcp4://127.0.0.1:37685
 PMIX_SERVER_URI2:pmix-server.81313;tcp4://127.0.0.1:37685**

Hello world from host mingb001, process 2 of 3 **PMIX_SERVER_URI21: pmix-server.24443;tcp4://127.0.0.1:43805
 PMIX_SERVER_URI2:pmix-server.24443;tcp4://127.0.0.1:43805**

**Comment by garlick** [comment] 2018-09-07 21:35
> Not really clear on how PMIX works. Does mpirun start a server on each node and then the servers communicate with other to coordinate message passing with MPI or to coordinate flux-broker communications between nodes?

Pretty much, except PMI is used primarily just to bootstrap the processes that make up your MPI program.  Each process gets the size of the program, and its rank with in it, publishes its own network address, and obtains the network addresses of other ranks it wants to connect with.  MPI then wires up and PMI is (usually) out of the picture.

Flux runs exactly like an MPI program.

One of your three processes is bootstrapping correctly (I surmise though I could be wrong).  It is finding the libpmi.so library provided by your side installed pmix.  That library is then using the PMIX_SERVER_URI2 info to connect to the local pmix service.  It sees that it's rank 0 of a size=3 program.

Two of your three processes are going wrong somewhere.  They are not finding that same libpmi.so.  That could be for a number of reasons, like different LD_LIBRARY_PATH, different LD_PRELOAD, different network file system configs, etc..

I'm a little surprised that the two going wrong don't see PMIX_SERVER_URI2 in their environment and then use the flux pmix support, if you built flux `--with-pmix`.  With that configure option, flux should already be linked directly with the libpmix.so.  It will use it if it doesn't find a "normal" pmi library first like it did on the one rank.  Instead it doesn't try (maybe it does't see PMIX_SERVIER_URI2?), and falls through to the singleton PMI config.

**Comment by dongahn** [comment] 2018-09-10 18:28
@damora: I think flux should use its own pmi which links with the public pmix library.

**Comment by garlick** [comment] 2018-09-10 18:38
Right, the internal flux pmi library is always built.  Flux calls into that, and it decides how to interface with the available libraries or services.

Also `--with-pmix` is having no effect in your case, since your side-build pmix is providing the libpmi.so compatibility library and flux uses that if available.  (On rank 0 anyway - ranks 1 and 2 can't find libpmi.so and aren't seeing the PMIX_SERVER_URI2 environment variable to trigger the use of pmix it was built with).

I think the problem must be related to the environment on ranks 1 and 2.

**Comment by garlick** [comment] 2018-09-10 22:05
No problem.  Good luck!  I'll go ahead and close this and you can open another one if you encounter other difficulties that seem less than obvious.

**Closed by garlick** 2018-09-10 22:05 UTC
