### ISSUE TITLE
wreck job state changes cannot be reliably collected by JSC

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#234] opened 2015-06-29 19:34 UTC
I am hitting new JSC test failures when I test my branch for PR #225 in an Ubuntu 14.04 VM running under VirtualBox on a mac mini.  I have not seen these failures on travis or my RHEL 6 desktop.  These failures don't reproduce on the same VM when I switch to master 62d7580 so it would seem like something I've introduced.  However, as @grondo was hitting jsc failures in his PR #231, I wanted to get this open in case the problem is a fragile test.

Output from failure of test 3: notification works from multiple wreckruns
```
#	
#	    run_flux_jstat 3 &&
#	    p=$( sync_flux_jstat 3 ) &&
#	    run_timeout 4 flux wreckrun -n4 -N4 hostname &&
#		run_timeout 4 flux wreckrun -n4 -N4 hostname &&
#		run_timeout 4 flux wreckrun -n4 -N4 hostname &&
#	    cat >expected <<-EOF &&
#	$trans
#	$trans
#	$trans
#	EOF
#	    cp output.3 output.3.cp &&
#	    kill -INT $p &&
#	    test_cmp expected output.3.cp 
#	
```
When i `diff -u` the test_cmp files I get:
```
--- trash-directory.t2001-jsc/expected	2015-06-29 12:10:49.000000000 -0700
+++ trash-directory.t2001-jsc/output.3	2015-06-29 12:10:40.000000000 -0700
@@ -1,7 +1,7 @@
 null->null
 null->reserved
-reserved->starting
-starting->running
+reserved->running
+running->running
 running->complete
 null->null
```
It would seem that some job state transitions are not being logged as expected.   @dongahn could this be a manifestation of the `lwj.nextid` vs `lwj.N.state` race discussed in PR #205?

**Comment by grondo** [comment] 2015-06-29 20:18
We discussed this a bit in the meeting today and in general how some communications and synchronization via the KVS could be racy if not done properly.  Admittedly, the ad-hoc implementation used by wreckrun could be partially to blame here, but this requires more investigation.

@trws had the idea to write up an RFC on the topic of using KVS for distributed communication and maybe some methods for success and things to avoid (?). Tom was going to start a rough outline (thanks, Tom!) and then maybe open up for group comment.

(Sorry, that is only tangentially related to this issue, but items discussed in KVS usage RFC may uncover some issues as discussed in #205 and potentially this issue as well.)

**Comment by grondo** [comment] 2015-06-29 21:10
BTW, I should mention what I'm seeing on the `subprocess-io` branch are intermittent hangs in the jsc tests. I haven't been able to debug yet, but to me it looks like a `flux-wreckrun` problem and not an issue in the tests.

**Comment by garlick** [comment] 2015-06-29 21:59
Thanks!  The RFC on KVS synchronization sounds great, and I'll be happy to contribute to that if @trws wants to get one started.

I better run this down further before pointing the finger at the jsc tests if @grondo's failures were hangs.  Sorry I should have remembered that.

**Comment by dongahn** [comment] 2015-06-29 22:09
Yes, it does seem like the similar race issue. The "starting" event was probably generated during the "black-out period." I would be happy to contribute to the RFC on KVS synchronization. It seems we need to identify as many patterns as possible with KVS and see what's covered and what's not with the current mechanisms. We can think of ways to support what's not covered if they are common, I guess.

**Comment by garlick** [comment] 2015-06-29 22:35
Well what do you think @dongahn, should I dig deeper to try to find out the root cause of the failures or is it pretty clear that this is due to incorrect synchronization between jsc and wreck?  I am currently responding by writing more tests for my changes which is not a bad thing so maybe you don't have to answer that right away :-)  If however the jsc tests are going to keep failing, then we should probably disable the tests until the race is resolved.

**Comment by dongahn** [comment] 2015-06-30 15:32
@garlick @grondo. I  propose we look this a bit further. There is one thing my "extended black-out period" issue doesn't seem to explain quite well. I wanted to look at the wrexec code and my test code a bit, but I have a short LDRD meeting this morning so I have to go. Looking at the diff, it seems the new job state transition JSC sees via the KVS watch trick is now:

null->null
null->reserved
reserved->running
running->running
running->complete

Now, essentially, JSC broke the race (described in #205 ) by posting "NULL" event to its client (e.g., scheduler) before installing the watcher to "lwj.id.state." Because of this delay, a clear "happends-before" relation is formed between NULL event and other events coming out of wrexec. But this is at the expense of JSC now CAN miss some initial state sequence generated by wrexec. But in this case, I would expect we wouldn't see the "reserve" state either... but it missed the sequence, it will miss the whole initial sequence. 

I will take a look at this a bit closely after the meeting today. 

In any case, the whole issue seems to arise due to lack of atomicity or synchronization implementation somewhere -- which I think can be either solved by adding some primitive support in KVS or implementing explicit consumer-producer synchronization.

I think one way to effective push this dialogue forward is to have the couple of issues we encountered with JSC into a set of slides and see at what point we can implement the  atomicity or synchronization if they are representative cases and other KVS consumers and producers can use the same patterns. 

I will capture this in the slides but we should probably want to use another PR or distribution list to push it forward.

**Comment by garlick** [comment] 2015-06-30 18:46
What about the idea someone (?) had in our project meeting about appending states to the `lwj.N.state` key rather than replacing them?  Would that solve the race with the least effort?

For example in the worst case, the whole job runs to completion before the watch is installed on `lwj.N.state`.  Then JSC gets one callback (the initial one) and walks through all of the states stored in the value.

**Comment by grondo** [comment] 2015-06-30 20:36
I like that idea because it doesn't force a job to change state in lockstep with one (or possibly more!) "consumers of state".

Already (for general interest, there is no user of it) wrexecd puts a key
```
<state>-time = <timestamp>
``` 
into the lwj.<id> dir for each state change. This could easily be put into a `state-log` file or something instead. There was no reason I put the timestamps into different keys except to avoid read-modify-write.

**Comment by garlick** [comment] 2015-06-30 20:47
I updated issue #206 with some of the challenges of adding new synchronization to the KVS to solve this.   If we can work around it another way and perhaps document the approach as a best practice in the aforementioned RFC, that would be an easy way out.

Not that we should avoid the hard way if it's the right way.

**Comment by garlick** [comment] 2015-07-01 19:52
These tests are (temporarily) disabled now pending a solution for the race.  Since the root of the problem is assumed to be the incorrect synchronization, and the tests are just showing that, I'll change the title of this issue to reflect the problem that we need to solve.

**Comment by grondo** [comment] 2015-07-01 20:50
It would be nice if someone could design a test that failed every time, demonstrating this race.
Then we could run it under `test_expect_failure` and have it marked as a TODO

**Comment by dongahn** [comment] 2015-07-01 20:54
Sorry I am not fully convinced this is due to the race yet. I am taking a look at this.

**Comment by garlick** [comment] 2015-07-01 21:41
Uh oh, sorry if I misinterpreted your earlier comments @dongahn. I will
spend some time looking at this in my VM where it seems prone to failure.

**Comment by dongahn** [comment] 2015-07-01 21:54
@garlick: no problem. I had hard time to reproduce this on Cab, so I  induced some delay to JSC's installing the state watch to increase the black-out period. When I did this, the job state change misbehaved but as I expected. 

``
null->null
null->running
running->complete
``

This is expected because JSC misses the initial state transitions wholly. The these states are not reported:

``null->reserved, 
reserved->starting 
and starting->running`` 

The observed transition reported above is, though, as if JSC got notified of all of the state changes except that it got "running" in place of "starting."

``
null->null
null->reserved
reserved->running
running->running
running->complete
``

The JSC race is still a possibility. But this could also be 1) wreck actually update the state with "running" instead of "starting," or 2) KVS  passes the new value on the watch triggered for the old value... Can 2) condition occur if the state changes occur so quickly between starting and running?

Sorry I could have been much more precise if I have the same VM environment. (I should get one soon.)

**Comment by dongahn** [comment] 2015-07-01 22:05
@grondo: adding a sufficiently long delay to JSC right before installing the job state watch probably can show the black-out issue. We can even design a new test that shows the side-effect of lack of sync on producer - consumer patterns using KVS as well. But before designing something like this, I would like to generate some discussions on this topic (back to my slides for now.)

**Comment by grondo** [comment] 2015-07-01 22:06
The code that updates the state from starting to running is in wrexecd.c.

Only the wrexecd on `nodeid == 0` updates the state, and it does
`kvs_commit()`
after each state change (see `update_job_state`). However, that is not to
say there is not a bug in there. That being said job state would be expected
to transition from "starting" to "running" very quickly -- and maybe this
falls
within the kvs commit squash window?

Another good argument for a state transition log instead of single state
entry in kvs.

**Comment by garlick** [comment] 2015-07-01 22:09
The kvs_commit is synchronous so those commits would not be squashed.

**Comment by dongahn** [comment] 2015-07-01 22:09
If starting and running got squashed, would JSC get one notification or still two notifications? It seems JSC still got two notifications. (Still can be a bug somewhere in JSC or its test as the code base is young.)

**Comment by trws** [comment] 2015-07-01 22:20
This is caused by a second, though related, race in the JSC.  As I read it, this is the order and race profile.

1. JSC receives a notification on `lwj.next-id` and takes <job-id> from the callback value
2. JSC registers a watch on `lwj.<job-id.state`, this is race number 1, and can be easily tested as @dongahn pointed out.  I have most of a test for this written actually.
3. JSC receives a notification on `lwj.<job-id>.state` and ignores the value
4. JSC *reads* the value from the kvs non-atomically, this is race number 2, and the cause of the "running->running" issue

There are probably at least 2-3 other races in the way this is set up right now, but these are the two causing immediate problems.

**Comment by dongahn** [comment] 2015-07-01 22:21
@garlick @grondo: Oh well. Here is another theory. Looking at the state change handling, JSC actually fetches the new state on the state call-back invocation. This could be again racy as the state could have changed by the time JSC gets to fetch it. I think this can be resolved, if I just use the "val..." Let me do some testing.

**Comment by dongahn** [comment] 2015-07-01 22:28
@trws: Our message crossed. Yes I think you've got it. At least this race is fixable by not ignoring the state value passed to the callback. Sorry for the trouble. 

But then, this would be one of the general problems of using KVS watch: I want the consumer to act on a watch event, but this would probably be unreliable as the producers can change the states in between. I am capturing all these issues in my slides.

But I will work on the patch first.

**Comment by garlick** [comment] 2015-07-01 22:37
Ah, good job guys.

@dongahn on your last comment, one thought is maybe the watch callback should get a `kvsdir_t` representing the root directory (internally including its SHA1), then `kvsdir_get_*()` functions could be used to traverse the namespace as though it were a snapshot of the commit that changed the watched key.  This is the idea alluded to in issue #64.  I'm going to mention #206 here as that is where I'd like to redirect the general discussion on KVS synchronization.

**Comment by dongahn** [comment] 2015-07-01 22:43
@garlick I think this is a great idea. And discussing this at #206 would be great. My gut feeling (as I'm dumping my brain into slides) is that we will probably need both transactional mechanisms like that in KVS and probably also some reasonable sync mechanism outside KVS between producers and consumers using KVS. 

If @trws was planning to have some thoughts on this topic, we should all compare the notes and identify best practices with reasonable scoped engineering work. Perhaps, next meeting?

**Comment by dongahn** [comment] 2015-07-01 22:49
The patch seems straightforward. @garlick: but I would like to try this on your setting first to confirm the fix. What's the best way to do this?

**Comment by garlick** [comment] 2015-07-01 22:53
Can you send me a ref to your personal branch containing the patch?  I can just check it out and run it here for a sanity test if you like.

**Comment by dongahn** [comment] 2015-07-01 23:17
@garlick Please try https://github.com/dongahn/flux-core/tree/jsc-234

The fix was made to jstatctl.c.

And I've also changed the test script to use a distinct file name for expected result file per each subtest for better debugging. 

Let me know.

**Comment by garlick** [comment] 2015-07-02 00:00
I've run the jsc tests 12 times on your branch, all OK.
Reverting the code patch, it fails right away (pretty much always one of tests 1-5 fails in this VM)

**Comment by dongahn** [comment] 2015-07-02 00:16
I need that VM :-)

**Comment by garlick** [comment] 2015-07-02 00:21
It's Ubuntu 14.04 x86_64 running under virtualbox, assigned 1G of ram.  The host is an mac mini circa 2011 with intel i5 (not sure if that plays into it at all),.

**Comment by dongahn** [comment] 2015-07-02 00:23
Because there still is a legitimate race between state watch installation and the first state put event, the sub tests can break. Leaving RACY mark to those tests until we make progress through #206 seems the right way to go.

**Comment by grondo** [comment] 2015-09-23 23:19
@dongahn, what is the current state of things regarding this Issue? Is wreck patched up enough that we can close this one?

**Comment by dongahn** [comment] 2015-09-23 23:20
I believe so. I am not aware of any pending issue. Please close it.

**Closed** 2015-09-23 23:45 UTC
