### ISSUE TITLE
Inconsistent --label-io vs --labelio

### ISSUE THREAD

**Issue by jedbrown** [flux-framework/flux-core#2915] opened 2020-04-25 19:27 UTC
We have `flux exec --labelio` (with abbreviation `-l`), but `flux mini run --label-io` (with no abbreviation). I'd imagine you'd prefer this to be consistent, but don't know which you prefer.

**Comment by dongahn** [comment] 2020-04-28 17:44
Thanks @jedbrown. Making the option set consistent seems like a good idea. Can I ask which project are you using Flux for?

**Comment by jedbrown** [comment] 2020-04-28 21:03
I was just experimenting, and hoping to benchmark submission overhead for possible use parallelizing short-running tests without oversubscription. Is the following supposed to work?
```
$ docker run -it --rm fluxrm/flux-sched bash
flux@9455f8d89702:~$ flux start
flux@9455f8d89702:~$ flux mini run hostname
flux-mini: ERROR: [Errno 22] sign-munge-sign: Failed to access "/var/run/munge/munge.socket.2": No such file or directory
```

**Comment by dongahn** [comment] 2020-04-28 21:14
> I was just experimenting, and hoping to benchmark submission overhead for possible use parallelizing short-running tests without oversubscription. Is the following supposed to work?

Thanks. You should start up munge daemons and we also have a helper script to do this under docker if you plan to make modifications to flux-sched.

```console
[gingerfoot:~/workspace/flux_dev/flux-sched] ahn1% src/test/docker/docker-run-checks.sh -I --
ahn1@c3c90b9f37d6:/usr/src$ sudo /sbin/runuser -u munge /usr/sbin/munged
ahn1@c3c90b9f37d6:/usr/src$ flux start
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ahn1@c3c90b9f37d6:/usr/src$ flux mini run hostname
c3c90b9f37d6
```

> hoping to benchmark submission overhead for possible use parallelizing short-running tests without oversubscription.

Flux's general scheduling approach is called scheduler specialization such that you can specialize your user-level scheduler tailored to the performance characteristics of your workloads. You would control three policy knobs: queuing-backfilling policy, queueing/policy parameters and hierarchical policy. 

For short-running tests, I would specialize it with queue-policy=fcfs queue-params=queue-depth=1 to begin with. And to get extreme throughput, I would use flux-tree to parallelize your scheduling further. 

There are various ways to improve ingest rate etc. I will add some reference here.

**Comment by dongahn** [comment] 2020-04-28 21:15
flux-tree: https://github.com/flux-framework/flux-sched/blob/master/src/cmd/flux-tree

**Comment by dongahn** [comment] 2020-04-28 21:16
Python Asynchronous Bulk Job Submission: https://github.com/flux-framework/flux-workflow-examples/tree/master/async-bulk-job-submit

**Comment by dongahn** [comment] 2020-04-28 21:17
Similar studies done by SNL: https://github.com/flux-framework/flux-sched/issues/573

**Comment by dongahn** [comment] 2020-04-28 21:21
Our 2020 tutorial slides: https://github.com/flux-framework/Tutorials/tree/master/2020-ECP

Sandia National Lab's "Manage Internal Queue w/ Flux for Common Workflows" talk might be of your interest.

**Comment by dongahn** [comment] 2020-04-28 21:23
BTW, I was talking with ANL researches about libensemble workflow to take advantage of Flux. Is your effort related to that at all? Since I see petsc from your repo set.

**Comment by jedbrown** [comment] 2020-04-28 21:35
Thanks for these tips. There are zero results for "munge" on the documentation site: https://flux-framework.readthedocs.io/en/latest/search.html?q=munge&check_keywords=yes&area=default
Would it be possible to do this by default in the container (or a variant of the container)?

Is there a way this can be made faster? It's about 15x slower than Open MPI `mpiexec` and 40x slower than MPICH `mpiexec`.
```
$ time for i in {1..100}; do flux mini run /bin/true; done

real    1m25.804s
user    0m12.668s
sys     0m1.756s
```

I'm not working directly with libEnsemble, but I do work with some of the people. In this case, a typical CI pipeline for PETSc runs about 60 configurations, each of which runs 4k to 8k jobs. Many of those jobs are single-core, but some require several cores. Our current strategies either give up parallelism or result in incidental oversubscription (which severely hurts perf). Most of our tests use MPICH built with (deprecated) `ch3:sock` because it is most tolerant of oversubscription. Many of the jobs run for less than a second, so running it all through `flux mini run` as above would cost many core-hours of compute time per pipeline. In this context, we're running everything on the local node.

**Comment by jedbrown** [comment] 2020-04-28 21:49
I don't understand what is happening here:
```
flux@9cc68e2e6580:~$ export FLUX_QMANAGER_OPTIONS="queue-policy=easy queue-params=queue-depth=1"
flux@9cc68e2e6580:~$ time for i in {1..10}; do flux mini run /bin/true; done

real    0m2.244s
user    0m1.240s
sys     0m0.171s
flux@9cc68e2e6580:~$ time for i in {1..100}; do flux mini run /bin/true; done

real    3m20.115s
user    0m10.919s
sys     0m1.536s
```

still quite a bit slower than MPICH `mpiexec`.

**Comment by dongahn** [comment] 2020-04-28 21:54
How many cores you have on this system? Could you do `flux hwloc info`?

**Comment by jedbrown** [comment] 2020-04-28 22:02
This is just my laptop.
```
flux@9cc68e2e6580:~$ flux hwloc info
1 Machine, 2 Cores, 4 PUs
```
The real CI pipelines run on a variety of machines from older hardware to newer two-socket Xeon and some cloud. But I'm just running `/bin/true` here, which takes about 1 ms to execute.

**Comment by grondo** [comment] 2020-04-28 22:04
>  so running it all through flux mini run as above would cost many core-hours of compute time per pipeline. In this context, we're running everything on the local node.

To clarify probably poor documentation, using `flux mini run` in a loop will run all your jobs serially, since each invocation will block until the job is complete. Is this how you meant to run the workload?

To submit jobs for scheduling, take a look at `flux mini submit`. I fear it still won't be as fast as mpiexec, since Flux will have a bit of overhead in scheduling the jobs and will not oversubscribe.

**Comment by jedbrown** [comment] 2020-04-28 22:27
Right, we typically use `make -j` to run the jobs and evaluate output (various comparisons) to yield TAP or Junit logs, which GitLab can render in the merge request. We want `run` (not `submit`) semantics, but we will have parallel submitters due to `make -j`.

Per my example above, why does running 100 jobs in sequence take over 60x longer than running 10? Shouldn't the cost per job be constant?

If the overhead was, say, 2x more than MPICH `mpiexec`, we'd be sold. It's a tough sell if it's >10x more.

**Comment by dongahn** [comment] 2020-04-28 22:31
@jedbrown and @grondo: I have to believe the current small-scale bottle is due to `flux-mini` interface using python. With that, a bulkier executable (python interpreter) with more DLLs come in, compared to leaner `mpiexec`.

bulksubmit.py from  https://github.com/flux-framework/flux-workflow-examples/tree/master/async-bulk-job-submit can help.


```sh
#!/bin/sh

export FLUX_QMANAGER_OPTIONS="queue-policy=fcfs queue-params=queue-depth=1"
mkdir -p jobs
flux mini run --dry-run -n1 /bin/true > jobs/0.json
for i in `seq 1 100`; do cp jobs/0.json jobs/${i}.json; done
./bulksubmit.py jobs/*.json
```

```console
ahn1@466b72785462:/usr/src$ time ./run_bulk.sh
bulksubmit: Starting...
bulksubmit: submitted 101 jobs in 0.42s. 240.59job/s
bulksubmit: First job finished in about 0.457s

bulksubmit: Ran 101 jobs in 3.3s. 31.0 job/s

real	0m4.149s
user	0m0.200s
sys	0m0.070s
```

```console
ahn1@466b72785462:/usr/src$ time for i in {1..100}; do flux mini run /bin/true; done


real	0m15.391s
user	0m7.160s
sys	0m0.990s
```

**Comment by dongahn** [comment] 2020-04-28 22:33
Forget to mention. bulksubmit.py is slightly broken under the current flux-core master.

```diff
ahn1@466b72785462:/usr/src$ diff bulksubmit.py.orig bulksubmit.py
27c27
<     sys.stdout.write(s)
---
>     #sys.stdout.write(s)
40c40
<         job.submit_async(h, jobspec.read(), flags=flags).then(submit_cb)
---
>         job.submit_async(h, jobspec.read(), waitable=True).then(submit_cb)
```

**Comment by grondo** [comment] 2020-04-28 22:34
> Per my example above, why does running 100 jobs in sequence take over 60x longer than running 10? Shouldn't the cost per job be constant?

Good question, the cost per job should be constant, especially when running serially. 

FWIW, I'm not able to reproduce the scaling problem on my system though. (However, this is using the simple scheduler from core, not graph-based scheduler of flux-sched)

```
grondo@asp:~/git/flux-core.git$ time for i in {1..100}; do flux mini run /bin/true; done

real	0m24.726s
user	0m12.177s
sys	0m2.166s

```

**Comment by dongahn** [comment] 2020-04-28 22:35
BTW, from @jedbrown's test with

```
flux@9cc68e2e6580:~$ export FLUX_QMANAGER_OPTIONS="queue-policy=fcfs queue-params=queue-depth=1"
flux@9cc68e2e6580:~$ time for i in {1..10}; do flux mini run /bin/true; done

real    0m2.151s
user    0m1.093s
sys     0m0.170s
flux@9cc68e2e6580:~$ time for i in {1..100}; do flux mini run /bin/true; done

real    2m24.141s
user    0m12.216s
sys     0m1.619s
```

I don't understand why the `real` time is much much higher than docker on my laptop. 

```
ahn1@466b72785462:/usr/src$ flux hwloc info
1 Machine, 4 Cores, 4 PUs
```

**Comment by dongahn** [comment] 2020-04-28 22:40
My posting was crossed with @grondo's. 

It could be with only 2 cores given to our scheduler, more blocking could occur -- not clear.  

@jedbrown: are those two cores dedicated to docker or somehow being shared with other activities going on in your desktop. 

Probably would be good to do a more control experiment on a dedicated system. 

Bulk submit is one way to optimize this. If a larger scale is involved, I can see why deepening flux scheduling levels can parallelize the scheduling. But at is, at a small scale, it doesn't look like the bottleneck lies in the scheduling but somewhere else.

**Comment by grondo** [comment] 2020-04-28 22:41
> Right, we typically use make -j to run the jobs and evaluate output (various comparisons) to yield TAP or Junit logs, which GitLab can render in the merge request. We want run (not submit) semantics, but we will have parallel submitters due to make -j.

Thanks for the clarification! What features are you hoping to leverage from Flux since you're already using `make -j` to manage parallelism? (If only MPI job launch, I'm not certain you'll see a large benefit moving to Flux, unless you potentially want to leverage running under multiple different resource manager environments, in which case Flux can act as a portability layer for your suite)

**Comment by grondo** [comment] 2020-04-28 22:42
>  I can see why deepening flux scheduling levels can parallelize the scheduling. But at is, at a small scale, it doesn't look like the bottleneck lies in the scheduling but somewhere else.

@dongahn, there's no scheduling being done by Flux in these examples, we're just running `flux mini run` serially...

**Comment by dongahn** [comment] 2020-04-28 22:47
> @dongahn, there's no scheduling being done by Flux in these examples, we're just running flux mini run serially...

Ah.... flux-mini-run request will come to the scheduler.  It is just that each will be scheduled/executed/release on the first core.

**Comment by jedbrown** [comment] 2020-04-28 22:50
Could there be a daemon so that jobs could be submitted via bash or C and still have `run` semantics (`stdout`, `stderr`, and exit codes returned synchronously)?

The machine was basically idle and I reproduced the effect three times.

Suppose I have 16 cores to work with and run `make -j8`. If most of the jobs are serial, half my cores are idle, but sometimes a singlemake  job does `mpiexec -n 12 ./test` and suddenly we're oversubscribed and see 100x slow-down. We can use `make -j8 -l16` to prevent new jobs from starting when the system load is high/oversubscribed, but it's far from perfect.

**Comment by grondo** [comment] 2020-04-28 23:11
> Could there be a daemon so that jobs could be submitted via bash or C and still have run semantics (stdout, stderr, and exit codes returned synchronously)?

Yes, `stdout/err` and exit status are kept for all jobs in the Flux KVS, even those submitted instead of run in the foreground. You can "attach" to previously completed (and/or running) jobs with `flux job attach ID` at any time.

> Suppose I have 16 cores to work with and run make -j8. If most of the jobs are serial, half my cores are idle, but sometimes a singlemake job does mpiexec -n 12 ./test and suddenly we're oversubscribed and see 100x slow-down. 

Yeah, this is a nice use case for using a scheduler. With Flux, I think you could use `make -j 16` in this case. When a job came along that needs 12 cores, it would block until 12 cores are available, and while it is running, other single core jobs will block.

Since `make` is parallelizing the workload for you, I wonder if the overhead of `flux mini run` will actually be a huge problem.  It would be interesting to do a benchmark and see!

**Comment by dongahn** [comment] 2020-04-28 23:12
> Suppose I have 16 cores to work with and run make -j8. If most of the jobs are serial, half my cores are idle, but sometimes a singlemake job does mpiexec -n 12 ./test and suddenly we're oversubscribed and see 100x slow-down. We can use make -j8 -l16 to prevent new jobs from starting when the system load is high/oversubscribed, but it's far from perfect.

I get it. In a sense parallel make works as a scheduler-like logic in your case.

A silly thought: what would happen if you increase the -j factor high under Flux? Like -j 48 for a 16 core node? Would that allow more flux-mini run jobs are "submitted" to the scheduler and can increase parallelism? Since you can't really do this w/o a first class scheduler (which would be the case with `mpiexec`), this may allow for overlapping the overheads of `flux mini run`?

**Comment by dongahn** [comment] 2020-04-28 23:14
> Since make is parallelizing the workload for you, I wonder if the overhead of flux mini run will actually be a huge problem. It would be interesting to do a benchmark and see!

I agree. But it would be a very interesting test. Are we gaining performance by increasing parallelism or losing performance because of the flux-mini or python overhead. Depending on what we find, a solution should be different.

**Comment by dongahn** [comment] 2020-04-28 23:33
One last thought:

I wonder if combing @jedbrown's idea of

> Could there be a daemon so that jobs could be submitted via bash or C and still have run semantics (stdout, stderr, and exit codes returned synchronously)?

and increasing make -j factor may produce a best result.

A lean C program can be developed out of Flux C bindings, which create a jobspec on the corresponding make target, submits it and quietly waits for the completion of work. Then, one increase -j factor as much as practical to maximize the job injection rate required for such a "micro-tasking" regime. 

Maybe this can be a state of the art technique for HPC CI. Given the overall job count is 280K to 480K, I have to believe parallelism should ultimately win -- not a single launch overhead.

**Comment by garlick** [comment] 2020-04-29 01:07
That's kind of a fun thing to play with.  Here's a Makefile that illustrates my interpretation of the problem at least.  Run `make create_inputs`, then `time make -j N`, adjusting N to vary the number of parallel runs, with `make clean` in between runs...
```makefile
COUNT = 100
INS = $(wildcard *.in)
OUTS = $(INS:.in=.out)

all: $(OUTS)

%.out: %.in
        flux mini run -n1 cp $< $@

create_inputs:
        for i in `seq 1 $(COUNT)`; do touch $$i.in; done

clean:
        rm -f *.out

clobber: clean
        rm -f *.in
```
Setting `-j N` a little higher than the number of cores should mask the  python startup overhead (could plot j vs wall time and see where the curve levels out).

**Comment by grondo** [comment] 2020-04-29 02:07
Nice! To fully simulate the use case, we could add some fake computational load instead of `cp`, and add in a configurable number of targets that require `flux mini run -n NPROCS` where NPROCS > 1.

As an aside, here's a dumb little patch for GNU make 4.1 that wraps all child jobs in `flux mini run -n1 -N1` (based off a [similar patch](https://github.com/SchedMD/slurm/blob/master/contribs/make-3.81.slurm.patch) from Slurm).

```diff
diff --git a/job.c b/job.c
index 2989249..2af4b6c 100644
--- a/job.c
+++ b/job.c
@@ -2324,6 +2324,24 @@ void
 child_execute_job (int stdin_fd, int stdout_fd, int stderr_fd,
                    char **argv, char **envp)
 {
+  if (getenv ("FLUX_URI")) {
+    int i = 0;
+    int argc;
+    char **av;
+    while (argv[i])
+      i++;
+    argc = i + 5;
+    av = alloca (argc * sizeof (*av));
+    av[0] = "flux";
+    av[1] = "mini";
+    av[2] = "run";
+    av[3] = "-N1";
+    av[4] = "-n1";
+    for (i = 5; i < argc; i++)
+      av[i] = argv[i-5];
+    av[i] = NULL;
+    argv = av;
+  }
   /* For any redirected FD, dup2() it to the standard FD then close it.  */
   if (stdin_fd != FD_STDIN)
     {
```

**Comment by garlick** [comment] 2020-04-29 02:55
Oh I can't wait to play with that!

**Comment by jedbrown** [comment] 2020-04-29 03:40
It is more than just latency. The 0.3 seconds per launch (for Python) is actually quite a bit of work and file system access, and would amount to core-hours over a complete pipeline run. I'd prefer the C or bash submitter.

Our typical jobs have the structure
```bash
set -e
mpiexec -n 4 ./app -options > result.out 2> result.err
if [[ -s result.err ]]; then
    report failure with stderr
fi
if diff -q reference.out result.out; then
    report failure with diff
fi
```
One nice thing about `make -j` is that it familiar to users and pretty good about collating output from jobs that may or may not fail, and interrupting cleanly without zombie processes or corrupt files.

My preference would be to have a substitute that behaves basically like `mpiexec` while avoiding oversubscription.

We also use some of our CI hosts for one-off development and debugging (single and multi-user). These jobs are usually just a few seconds so we haven't bothered configuring a resource manager, but if Flux is simple to use in that environment, it would save some conflicts/CI timeouts when someone kick off `mpiexec -n 64 ./not-so-short` without thinking about the consequences.

**Comment by dongahn** [comment] 2020-04-29 04:17
> It is more than just latency. The 0.3 seconds per launch (for Python) is actually quite a bit of work and file system access, and would amount to core-hours over a complete pipeline run. I'd prefer the C or bash submitter.

I agree. 

Please see https://github.com/flux-framework/flux-core/issues/2915#issuecomment-620908246. 

My proposal would be to write a braindead simple custom run program using C on top of our C bindings. I think this should be easy enough for someone to take on. 

@grondo and @garlick: also for each job, we also use a python validator program correct? I wonder in a micro tasking region like this, one can specialize the job ingestion behavior and disable that as well...

**Comment by jedbrown** [comment] 2020-04-29 04:38
@dongahn This would be great and I think you'd get a lot of uptake from other projects too. I think if you created such a thing, the C program would probably learn a lot of `mpiexec` features (like affinity) over time (hopefully that would just mean passing them through to Flux), but the most basic support for `-n` would do the trick for PETSc's CI.

**Comment by dongahn** [comment] 2020-04-29 04:54
> I think if you created such a thing, the C program would probably learn a lot of mpiexec features (like affinity) over time (hopefully that would just mean passing them through to Flux), but the most basic support for -n would do the trick for PETSc's CI.

The C program doesn't need to have any of these features (affinity etc) implemented at that level at all because these are already implemented in our execution service. I guess that's probably what you mean by "passing them through Flux." Currently, the overheads is in the front end (flux mini interface) due to using python and Python API. To begin with, a lightweight custom C run program can take in only `-n` and does an RPC to submit and wait for the job to finished up is all that's required. (Plus, collecting stdout/stderr at the end).

@grondo or @SteVwonder should know better, but my expectation would be on the order of a few hundred of lines of code...

One thing I'm not sure is whether such a program should make into the flux-core proper or rather considered to be a "production" software.

It seems it makes sense to create a prototype C program on the side and tested/used by some projects like PETSC CI. If this turns out to be generally useful, we can consider bringing a production version of this into the mainline. 

We had an idea of naming mircrorun when we named flux mini run like flux microrun. Seems like Petsc CI use case is demanding `microrun` from its micro tasking...


Just a thought.

**Comment by garlick** [comment] 2020-04-29 14:11
It's actually not a tiny amount of C code, but much of it's already done in the plumbing commands `flux job submit` and `flux job attach`.  If we added one more to generate jobspec, then FWIW we'd have all the pieces that could be combined in a shell script like
```
#!/bin/sh
flux job attach $(flux job spec $* | flux job submit)
```

**Comment by garlick** [comment] 2020-04-29 14:34
I prototyped that real quick but the performance is not a huge win over mini run, given the loss of functionality:
```
$ time flux job attach $(flux job spec /bin/true| flux job submit)

real	0m0.132s
user	0m0.075s
sys	0m0.026s

$ time flux mini run /bin/true

real	0m0.245s
user	0m0.109s
sys	0m0.036s
```

**Comment by dongahn** [comment] 2020-04-29 16:33
@garlick: 

A factor of 2 is still significant and a step into the right direction! I wonder if running this 100 times would show if this is a reproducible gain or not, though. Also micro-tasking may benefit from a bit more execution specialization. As I mentioned at https://github.com/flux-framework/flux-core/issues/2915#issuecomment-620980071, are we still using a python jobspec validator for each job? Is there a way to disable that for testing?

@jedbrown: 

Given @garlick's prototype above and other execution service specialization may be possible, would you be willing to run some more isolated benchmarking on your CI workload? So far, the evidence is ad hoc and it feels like we can all benefit from a bit more exploration. Like using 16 core machine; realistic Makefile (like one of 60 configurations) and vary things like -j factor etc to control parallelism and job injection rate? 

Note that Flux scheduling and execution services must meet a wide range of HPC workflow execution patterns, ranging from the traditional large long running pattern to more emerging execution patterns, and micro tasking workflow is in the far end of this: "extreme" throughput regime (many 1 sec or sub-second tasks) , which we don't have a lot of experience yet.

If something like this is run on large number of nodes, I would tap into our scheduler parallelism using a command like flux-tree. But yours is in the desktop domain so that won't work well. 

In general, our path for enabling a wide range of execution patterns is through service specialization. I already have a bunch of scheduling specialization in flux-sched and have more ideas if needed. For example,

https://github.com/flux-framework/flux-sched/issues/574
https://github.com/flux-framework/flux-sched/issues/575

I hope that execution service could also meet a pattern like yours through specialization that would require only minor effort. But we can't get there in one step and by ourselves alone.

One question. Is your project an ECP project?

**Comment by garlick** [comment] 2020-04-29 16:41
> are we still using a python jobspec validator for each job? Is there a way to disable that for testing?

Not an easy way,  but it goes pretty fast once it gets going.  There is a work crew, and the workers continue to run as long as there are jobs to process, so python startup cost is not per job.  I'm measuring about 500 jobs/sec ingest rate on a single (slow) node, and the validation is included in that number.

**Comment by grondo** [comment] 2020-04-29 16:52
Yeah, job-ingest isn't a bottleneck at all (except you pay a hefty startup cost when the first validator worker starts). You could replace the python validator will a simple shell script:
```sh
#!/bin/sh
while read line; do
    printf '{"errnum":0}\n'
done
```
Load it with something like:

```console
$  flux module reload -f job-ingest validator=$(pwd)/null-validator.sh
```

**Comment by dongahn** [comment] 2020-04-29 16:55
@grondo: thanks.

> Yeah, job-ingest isn't a bottleneck at all (except you pay a hefty startup cost when the first validator worker starts).

So this could bias the benchmarking result if only a small number of jobs are used? The startup cost isn't fully amortized.

**Comment by grondo** [comment] 2020-04-29 16:59
> My preference would be to have a substitute that behaves basically like mpiexec while avoiding oversubscription.

I hesitate to mention it, since it is not really Flux related, but have you ever looked into tapping into GNU make's jobserver?

https://www.gnu.org/software/make/manual/html_node/Job-Slots.html

Your mpiexec wrapper script could grab the extra slots it needs from the pipe and return them when finished. (Of course, this would not help on shared systems, nor would it help a workflow scale across multiple nodes)

**Comment by grondo** [comment] 2020-04-29 17:01
> So this could bias the benchmarking result if only a small number of jobs are used? The startup cost isn't fully amortized.

Yes. When I benchmark I tend to run a single job to get at least one validator started. The dummy shell script is probably a better idea for benchmarking -- I wonder if we should include one in the distribution.

**Comment by jedbrown** [comment] 2020-04-29 17:10
I almost started implementing using the jobserver before realizing that it would deadlock if you wait to get n slots before `mpiexec -n $n ./job`. It really isn't meant for this purpose.

**Comment by dongahn** [comment] 2020-04-29 17:18
A theoretical analysis:

Say, 
- runtime overhead of `mpiexec` is `M` 
- runtime overhead of `flux run` is `F` 
- average runtime of microtask is `J`
- relative parallelism gain going with the first-class scheduler with flux is `P`

For example, with this definition, 
- Under Flux:
If flux allows the CI to run tasks with full 16 way parallelism, the makespan of the one wave of executing 16 tasks would be: `F + J`
- Under mpiexec:
If you have to reduce the parallelism by a factor of 2, the makespan of doing the same amount of work would be `2M + 2J`

In general, under mpiexec `PM + PJ`; under Flux `F+J`. 

So we want to make `PM + PJ > F + J` condition. 
at P=2, `2M + J > F`
at P=4 `4M + 3J > F`

In general `J` would be much greater than `M` or `F`. So maybe there is a good chance that Flux scheduling approach will win?

**Comment by jedbrown** [comment] 2020-04-29 18:28
Example pipeline: https://gitlab.com/petsc/petsc/pipelines/140789590
* Job on KNL: https://gitlab.com/petsc/petsc/-/jobs/530568673 (50 minutes for build and test)
```
# success 6720/8295 tests (81.0%)
# failed 0/8295 tests (0.0%)
# todo 212/8295 tests (2.6%)
# skip 1363/8295 tests (16.4%)
#
# Wall clock time for tests: 1474 sec
# Approximate CPU time (not incl. build time): 5485.78 sec
```
* Job on 8-core FreeBSD: https://gitlab.com/petsc/petsc/-/jobs/530568659 (33 minutes)
```
# success 8070/9079 tests (88.9%)
# failed 0/9079 tests (0.0%)
# todo 212/9079 tests (2.3%)
# skip 797/9079 tests (8.8%)
#
# Wall clock time for tests: 440 sec
# Approximate CPU time (not incl. build time): 1050.1299999999812 sec
```

If we take this bottom case and a typical MPICH `mpiexec` of `M = 0.01` seconds. Across 8000 jobs, this is about 80 seconds spent in the launcher.

If we naively took CPU time and divided by 8 cores, we'd hope to run in, say 150 seconds. It costs 440 due to imperfect parallelism (and perhaps other OS overhead).

But we would double our CPU time if the launcher were to take `F= 0.25` seconds, we'd be adding 2000 CPU seconds of overhead. Even if that parallelizes perfectly across the 8 cores, we'd still be adding 250 wall clock seconds and thus wash away any benefits we could gain from better parallelism.

Note that the cost distribution J is highly skewed, with lots of very short jobs and a long tail of more expensive jobs.

**Comment by dongahn** [comment] 2020-04-29 19:38
Great example! 

Yes with `J` being so small like this, `F` needs to be substantially smaller. Is the relative performance difference between `M` and `F` is 25x as is? 

As suggested, its seems more execution service specialization is needed.

- Use @garlick's dead simple launcher (this may already provide 2x overhead reduction though more benchmarking is needed)
- Use dead simple validator
- Don't use munge authentication (which isn't really required anyway for this single user flux use)

More controlled benchmark can be run with these changes so far?

**Comment by jedbrown** [comment] 2020-04-29 19:53
We can set up a benchmark environment (including a subset of the tests that would run in whatever time is convenient). The next week is going to be extremely busy for me so I won't be able to do more than run.

**Closed** 2020-07-24 23:48 UTC
Labels: no-brain-required
