### ISSUE TITLE
Super-linear memory expansion launching jobs

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#462] opened 2015-10-28 17:42 UTC
Running a test for scalability in terms of number of jobs over time, I ran into super-linear memory consumption on broker 0.  I do not have data for the other brokers, but the broker 0 memory consumption proceeds as below, expressed as a percentage of total node memory for a Hype node, which I think is 32GB.  This test was run on four nodes, one broker per node, launching 4-rank MPI_hello jobs in groups of 16.  It was run with this command, (note the lack of --pty, that causes other oddness, also the extra quotes are necessary, the broker eats a level of quotes for some reason, the parallel xargs is just there so this takes 10 minutes instead of an hour due to loading each one sequentially):

```bash
$ srun -N 4 -n 4 -ppdebug flux broker sh -c "'seq 1 6000 | xargs -n 1 -P 16 flux wreckrun -n 4 ./mpi_hello'"
```

| jobs complete | percent memory |
|--------------------|------------------------|
|1000| 5%|
|2000| 20%|
|3000| 42%|
|4000| 75%|
|4528| OOM|

I'm working on getting a heap profile for this, but it's proving to be surprisingly difficult to do so in a multi-node configuration like this.  I'll report back if I succeed in getting more useful data.

**Comment by grondo** [comment] 2015-10-28 17:50
@trws, thanks for collecting this data!

I believe you mentioned that if you don't run MPI job as the target, the limit is many more jobs? Do you know how many more?

**Comment by trws** [comment] 2015-10-28 17:51
@grondo: I don't, I had to cancel the test because I didn't think to put it in a tmux before I started it.  I'll try it now and see what happens.

**Comment by trws** [comment] 2015-10-29 00:16
As it turns out, this is not unique to PMI.  I'm not sure what happened yesterday that I thought it was, but re-working the test to use non-MPI jobs had the same effect just now on cab.  It did give me one new piece of information though, which is that the memory use only baloons on broker 0, the other three stay at a steady 1.3-1.5% of node memory all the way up to 0 running out, which on cab happens at about 89%.

**Comment by grondo** [comment] 2015-10-29 04:06
Maybe there is something *really dumb* wreckrun is doing with the kvs?

One bit of wasted space in the kvs for each job is the environment, which is currently duplicated for every lwj entry. There is already a workaround for this in place, especially if every job runs with the same environment. Let me know if we need to exercise that.

However, even with all that environment duplication, though, a back of the envelope guess at kvs space used per job is roughly 8KB -- so with 4000 jobs and 8KB per job we should only be using about 32M for the kvs for `lwj.*`. That is clearly much much lower that what you are seeing.

I wonder what happens if you run `flux kvs dropcache` on rank 0 after every 1000 jobs. I don't know enough about kvs implementation to know if this does anything on kvs master, probably should defer to @garlick here. (actually I'm even just guessing that we're dealing with kvs growth here)

**Comment by trws** [comment] 2015-10-29 17:00
I'm suspecting the KVS as well actually, just because it's only broker 0, and because the doubling realloc behavior under the hash tables it stores data in might do this to us even if wreck and the KVS dedup are doing their jobs perfectly.  For some reason the heap profiling from tcmalloc is causing the broker to crash now, so I'm trying some alternatives.  Hopefully we'll have hard data later today.

**Comment by garlick** [comment] 2015-10-29 21:04
Dropcache is a no-op on the master since the cache isn't really a cache there, it's the master copy.

It might be interesting to look at
```
flux comms-stats --parse "obj size total (MiB)" kvs
```

on rank 0 to see what the KVS thinks it's using (based on iterating through the object store and adding up the serialized json size of each object...won't be spot on, but I would expect this to be at least proportional to the actual usage)

**Comment by trws** [comment] 2015-10-29 23:08
Ok, we have data.  I managed to link jemalloc into the broker and write a set of wrappers to get just the broker to actually dump heap profiling.  That setup managed to get meaningful output (liking jemalloc by the way, pretty nice).  Anyway, the data generated is rather like what gperftools produces.  The attached PDF sums it up pretty well. (broker 0 only, all threads, total in-use heap at approximately 2000 jobs run, no PMI in use)

[broker-0-2000jobs.pdf](https://github.com/flux-framework/flux-core/files/23848/broker-0-2000jobs.pdf)

The default cutoffs, about 0.005% of mem consumption for nodes and 0.001% for edges, removes everything but allocations by the KVS.  It's roughly half json-c linkhash objects for directories and half json-c string objects.

**Comment by trws** [comment] 2015-10-29 23:18
Good idea @garlick, I'll add that command to my test runner and post what comes out.

**Comment by dongahn** [comment] 2015-10-29 23:43
Just a side note: This memory-profiling display scheme is pretty cool. Seems our LC users can also take advantage of.

**Comment by trws** [comment] 2015-10-29 23:50
@garlick The command you sent grows steadily to about 2030MB, then it goes negative for some reason, and ends at -1908MB for rank 0... Not sure what's up with that, but clearly something odd is going on for 1500+ jobs.

@dongahn: Yeah, it's definitely my preferred way to look at heap data.  Usually I reach for tcmalloc for this, but come to find out jemalloc's version is a little more stable for seriously complicated threaded systems.  I suppose I shouldn't be surprised, given that jemalloc is designed for that in the first place, but either way at least it works, and you get a faster allocator out of the bargain too.

**Comment by SteVwonder** [comment] 2015-10-30 00:26
Any special modifications you had to make to get jemalloc working with Flux?  For tcmalloc, I just set LIBS when I configured flux-core.  Is it similar for jemalloc?

**Comment by trws** [comment] 2015-10-30 00:28
I added it to libs for specifically the broker, then created a wrapper script that turned on profiling for just the one assigned rank 0.  Neither of these are necessarily required, but loading it normally either overloaded the filesystem or caused hangs (tcmalloc always hung trying to manage profiling this test).

**Comment by garlick** [comment] 2015-10-30 03:49
NIce @trws.  I'll take a closer look tomorrow but I wouldn't be too surprised if the KVS object store were half object and half strings representing the serialization of those objects (stored within the objects).

I'll look into why that count is going wrong as well.

**Comment by trws** [comment] 2016-02-08 23:57
Using sqlite this seems to be addressed.  I'm going to get some numbers on the file sizes, but it looks like this will be closable shortly. Nice work @garlick!

**Comment by garlick** [comment] 2016-03-29 18:43
I'm going to close this as I believe we have a handle on the memory now, and are on to other issues.

@trws if you happen to have runes handy for jemalloc heap profiling, I'd appreciate a hint in #604 - I'm having some difficulty getting that going at the moment.

**Closed by garlick** 2016-03-29 18:43 UTC

**Comment by trws** [comment] 2016-03-29 19:41
That sounds reasonable.

What kind of output would you like? I have a tree somewhere with a 
little wrapper to help get the heap allocation call traces like I posted 
before, but is that what you want or something more performance-centric? 
I think it can do both, I just haven't done much with the performance 
interface in jemalloc, usually use tcmalloc's for that (though that 
crashes flux on LC machines for some reason completely unrelated to 
flux...)

**Comment by garlick** [comment] 2016-03-29 20:15
Hmm, well, I was hoping to zero in on some heap hotspot that might explain the job launch slowdown of #604, but having generated some call graphs like you posted but with tcmalloc (on ubuntu), I'm not really getting anywhere.  I had added calls to `HeapProfilerDump()` in the heartbeat event handler and thought maybe looking at two dumps in a row while jobs were running might show me something.  Not really though.

I'm pretty naive with these tools.  Open to suggestions!

**Comment by trws** [comment] 2016-03-29 20:29
Based on some of the profiling I did before, it seems the kvs operations 
get progressively slower based on the information from its stat 
messages.  I keep thinking it would be really useful to put a timer in 
the broker's message handling loop to time each message, then 
post-process the event times.  I had meant to put up an issue on this 
with some notes on tracing libraries we could use to get an actual timed 
trace we could look at with some of the MPI or threading profiling 
tools.  Our own caliper might be a good way to do it, but it doesn't tie 
into any good trace viewers yet, let me see if hpctoolkit or tau have 
made that reasonable yet and I'll put something up.

@dongahn: do you have any ideas for something that would be quick but 
useful?

**Comment by dongahn** [comment] 2016-03-29 20:45
@garlick: I think that comparing profile data across two different intervals is a good idea... But I am not sure if one heartbeat interval is long enough. Can we try this at coarser granularity like after 10 or higher maybe. 

Also, while accumulation of perf/memory data tells one story, reseting the data between two different intervals might tell another story.

**Comment by grondo** [comment] 2016-03-29 21:48
Are you sure the heap is the cause the slowdown? Would starting with a statistical profiler like perf or oprofile help narrow down potential hot spots with less work that direct tracing? E.g. compare perf output at start of a session and after 4000 jobs? 

I remember that I found [FlameGraphs](https://github.com/brendangregg/FlameGraph) a useful visualization of the trace data before. Using recent CPUs it appears you might be able to get much more reliable profiling using [Processor Trace](http://halobates.de/blog/p/329)

Of course, apologies if I misunderstand what you're trying to analyze in this issue! You can ignore my comments if needed!

**Comment by dongahn** [comment] 2016-03-29 21:56
I agree. "perf" with in particular with call-graph could be useful across different time intervals. One thing I had trouble in the past was, though, that it requires the elevated privilege. But in this case, you folks may already have that privilege on the test platform...

**Comment by trws** [comment] 2016-03-29 22:03
I have had little luck with perf/oprofile so far, largely because flux is an event loop, so the vast majority of time is spent waiting for something to happen, and the actual work gets buried in the noise.  If we add in some points to make it easier to filter that, or to determine which parts are actually important, that might help, but by that point we can get real traces.  That's not to say it isn't worth a try, but I was unable to get useful data out of that approach at the broker level.

By the way, it doesn't actually take elevated privileges on some platforms.  You can use it at will on cab as I recall, but not on hype... odd that...

**Comment by trws** [comment] 2016-03-29 22:11
FWIW, this is the kind of thing I was referring to: https://www.cs.uoregon.edu/research/tau/docs/tauapi/

I have some emails out to see if there's something easier, but if we put in some phase calls, and maybe build RECV and SEND message tracers into the messaging layer we can get traces like we get from MPI applications for all of flux.  In the meantime, since this is not a simple instant solution, intel vtune does a pretty good job with flux, and has the filtering to make it workable, but it's still tricky to filter down to what's really important.

**Comment by grondo** [comment] 2016-03-29 22:25
@trws, you make a good point. You have to have some context to know *what* you're waiting for, if you're spending more time waiting as the cause of the slowdown.

I kind of hoped that comparing two perf runs using a FlameGraph would point to some place where more work is being done (assuming that you're waiting longer because more work must be done somewhere else), but I agree something like you propose sounds like a much better approach for analysis.

It would be cool if eventually "latency traces" could be enabled saved in a time series DB for even real-time analysis (perhaps this could be part of the monitoring system), kind of like I think redis does

**Comment by trws** [comment] 2016-03-29 22:39
@grondo, it's certianly worth a try to do a comparison like that, it's something I haven't tried and it may really help.

As to doing latency traces, that's something we could definitely do.  We could add in some caliper calls, and maybe even have a collection engine for it that would send it into the KVS or just go straight to the HBase-based system we have for collection now.  I don't love TAU (honestly, it's a pain to use in many cases)  but to get useful traces from distributed messaging systems, it and hpctoolkit are pretty much it as far as I know. This is the kind of thing we would end up with if we took the time to put in the hooks for it, and collected everything:

![tau-vampir02](https://cloud.githubusercontent.com/assets/660149/14126191/2aaf01ec-f5c4-11e5-9ce1-e7dc038ca1fb.gif)

The difference would be that it would probably be labeled by message topics for many of these instead of, or in addition to, function names.

**Comment by garlick** [comment] 2016-03-30 00:06
Thanks guys.  Learning new things today!  But mostly staring squinty eyed at tcmalloc call graphs and prof data, and no enlightenment yet.

**Comment by dongahn** [comment] 2016-03-30 00:14
BTW, this could also be related to @tpatki's current task of adding instrumentation to do critical path analysis for the scheduler performance. If we can just express the performance of scheduling and running *n* (100 or 1000)  jobs as a function of dominant factors, we may be able to pinpoint hotspots better. 

If we add instrumentation only to the scheduler, the flux-core performance will only show up as "black box" components. But the instrumentation doesn't have to stop there at flux-sched... 

This of course isn't most general, though, because someone has to instrument flux-core at some level.
