### ISSUE TITLE
need ability to view limits

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4659] opened 2022-10-06 19:17 UTC
Problem: the policy limits configured in an instance (global and per-queue) are not accessible to users, making it hard to determine what they are without submitting jobs that violate the limits.

It would be fairly easy from an implementation perspective to make the `flux queue status` command capable of dumping this.  I'm not sure that's the best choice from a UX perspective though.

**Comment by grondo** [comment] 2022-10-06 20:02
We could make a `flux queue list` using similar interfaces built on `flux.util.OutputFormat` like `flux jobs` and `flux resource list`. This would present a consistent and familiar API for users. We'd need to make a `Queue` class and have name/limits/defaults/etc available as attributes of each queue object. We might want to wait to implement this until we're certain we don't have to redo anything about the current queues implementation.

**Comment by grondo** [comment] 2022-12-10 16:50
Duplicate of #4673, which has more comments, so closing this one.

**Closed by grondo** 2022-12-10 16:50 UTC
