### ISSUE TITLE
testsuite: valgrind test sometimes fails with e.g. flux-start: 0 (pid 767) Killed

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2195] opened 2019-06-15 14:17 UTC
In #2194, @chu11 noted:

> Hmm, one builder hit a valgrind issue, no stack available. Was also hit in #2137 & #2178 (keying off the byte count of 27,632).
> ...
> ```
> ==768== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> flux-start: 0 (pid 767) Killed
> not ok 1 - valgrind reports no new errors on 2 broker run
> ```

and @grondo pointed out:
> Hm, in the valgrind test we adjust the broker's "shutdown-grace" period, but not flux-start's --killer-timeout which defaults to 2s. I wonder if the rank 0 broker is slow to exit and hits this timeout? I didn't look in any detail but we should probably add --killer-timeout (of at least VALGRIND_SHUTDOWN_GRACE?) to the flux-start command line in the test.

**Comment by chu11** [comment] 2019-06-18 17:36
Hacked this up:

```
diff --git a/t/t5000-valgrind.t b/t/t5000-valgrind.t
index 815a28c..702e966 100755
--- a/t/t5000-valgrind.t
+++ b/t/t5000-valgrind.t
@@ -38,7 +38,8 @@ VALGRIND_SHUTDOWN_GRACE=${VALGRIND_SHUTDOWN_GRACE:-16}
 test_expect_success \
   "valgrind reports no new errors on $VALGRIND_NBROKERS broker run" '
        run_timeout 120 \
-       flux start -s ${VALGRIND_NBROKERS} --wrap=libtool,e,${VALGRIND} \
+       flux start -s ${VALGRIND_NBROKERS} --killer-timeout=${VALGRIND_SHUTDOWN_GRACE} \
+                --wrap=libtool,e,${VALGRIND} \
                --wrap=--tool=memcheck \
                --wrap=--leak-check=full \
                --wrap=--gen-suppressions=all \
```

running a branch both with and without this patch in travis, trying to see if I can get the issue to reproduce on one and not the other.  So far no luck after maybe 5-6 builds on both.  Hopefully can hit at some point.

**Comment by chu11** [comment] 2019-06-18 22:21
I hit a valgrind fail with the patch :-( ... the byte size is different though, so it's possible this is a different valgrind issue.

```
==1913== 
==1913== HEAP SUMMARY:
==1913==     in use at exit: 23,615 bytes in 57 blocks
==1913==   total heap usage: 28,572 allocs, 28,515 frees, 19,726,541 bytes allocated
==1913== 
==1913== LEAK SUMMARY:
==1913==    definitely lost: 0 bytes in 0 blocks
==1913==    indirectly lost: 0 bytes in 0 blocks
==1913==      possibly lost: 0 bytes in 0 blocks
==1913==    still reachable: 23,615 bytes in 57 blocks
==1913==         suppressed: 0 bytes in 0 blocks
==1913== Reachable blocks (those to which a pointer was found) are not shown.
==1913== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1913== 
==1913== For counts of detected and suppressed errors, rerun with: -v
==1913== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
flux-start: 0 (pid 1911) Killed
not ok 1 - valgrind reports no new errors on 2 broker run
```

**Comment by grondo** [comment] 2019-06-18 23:28
Hm, can we increase verbosity to see what is killing rank 0 broker?

**Comment by chu11** [comment] 2019-06-18 23:42
good idea, I added

```
diff --git a/t/t5000-valgrind.t b/t/t5000-valgrind.t
index 815a28c..b45ca9c 100755
--- a/t/t5000-valgrind.t
+++ b/t/t5000-valgrind.t
@@ -48,7 +48,7 @@ test_expect_success \
                --wrap=--leak-resolution=med \
                --wrap=--error-exitcode=1 \
                --wrap=--suppressions=$VALGRIND_SUPPRESSIONS \
-               -o,--shutdown-grace=${VALGRIND_SHUTDOWN_GRACE} \
+               -o,--shutdown-grace=${VALGRIND_SHUTDOWN_GRACE},--setattr=log-level=7,-v \
                 ${VALGRIND_WORKLOAD}
 '
 test_done
```

lets see if something interesting pops out

**Comment by chu11** [comment] 2019-06-19 17:56
Hit the exact issue after 4-5 runs but nothing special

```
+ flux job drain
flux-broker: exited event loop
flux-broker: cleaning up
flux-broker: unloading connector-local
flux-broker: finalizing modules
==32103== 
==32103== HEAP SUMMARY:
==32103==     in use at exit: 27,632 bytes in 70 blocks
==32103==   total heap usage: 25,683 allocs, 25,613 frees, 17,209,498 bytes allocated
==32103== 
==32103== LEAK SUMMARY:
==32103==    definitely lost: 0 bytes in 0 blocks
==32103==    indirectly lost: 0 bytes in 0 blocks
==32103==      possibly lost: 0 bytes in 0 blocks
==32103==    still reachable: 27,632 bytes in 70 blocks
==32103==         suppressed: 0 bytes in 0 blocks
==32103== Reachable blocks (those to which a pointer was found) are not shown.
==32103== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==32103== 
==32103== For counts of detected and suppressed errors, rerun with: -v
==32103== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

```

then it hit me, oh @grondo probably meant increased valgrind verbosity .. doh

```
+               --wrap=--verbose \
```

**Comment by grondo** [comment] 2019-06-19 18:02
Well I actually meant `flux-start` verbosity, since I think it is the thing killing the rank 0 broker. However, more verbosity everywhere won't hurt!!

**Comment by chu11** [comment] 2019-06-19 18:33
It just occurred to me, I set the verbosity on the broker, not `flux-start`, but verbosity in `flux-start` just shows the broker options.  Lets just add a `log_err()` to here, which doesn't have anything at the moment.

```
void killer (flux_reactor_t *r, flux_watcher_t *w, int revents, void *arg)                                                                                   
{                                                                                                                                                            
    struct client *cli;                                                                                                                                      
                                                                                                                                                             
    cli = zlist_first (ctx.clients);                                                                                                                         
    while (cli) {                                                                                                                                            
        flux_future_t *f = flux_subprocess_kill (cli->p, SIGKILL);                                                                                           
        if (f)                                                                                                                                               
            flux_future_destroy (f);                                                                                                                         
        cli = zlist_next (ctx.clients);                                                                                                                      
    }                                                                                                                                                        
}  
```

**Comment by grondo** [comment] 2019-10-02 15:31
Hit this one again in a Travis builder, so apparently *not* fixed by longer killer-timeout.

**Closed** 2022-08-17 17:27 UTC
Labels: wontfix
