### ISSUE TITLE
make install fails on Sierra with undefined reference error 

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1755] opened 2018-10-23 18:18 UTC
As suggested by @SteVwonder: https://github.com/flux-framework/flux-sched/issues/395

I tried to build the current master with notce so that I can use the system GNU compilers.

```
sierra4360{dahn}25: ll ~/.notce
-rw------- 1 dahn dahn 0 Oct 23 10:57 /g/g0/dahn/.notce

sierra4360{dahn}22: which g++
/usr/bin/g++
sierra4360{dahn}23: which gcc
/usr/bin/gcc

sierra4360{dahn}27: pwd
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core
sierra4360{dahn}29: autogen.sh
<CUT>
sierra4360{dahn}30: cd build-blueos_3_ppc64le_ib_p9
sierra4360{dahn}31: ../configure --prefix=/nfs/tmp2/dahn/workspace/FLUX_SIERRA/inst
<CUT>

sierra4360{dahn}36: make -j20
<CUT>
sierra4360{dahn}37: make -j20 check
<CUT>
sierra4360{dahn}38: make install
<CUT>
make[5]: Entering directory `/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux'
echo Copying libraries to where they can be used by python in-tree
Copying libraries to where they can be used by python in-tree
[ "../../../../.." != "../../../.." ] && cp ../../../../../src/bindings/python/_flux/__init__.py ./; \
for LIB in _core.so _kvs.so _jsc.so _kz.so ; do \
	test -e .libs/$LIB && \
	ln -s .libs/$LIB ./ || true; \
done
ln: failed to create symbolic link './_core.so': File exists
ln: failed to create symbolic link './_kvs.so': File exists
ln: failed to create symbolic link './_jsc.so': File exists
ln: failed to create symbolic link './_kz.so': File exists
make[6]: Entering directory `/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux'
make[6]: Nothing to be done for `install-exec-am'.
 /usr/bin/mkdir -p '/nfs/tmp2/dahn/workspace/FLUX_SIERRA/inst/lib64/python2.7/site-packages/_flux'
 /bin/sh ../../../../libtool   --mode=install /usr/bin/install -c   _core.la _kvs.la _jsc.la _kz.la '/nfs/tmp2/dahn/workspace/FLUX_SIERRA/inst/lib64/python2.7/site-packages/_flux'
libtool: install: warning: relinking `_core.la'
libtool: install: (cd /nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux; /bin/sh /nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/libtool  --silent --tag CC --mode=relink gcc -std=gnu99 -g -O2 -avoid-version -module -Wl,--no-undefined -L/usr/lib64 -lpython2.7 -Wl,-rpath,/nfs/tmp2/dahn/workspace/FLUX_SIERRA/inst/lib -o _core.la -rpath /nfs/tmp2/dahn/workspace/FLUX_SIERRA/inst/lib64/python2.7/site-packages/_flux _core.lo ../../../../src/common/libflux-core.la ../../../../src/common/libflux-internal.la -lczmq -lzmq -lm )
.libs/_core.o: In function `_cffi_d_flux_rpc_message':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:15586: undefined reference to `flux_rpc_message'
.libs/_core.o: In function `_cffi_f_flux_rpc_message':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:15644: undefined reference to `flux_rpc_message'
.libs/_core.o: In function `_cffi_d_flux_rpc_get_matchtag':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:15474: undefined reference to `flux_rpc_get_matchtag'
.libs/_core.o: In function `_cffi_f_flux_rpc_get_matchtag':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:15497: undefined reference to `flux_rpc_get_matchtag'
.libs/_core.o: In function `_cffi_d_flux_requeue_nocopy':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:14547: undefined reference to `flux_requeue_nocopy'
.libs/_core.o: In function `_cffi_f_flux_requeue_nocopy':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:14598: undefined reference to `flux_requeue_nocopy'
.libs/_core.o: In function `_cffi_d_flux_future_fatal_error':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:6089: undefined reference to `flux_future_fatal_error'
.libs/_core.o: In function `_cffi_f_flux_future_fatal_error':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:6139: undefined reference to `flux_future_fatal_error'
.libs/_core.o: In function `_cffi_d_flux_future_error_string':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:6053: undefined reference to `flux_future_error_string'
.libs/_core.o: In function `_cffi_f_flux_future_error_string':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:6076: undefined reference to `flux_future_error_string'
.libs/_core.o: In function `_cffi_d_flux_buffer_read_trimmed_line':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:3194: undefined reference to `flux_buffer_read_trimmed_line'
.libs/_core.o: In function `_cffi_f_flux_buffer_read_trimmed_line':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:3238: undefined reference to `flux_buffer_read_trimmed_line'
.libs/_core.o: In function `_cffi_d_flux_buffer_peek_trimmed_line':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:2959: undefined reference to `flux_buffer_peek_trimmed_line'
.libs/_core.o: In function `_cffi_f_flux_buffer_peek_trimmed_line':
/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux/_core.c:3003: undefined reference to `flux_buffer_peek_trimmed_line'
collect2: error: ld returned 1 exit status
libtool: install: error: relink `_core.la' with the above command before installing it
make[6]: *** [install-fluxsoLTLIBRARIES] Error 1
make[6]: Leaving directory `/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux'
make[5]: *** [install-am] Error 2
make[5]: Leaving directory `/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux'
make[4]: *** [install] Error 2
make[4]: Leaving directory `/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python/_flux'
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory `/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings/python'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src/bindings'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/nfs/tmp2/dahn/workspace/FLUX_SIERRA/flux-core/build-blueos_3_ppc64le_ib_p9/src'
make: *** [install-recursive] Error 1
```

**Comment by garlick** [comment] 2018-10-25 20:10
I'm seeing this too, on `v0.10.0-328-gbd23bac`.

**Comment by SteVwonder** [comment] 2018-10-25 22:30
Hmmm.  Compiling/installing with spack "just works".  I'll try and do a manual compile.

**Comment by trws** [comment] 2018-10-25 23:47
Oddly I just had an error like this on quartz:

```
make[4]: Entering directory `/g/g12/scogland/projects/flux/flux-core/build-toss3/src/modules/kvs'
make[4]: Nothing to be done for `install-exec-am'.
 /usr/bin/mkdir -p '/g/g12/scogland/projects/flux/flux-core/build-toss3/install/lib/flux/modules'
 /bin/sh ../../../libtool   --mode=install /usr/bin/install -c   kvs.la '/g/g12/scogland/projects/flux/flux-core/build-toss3/install/lib/flux/modules'
libtool: warning: relinking 'kvs.la'
libtool: install: (cd /g/g12/scogland/projects/flux/flux-core/build-toss3/src/modules/kvs; /bin/sh "/g/g12/scogland/projects/flux/flux-core/build-toss3/libtool"  --silent --tag CC --mode=relink gcc -std=gnu99 -Wall -Werror -Werror=missing-field-initializers -Wno-strict-aliasing -Wno-error=deprecated-declarations -g -O2 -Wl,--no-undefined -avoid-version -export-symbols-regex "^mod_(main|name|service)\$" --disable-static -shared -export-dynamic -module -o kvs.la -rpath /g/g12/scogland/projects/flux/flux-core/build-toss3/install/lib/flux/modules kvs.lo cache.lo waitqueue.lo kvs_util.lo lookup.lo treq.lo kvstxn.lo kvsroot.lo ../../../src/common/libkvs/libkvs.la ../../../src/common/libflux-internal.la ../../../src/common/libflux-core.la -lm )
.libs/kvs.o: In function `getroot_completion':
/g/g12/scogland/projects/flux/flux-core/build-toss3/src/modules/kvs/../../../../src/modules/kvs/kvs.c:398: undefined reference to `flux_requeue_nocopy'
../../../src/common/libkvs/.libs/libkvs.a(kvs_lookup.o): In function `flux_kvs_lookup_cancel':
/g/g12/scogland/projects/flux/flux-core/build-toss3/src/common/libkvs/../../../../src/common/libkvs/kvs_lookup.c:409: undefined reference to `flux_rpc_get_matchtag'
../../../src/common/libkvs/.libs/libkvs.a(kvs_getroot.o): In function `flux_kvs_getroot_cancel':
/g/g12/scogland/projects/flux/flux-core/build-toss3/src/common/libkvs/../../../../src/common/libkvs/kvs_getroot.c:212: undefined reference to `flux_rpc_get_matchtag'
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'kvs.la' with the above command before installing it
make[4]: *** [install-fluxmodLTLIBRARIES] Error 1
make[4]: Leaving directory `/g/g12/scogland/projects/flux/flux-core/build-toss3/src/modules/kvs'
make[3]: *** [install-am] Error 2
make[3]: Leaving directory `/g/g12/scogland/projects/flux/flux-core/build-toss3/src/modules/kvs'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/g/g12/scogland/projects/flux/flux-core/build-toss3/src/modules'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/g/g12/scogland/projects/flux/flux-core/build-toss3/src'
make: *** [install-recursive] Error 1

```

I was doing a parallel make install when it happened.  A regular make completes without issues, in the same tree.  Nothing I do now seems to fix it, including cleaning and rebuilding seriallly...

**Comment by trws** [comment] 2018-10-25 23:56
Re-doing the build using the system autotools (rather than a newer version from my home directory) now gives me the exact same error @dongahn got, in exactly the same place.

**Comment by SteVwonder** [comment] 2018-10-26 01:03
@trws which make?  Using the autotools in `/usr/bin` but `/usr/tcetmp/bin/make`, my compilation succeeds.  So maybe the issue is make.  Lemme see if I can get rid of that make with `~/.notce`.

I'm also using spack packages for the following runtime dependencies: 
```
zlib
zeromq
yaml
xz
unzip
sqlite
readline
python
py-six
py-pycparser
py-cffi
openssl
numactl
ncurses
munge
lz4
lua
lua
libxml2
libuuid
libsodium
libpciaccess
libgpg
libgcrypt
libffi
jansson
hwloc
gdbm
czmq
bzip2
```

**Comment by SteVwonder** [comment] 2018-10-26 06:08
I think I isolated the problem (haven't quite grok'd how differing versions of autotools and compilers play into it yet though, [maybe something to do with lazy linking](https://www.redhat.com/archives/libvir-list/2010-May/msg00189.html)?).

So the offending compilation line (obtained by running the failing libtool relink command with `--debug`) is: 
```
gcc -std=gnu99 -shared -fPIC -DPIC .libs/_core_la-_core.o \
  -Wl,-rpath -Wl,/g/g0/herbein1/opt/packages/toss3/flux-core/test-sierra/lib \
  -L/usr/lib64 -lpython2.7 -L/g/g0/herbein1/opt/packages/toss3/flux-core/test-sierra/lib \
  -ljansson -lpthread -lutil -ldl -lczmq -lzmq -lm -lflux-core -O2 \
  -Wl,--no-undefined -Wl,-rpath -Wl,/g/g0/herbein1/opt/packages/toss3/flux-core/test-sierra/lib \
  -Wl,-soname -Wl,_core.so -o .libs/_core.so
```

If I add `-Wl,--verbose`, we can see that the linker is grabbing the system-installed libflux-core.so which doesn't define the symbols we need. This is because `-L/usr/lib64` comes before `-L$PREFIX` in the compilation line:
```
attempt to open /usr/lib64/libflux-core.so succeeded
-lflux-core (/usr/lib64/libflux-core.so)
attempt to open /usr/lib64/libgcc.so failed
attempt to open /usr/lib64/libgcc.a failed
attempt to open /g/g0/herbein1/opt/packages/toss3/flux-core/test-sierra/lib/libgcc.so failed
attempt to open /g/g0/herbein1/opt/packages/toss3/flux-core/test-sierra/lib/libgcc.a failed
attempt to open /usr/lib/gcc/ppc64le-redhat-linux/4.8.5/libgcc.so failed
attempt to open /usr/lib/gcc/ppc64le-redhat-linux/4.8.5/libgcc.a succeeded
attempt to open /usr/lib64/libgcc_s.so failed
attempt to open /usr/lib64/libgcc_s.a failed
attempt to open /g/g0/herbein1/opt/packages/toss3/flux-core/test-sierra/lib/libgcc_s.so failed
attempt to open /g/g0/herbein1/opt/packages/toss3/flux-core/test-sierra/lib/libgcc_s.a failed
attempt to open /usr/lib/gcc/ppc64le-redhat-linux/4.8.5/libgcc_s.so succeeded
-lgcc_s (/usr/lib/gcc/ppc64le-redhat-linux/4.8.5/libgcc_s.so)
```

The `-L/usr/lib64` is coming from the `AM_LDFLAGS` defined in `_flux/Makefile.am` and the `-L$PREFIX` is coming from the use of `LIBADD` (I think):
```
AM_LDFLAGS = \
    -avoid-version -module $(san_ld_zdef_flag) \
    $(PYTHON_LDFLAGS) -Wl,-rpath,$(PYTHON_PREFIX)/lib \
    $(CODE_COVERAGE_LIBS) $(ZMQ_LIBS)

_core_la_LIBADD = $(top_builddir)/src/common/libflux-core.la \
          $(top_builddir)/src/common/libflux-internal.la
```

LDFLAGS come earlier in the compilation line than LIBADD, so the `-L/usr/lib64` in `$(PYTHON_LDFLAGS)` comes first, "polluting" the linkers search path with the system library path that also contains a libflux-core.so.

I'm not sure if it's as simple as merging the LDFLAGS and LIBADD variables, or if it's more complex. I can play around with things tomorrow afternoon unless someone knows "The Right Way" to fix this.

**Comment by dongahn** [comment] 2018-10-26 15:41
Thanks Stephen! 

There may be some odd things going on on Sierra though. For that C++ version mismatch like problems which I fixed by copying libjobspec into flux-sched shouldn't have been a problem when I used the same compiler between core and sched. But it was still happening. 

I was wondering if there are some misconfiguration of some sort in our compiler setting...

**Comment by trws** [comment] 2018-10-26 16:45
That offer of re-writing this in cmake is still on the table...

As a short-form fix, we should add a -L<path_to_build_lib_dir> in the LDFLAGS before the python_ldflags reference.  The order that `-L` appears with respect to `-l` on the line doesn't matter, only the order of `-L` with respect to each other, so it should take care of it.

**Comment by trws** [comment] 2018-10-26 17:00
Oh good, libtool is injecting the -L/usr/lib64 that causes it to fail in the other case I was looking at.  Yay...

```sh
# Libraries that this one depends upon.
dependency_libs=' -L/usr/lib64 -ljansson -lczmq -lzmq -lpthread -lutil -ldl -lm'
```

**Comment by SteVwonder** [comment] 2018-10-26 23:39
@dongahn: The linking issue that you hit can be fixed with the following one-line patch.  @trws has reported running into a similar problem elsewhere, so I don't know what the general solution is.

```
diff --git a/src/bindings/python/_flux/Makefile.am b/src/bindings/python/_flux/Makefile.am
index ec88fc1..cf40a52 100644
--- a/src/bindings/python/_flux/Makefile.am
+++ b/src/bindings/python/_flux/Makefile.am
@@ -6,6 +6,7 @@ AM_CPPFLAGS = \
        $(CODE_COVERAGE_CFLAGS)

 AM_LDFLAGS = \
+       -L$(libdir) \
        -avoid-version -module $(san_ld_zdef_flag) \
        $(PYTHON_LDFLAGS) -Wl,-rpath,$(PYTHON_PREFIX)/lib \
        $(CODE_COVERAGE_LIBS)
```

**Comment by grondo** [comment] 2018-11-08 21:31
I hit this issue trying to side-install flux-core on a system with an existing, older flux-core.

The issue appears to be use of `PYTHON_LDFLAGS`, which in my case contains `-L/usr/lib64` with `AM_LDFLAGS` instead of `_LIBADD` or `_LDADD` as (I think) it should be.

In my specific case, this patch fixed the build:

```diff
diff --git a/src/bindings/python/_flux/Makefile.am b/src/bindings/python/_flux/M
index 71faaa2..e0a9e84 100644
--- a/src/bindings/python/_flux/Makefile.am
+++ b/src/bindings/python/_flux/Makefile.am
@@ -7,7 +7,7 @@ AM_CPPFLAGS = \
 
 AM_LDFLAGS = \
        -avoid-version -module $(san_ld_zdef_flag) \
-       $(PYTHON_LDFLAGS) -Wl,-rpath,$(PYTHON_PREFIX)/lib \
+       -Wl,-rpath,$(PYTHON_PREFIX)/lib \
        $(CODE_COVERAGE_LIBS)
 
 MAKE_BINDING=$(top_srcdir)/src/bindings/python/make_binding.py
@@ -15,7 +15,8 @@ SUFFIXES = _build.py
 
 common_libs = $(top_builddir)/src/common/libflux-core.la \
              $(top_builddir)/src/common/libflux-internal.la \
-             $(ZMQ_LIBS)
+             $(ZMQ_LIBS) \
+             $(PYTHON_LDFLAGS)
 
 _build.py.c:
        $(PYTHON) $*_build.py
diff --git a/src/modules/pymod/Makefile.am b/src/modules/pymod/Makefile.am
index 346080f..8b1d141 100644
--- a/src/modules/pymod/Makefile.am
+++ b/src/modules/pymod/Makefile.am
@@ -18,7 +18,7 @@ AM_CPPFLAGS = \
 fluxmod_LTLIBRARIES = pymod.la
 
 pymod_la_SOURCES = py_mod.c
-pymod_la_LDFLAGS = $(fluxmod_ldflags) -module $(PYTHON_LDFLAGS)
+pymod_la_LDFLAGS = $(fluxmod_ldflags) -module
 
 # allow pymod to find the configured libpython at runtime
 pymod_la_LDFLAGS += -Wl,-rpath -Wl,$(PYTHON_PREFIX)/lib
@@ -26,7 +26,8 @@ pymod_la_LDFLAGS += -Wl,-rpath -Wl,$(PYTHON_PREFIX)/lib
 pymod_la_LIBADD = $(top_builddir)/src/common/libflux-core.la \
                  $(top_builddir)/src/common/libflux-internal.la \
                  $(top_builddir)/src/common/libflux-optparse.la \
-                 $(ZMQ_LIBS)
+                 $(ZMQ_LIBS) \
+                 $(PYTHON_LDFLAGS)
 
 fluxpymod_PYTHON = echo.py __init__.py
```

**Comment by trws** [comment] 2018-11-13 15:32
If that works, it's certainly better than the alternative, but shouldn't it at least be in `_LDFLAGS`? It only contains `-l` and `-L` in this particular instance, but on some platforms it may contain more?

**Comment by grondo** [comment] 2018-11-13 16:56
> If that works, it's certainly better than the alternative, but shouldn't it at least be in `_LDFLAGS`?

`-l` and `-L` are explicitly supposed to go in `_LIBADD` or `_LDADD`. Probably the python m4 should separate an `LDFLAGS` and `LIBS` variables or something. My guess is this is a common misunderstanding. (I know I was confused)

**Comment by SteVwonder** [comment] 2019-01-05 00:33
I'm no longer seeing this issue on Sierra with 0.11.0.  I'm guessing #1795 fixed it?

@dongahn, is this still an issue for you?

**Comment by SteVwonder** [comment] 2020-03-14 00:14
Closing since this issue appears to be fixed.

**Closed by SteVwonder** 2020-03-14 00:14 UTC
