### ISSUE TITLE
high rate job submission stalls sched message queue

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1376] opened 2018-03-22 16:47 UTC
Submitting jobs fast enough, or enough of them over time, stalls sched out completely.  I've seen this happen with <5000 jobs when submitted at a very high rate, and around 35000 jobs at a slightly slower rate.

**Comment by dongahn** [comment] 2018-03-22 16:51
Is this with delay schedule and queue depth optimization?

**Comment by trws** [comment] 2018-03-22 16:55
Yes, and with several other optimizations I've applied to jsc, hardware topology pruning and disabling priority support.

**Comment by dongahn** [comment] 2018-03-22 17:14
Ok. This needs to be debugged. What is the scale at which this can be reproduced. My guess is we can use 'sleep 0' 5000 jobs back to back. I had a success at 10K way back at small scales so if this occurs at small scale, this could be caused by some changes afterward. (although this can be anything at this point).

Anything changed in flux eventing BTW?

**Comment by trws** [comment] 2018-03-22 17:21
If you want to get it consistently, use `seq 1 50000 | xargs -n 1 -P 15 
flux submit -n 1 sleep 0`.  It may take up to 15 minutes to stall out, 
but that will do it.

**Comment by trws** [comment] 2018-03-22 17:52
I’m not sure, because the messaging blocks up as well, so I don’t 
really know which side is the problem.

**Comment by garlick** [comment] 2018-04-09 20:40
I tried submitting 50K sleep 0 jobs without sched loaded (disabling the wreck/job test for sched availability) and found that the submit rate stayed _pretty_ even at around 100 jobs/sec all the way through (using highly accurate  "one thousand one, one thousand two, ..." timing while watching the 100's digit of the job id's outputted by flux-submit)

Immediately afterwards, the rank 0 kvs module responded to pings with millisecond response tiimes.

I used this command
```
seq 1 50000 | xargs -n 1 | flux submit -n 1 sleep 0
```
So at least I think the submit path has no problem at scale. 

I'm going to tentatively close this here and reopen on the sched project.

**Closed by garlick** 2018-04-09 20:40 UTC

**Comment by trws** [comment] 2018-04-09 20:44
I’d add one thing here, as long as there is only one process 
submitting, it took me a *long* time to get to where things would start 
to bog down.  The main source of slowdown may be in sched, but you may 
want to add a `-P 15` to that xargs command before writing it off, as I 
think at least a chunk of it is in JSC.

**Comment by grondo** [comment] 2018-04-09 20:58
The `job` module itself may also be to blame because it creates each job with a series of synchronous RPCs (allocate a jobid from sequence module, synchronous kvs transaction, send "create" event and wait to receive said event to ensure it has been published). I bet if we made all those call asynchronous the multiple job creators case would get much better.

Another idea would be to spread the load across multiple job modules (i.e. round robin or random spread across ranks in flux-submit). I think any job module is capable of the `job.create` and `submit` rpcs.

**Comment by dongahn** [comment] 2018-04-09 21:16
I agree we want to continue to optimize this, but ultimately this will be bounded by a generic queueing system problem: if we enqueue items faster than what the queuing system can process and dequeue, imbalance will occur. For example, what happens if we use `-P 32`? How about `-P 128`

For extreme HTC workloads like this, we should better off investing our time into hierarchical scheduling?

**Comment by trws** [comment] 2018-04-09 22:02
Or parallel, yeah.  The reason I consider this a bug isn’t to do with 
scheduling though, it’s that sched stops getting notifications and 
stops processing *at all* when it hits a certain point, and it’s 
spending all of its time in the message queue rather than actually 
attempting to schedule jobs even if the inflow of jobs stops.  That’s 
why I posted this to core to begin with, even if it shows up in sched, 
the backup doesn’t seem to be there.

**Comment by garlick** [comment] 2018-04-10 00:04
I repeated the test with `xargs -P 15`  and it still chugs along at about 100 jobs / sec.  (and I pushed it up to `-P 200`) and still about the same. More than that and I seem to have some other instabilities going on - maybe a lack of file descriptors)

We can certainly increase the ingest rate by fixing the job module's synchronous RPC's.

However if we're pushing 50K jobs through the system and limiting the submission parallelism (to 15 or 200 or whatever), the job module's endpoint queue will only grow to a max depth of 15 or 200, but sched's endpoint queue could be many thousands deep.

Synchronous RPC's in sched would then have a lot more requeueing to do when searching for their response.  (To review, each synchronous RPC deuqueues the entire queue looking for its response, then when it finally arrives, "requeues" all those messages before returning.  Next synchronouse RPC starts over).

So I would presume converting the sched synchronous RPC's to continuations is the more urgent need, at least the way this was described.

**Comment by grondo** [comment] 2018-04-10 00:09
Nice investigation @garlick. That puts things in perspective and a good investigation.

**Comment by dongahn** [comment] 2018-04-10 00:28
Good investigation @garlick. Just so that I understand.
 
> However if we're pushing 50K jobs through the system and limiting the submission parallelism (to 15 or 200 or whatever), the job module's endpoint queue will only grow to a max depth of 15 or 200, but sched's endpoint queue could be many thousands deep.

So job module is loaded across the all of the nodes and the assumption is users will submit jobs across different ranks to increase parallelism at the job module level? 

> So I would presume converting the sched synchronous RPC's to continuations is the more urgent need, at least the way this was described.

@garlick:  I'm all for this optimization. It's just that this seems to require substantial changes and we will want to balance this work against other work. Just to make sure I understand the priority.

Is this needed for splash?

**Comment by dongahn** [comment] 2018-04-10 15:54
Thanks @garlick. Sounds good to me. I will be on travel giving a talk this Thu so I will swing by your office to discuss this if you don't mind.
