### ISSUE TITLE
flux-start: suppress "exited with rc=0" messages

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1749] opened 2018-10-23 13:02 UTC
It's probably not that useful for `flux-start` to print the exit code of every broker when the exit code is zero:
```
./flux start -s4
flux-start: warning: setting --bootstrap=selfpmi due to --size option
garlick@sun1:~/proj/flux-core/src/cmd$ exit
exit
flux-start: 3 (pid 12403) exited with rc=0
flux-start: 2 (pid 12400) exited with rc=0
flux-start: 1 (pid 12398) exited with rc=0
flux-start: 0 (pid 12396) exited with rc=0
```

**Comment by grondo** [comment] 2018-10-30 17:37
The code to print exit code from flux-start also has other issues and should be fixed along with this bug:

See below, the order of tests should be changed back to the old order (copied from the `wait(2)` manpage. Right now `flux-start` will always print `Unknown signal 0` if a broker dies due to a signal, because the first test is `WIFSIGNALED`, but `WSTOPSIG (status)` is used.

```C
        if ((status = flux_subprocess_status (p)) >= 0) {
            if (WIFSIGNALED (status))
                log_msg ("%d (pid %d) %s", cli->rank, pid, strsignal (WSTOPSIG (status)));
            else if (WIFCONTINUED (status))
                log_msg ("%d (pid %d) %s", cli->rank, pid, strsignal (SIGCONT));
            else if (WIFSIGNALED (status))
                log_msg ("%d (pid %d) %s", cli->rank, pid, strsignal (WTERMSIG (status)));
            else if (WIFEXITED (status))
                log_msg ("%d (pid %d) exited with rc=%d", cli->rank, pid, WEXITSTATUS (status));
        } else
            log_msg ("%d (pid %d) exited, unknown status", cli->rank, pid);
    }
```

**Comment by grondo** [comment] 2018-10-30 17:41
From `wait(2`)`:
```C
                   if (WIFEXITED(wstatus)) {
                       printf("exited, status=%d\n", WEXITSTATUS(wstatus));
                   } else if (WIFSIGNALED(wstatus)) {
                       printf("killed by signal %d\n", WTERMSIG(wstatus));
                   } else if (WIFSTOPPED(wstatus)) {
                       printf("stopped by signal %d\n", WSTOPSIG(wstatus));
                   } else if (WIFCONTINUED(wstatus)) {
                       printf("continued\n");
                   }

```

**Comment by grondo** [comment] 2018-10-30 17:49
Actually, looking again, the problem is that the first `WIFSIGNALED` was supposed to be `WIFSTOPPED`.
However, the tests for `WIFSIGNALED` and `WIFSTOPPED` could probably just be removed since the code is only executed when `FLUX_SUBPROCESS_EXITED`.

**Closed** 2018-11-09 03:47 UTC
