### ISSUE TITLE
flux mini run nearly hangs when 4-task job prints in a tight loop

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2505] opened 2019-11-02 01:11 UTC
In an effort to reproduce Issue #2500, I created a simple hello world that prints out in a tight loop. I launched this with with flux mini run, which then appears to hang after printing out some lines. I ctrl-c out of it and then try to exit, the flux instance seemed to have some issues.

The same code works ok with srun. 

```
quartz42{dahn}28: srun -N 4 -n 4 --mpi=none --pty /usr/global/tools/flux/toss_3_x86_64_ib/flux-0.13.x-20191017-dbg/bin/flux start
quartz42{dahn}21: flux mini run -N 4 -n 4 ./virtual_ring_mpi

<CUT>
Hello world: 3 771
Hello world: 1 611
Hello world: 0 363
Hello world: 3 772
^Cflux-job: one more ctrl-C within 2s to cancel or ctrl-Z to detach
^Cflux-job: one more ctrl-C within 2s to cancel or ctrl-Z to detach
^C^C
^Cflux-job: one more ctrl-C within 2s to cancel or ctrl-Z to detach
^C
^Cflux-job: one more ctrl-C within 2s to cancel or ctrl-Z to detach
^C^C^C
flux-job: stdin not accepted by job
quartz42{dahn}22:
quartz42{dahn}22:
quartz42{dahn}22:
quartz42{dahn}22:
quartz42{dahn}22: flux job list
JOBID		STATE	USERID	PRI	T_SUBMIT
448790528000	C	7818	16	2019-11-02T00:34:30Z
quartz42{dahn}23:
quartz42{dahn}23:
quartz42{dahn}23:
quartz42{dahn}23: exit
exit
flux-broker: module 'kvs-watch' was not cleanly shutdown
flux-broker: module 'userdb' was not cleanly shutdown
flux-broker: module 'job-info' was not cleanly shutdown
flux-broker: module 'barrier' was not cleanly shutdown
flux-broker: module 'cron' was not cleanly shutdown
flux-broker: module 'job-manager' was not cleanly shutdown
flux-broker: module 'aggregator' was not cleanly shutdown
flux-broker: module 'content-sqlite' was not cleanly shutdown

srun: First task exited 30s ago
srun: step:3850708.5 task 0: running
srun: step:3850708.5 tasks 1-3: exited
srun: Terminating job step 3850708.5
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
srun: error: quartz42: task 0: Killed

```

reproducer code.
```c
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
#include <signal.h>
#define COMM_TAG 1000

double tst_abc;

void pass_its_neighbor(const int rank, const int size, int* buf)
{
  MPI_Request request[2];
  MPI_Status status[2];
  int rcvbuf;
  int i;
  char *hn = malloc(8);
  char *bigblock = malloc(1024);
  gethostname (hn, 32);

  tst_abc = 0.3;

  for (i = 0; i < 1000 ; i++) {
      MPI_Irecv((void*)buf, 1, MPI_INT, ((rank+size-1)%size), COMM_TAG, MPI_COMM_WORLD, &request[0]);
      MPI_Isend((void*)&rank, 1, MPI_INT, ((rank+1)%size), COMM_TAG, MPI_COMM_WORLD, &request[1]);
      MPI_Waitall(2, request, status);
      MPI_Allreduce((void *) &rank, (void *) &rcvbuf, 1, MPI_INT, MPI_MAX, MPI_COMM_WORLD);
  }

  for (i = 0; i < 10000; i++) {
     fprintf (stdout, "Hello world: %d %d\n", (int)rank, i);
  }

  if (rank==0) {
     fprintf(stdout, "rcvbuf: %d \n", rcvbuf);
  }

  MPI_Barrier(MPI_COMM_WORLD);
}

int main(int argc, char* argv[])
{

  int size, rank, i;
  int *buf = (int*) malloc(sizeof(int));

  tst_abc = 0.2;

  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &size);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);

  *buf=rank; /* we only pass around rank*/
  pass_its_neighbor(rank, size, buf);
  free (buf);

  MPI_Finalize();

  return 0;
}
```

**Comment by grondo** [comment] 2019-11-02 17:25
Yeah, I see a similar problem just with a simple `flux mini run -n64 t/shell/lptest 80 500`.

Even long after the job is killed, the kvs module doesn't respond to ping requests, and the broker is consuming 100% CPU (presumably the kvs module).

It seems flux could at least handle this case before and not fall over, IIRC. Not sure what has changed since then.

I tried a quick and dirty experiment converting the output module to use the eventlogger introduced in #2477 to try to reduce the kvs_commit frequency but that didn't seem to help. (maybe I got something wrong though)

**Comment by grondo** [comment] 2019-11-02 18:24
Hm, hopefully this isn't something going haywire in the new logging code.

I'll test before and after #2477 to make sure.

**Comment by grondo** [comment] 2019-11-02 22:08
No, I see the same problem before #2477 was merged.

I tried to run perf while the kvs module appears hung, but for some reason I wasn't having much luck with that today. Will try again later.

**Comment by grondo** [comment] 2019-11-03 02:09
BTW, I did verify that if you send stdout/err to a file the problem is mitigated. For now we may want to suggest users always use the mini run `--output` option.

**Comment by chu11** [comment] 2019-11-05 00:36
Simply running `perf record src/cmd/flux start --size=N flux mini run -nN t/shell/lptest 80 500` on various sizes "N", I saw this on N=64

```
  18.39%        270805  flux-broker-0    kvs.so                        [.] blobref_validate
  11.92%        186750  flux-broker-0    libc-2.17.so                  [.] _int_malloc
   8.55%        126322  flux-broker-0    libc-2.17.so                  [.] malloc_consolidate
   5.83%         95384  flux-broker-0    libc-2.17.so                  [.] _int_free
   5.02%        224150  lt-flux-shell    libflux-core.so.2.0.0         [.] cbuf_is_valid
   4.48%         67269  flux-broker-0    libc-2.17.so                  [.] malloc
   2.86%         42454  flux-broker-0    libc-2.17.so                  [.] __strcmp_sse42
   2.84%        126738  lt-flux-shell    libpthread-2.17.so            [.] pthread_mutex_trylock
   2.28%         33695  flux-broker-0    libc-2.17.so                  [.] __strlen_sse2_pminub
   2.05%         30121  flux-broker-0    libjansson.so.4.10.0          [.] json_string_value
```

What stood out to me was as I increased N:

1) `blobref_validate()` - This is a simple loop to make sure blobrefs are valid (calls `isxdigit()`), so I imagine it just eats tons of cycles just constantly checking `isxdigit()` on tons of KVS objects.  It is called in `treeobj_validate()`.  Perhaps we can be limit number of times we call this.  Will have to look into this.

2) `cbuf_is_valid()`  - `cbuf_is_valid()` is an internal cbuf assert check that is clearly eating up more cycles than it really should.  It internally includes over 26 assert checks, including calls to `pthread_mutex_trylock()` (which you can see above) and `memcmp()` (which was just outside of the top 10).  Would be worth investigating limiting this, b/c 8% on (effectively) "is this cbuf valid" seems excessive.  And I think cbuf is only used in code that is not threaded, so maybe we need to compile `cbuf` without that check.

**Comment by grondo** [comment] 2019-11-05 00:50
Nice analysis!

It might be most useful to focus on the broker code at first, since that is where the major impact will be (the kvs wasn't responding to pings even after the job is killed in my tests)

I also notice that the broker is heavily using malloc/free -- maybe we need to audit the common path and try to reduce the use of the allocator if at all possible?

**Comment by chu11** [comment] 2019-11-05 17:15
The primary culprit `treeobj_validate()` call was in `treeobj_insert_entry()`.  This change:

```
diff --git a/src/common/libkvs/treeobj.c b/src/common/libkvs/treeobj.c
index 7dbcb21..ac6c250 100644
--- a/src/common/libkvs/treeobj.c
+++ b/src/common/libkvs/treeobj.c
@@ -313,12 +313,20 @@ int treeobj_insert_entry (json_t *obj, const char *name, json_t *obj2)
     const char *type;
     json_t *data;

+#if 0
     if (!name || !obj2 || treeobj_unpack (obj, &type, &data) < 0
             || strcmp (type, "dir") != 0
             || treeobj_validate (obj2) < 0) {
         errno = EINVAL;
         return -1;
     }
+#else
+    if (!name || !obj2 || treeobj_unpack (obj, &type, &data) < 0
+            || strcmp (type, "dir") != 0) {
+        errno = EINVAL;
+        return -1;
+    }
+#endif
     if (json_object_set (data, name, obj2) < 0) {
         errno = EINVAL;
         return -1;
```

leads to

```
  18.93%        195777  flux-broker-0    libc-2.17.so                    [.] _int_malloc
  13.61%        132136  flux-broker-0    libc-2.17.so                    [.] malloc_consolidate
   9.32%        100883  flux-broker-0    libc-2.17.so                    [.] _int_free
   7.36%         72683  flux-broker-0    libc-2.17.so                    [.] malloc
   4.88%        138302  lt-flux-shell    libflux-core.so.2.0.0           [.] cbuf_is_valid
   2.85%         29174  flux-broker-0    libc-2.17.so                    [.] free
   2.71%         76998  lt-flux-shell    libpthread-2.17.so              [.] pthread_mutex_trylock
   1.96%         18992  flux-broker-0    libjansson.so.4.10.0            [.] json_delete
   1.72%         16683  flux-broker-0    libjansson.so.4.10.0            [.] json_deep_copy
   1.58%         44792  lt-flux-shell    libc-2.17.so                    [.] __memcmp_sse4_1
```

Why?  B/c KVS appends are like this:

```
        if (treeobj_append_blobref (ktmp, ref2) < 0) {
            json_decref (ktmp);
            return -1;
        }

        if (treeobj_insert_entry (dir, final_name, ktmp) < 0) {
            json_decref (ktmp);
            return -1;
        }
```

With all of the appending we're doing to the `guest.output`, we're appending tons of blobrefs to an array of references in the tree object.

And eventually, the `treeobj_validate()` will do this blobref validation loop:

```
        json_array_foreach (data, i, o) {
            if (blobref_validate (json_string_value (o)) < 0)
                goto inval;
        }

```

Which will eventually become very long with all of the appending we're doing.

I need to think of a way to deal with this.

Perhaps if there were a function like:

`treeobj_append_blobref_to_entry (dir, key, blobref)`

we would only have to do a `blobref_validate()` on the new blobref only and not the entire array.  Not sure if that is safe in general though.

Or perhaps some of the ideas we have for large directories (#1207) need to be considered for valref arrays with very long array lengths.

**Comment by chu11** [comment] 2019-11-05 18:16
Well I'm proud of myself for actually properly documenting this region.  This is the important chunk of the KVS append path.

```
else if (treeobj_is_valref (entry)) {
        /* treeobj is valref, so we need to append the new data's                                                                                            
         * blobref to this tree object.  Before doing so, we must save                                                                                       
         * off the new data to the cache and mark it dirty for                                                                                               
         * flushing later (if necessary)                                                                                                                     
         *                                                                                                                                                   
         * Note that we make a copy of the original entry and                                                                                                
         * re-insert it into the directory.  We do not want to                                                                                               
         * accidentally alter any json object pointers that may be                                                                                           
         * sitting in the KVS cache.                                                                                                                         
         */                                                                                                                                                  
                                                                                                                                                             
        if (kvstxn_val_data_to_cache (kt, current_epoch, dirent, ref,                                                                                        
                                      sizeof (ref)) < 0)                                                                                                     
            return -1;                                                                                                                                       
                                                                                                                                                             
        if (!(cpy = treeobj_deep_copy (entry)))                                                                                                              
            return -1;                                                                                                                                       
                                                                                                                                                             
        if (treeobj_append_blobref (cpy, ref) < 0) {                                                                                                         
            json_decref (cpy);                                                                                                                               
            return -1;                                                                                                                                       
        }                                                                                                                                                    
                                                                                                                                                             
        if (treeobj_insert_entry (dir, final_name, cpy) < 0) {                                                                                               
            json_decref (cpy);                                                                                                                               
            return -1;                                                                                                                                       
        }                                                                                                                                                    
                                                                                                                                                             
        json_decref (cpy);     
}
```

Altering an in place tree object in the cache is bad.  This probably also explains why `malloc()` is used so much, as we are constantly calling `json_deep_copy()` whenever we append.

Perhaps we need to look again at our buffering minimums ideas (my prelim idea in PR #2350)

**Comment by garlick** [comment] 2019-11-05 19:13
> Perhaps if there were a function like:
> 
> treeobj_append_blobref_to_entry (dir, key, blobref)

That sounds like a good optimization!

**Comment by chu11** [comment] 2019-11-05 21:59
So looking into it, the `json_deep_copy()` can't be removed, b/c we can't modify a json object that is also stored in the cache.  So if I were to write a `treeobj_dir_entry_append_blobref ()` type of function, it really only serves one purpose, which is to not call the `treeobj_validate()` function as an input check on `treeobj_insert_entry()`.

It's not nothing, it's worth something, but it is non-optimal.

But I think the best solution would be to come up with a `hdir` like plan for very large valref arrays.  So that the `json_deep_copy()`s are not very deep and we make the `treeobj_validate()` calls not against a long array.

**Comment by chu11** [comment] 2019-11-05 23:58
After some discussion with @garlick and @grondo, basically there are a few ways to improve performance.  Listed below, each with increasing difficulty/work, but each with (likely) increasing performance gains.

- write a `treeobj_dir_entry_append_blobref()` like function that will more or less do:

```
entry = treeobj_get_entry (dir, name);
cpy = treeobj_deep_copy (entry);
treeobj_append_blobref (cpy, new_ref);
treeobj_insert_entry (dir, name, cpy);
```

but without the `treeobj_validate()`.  Based on `perf record` above, should hopefully greatly lower that terrible 18% time spent in `blobref_validate()`.

- buffer/batch KVS appends so that the valref array is shorter.  Could use a combination of the shell eventlog batcher (@grondo says has prototype attempt) and modification to `libkvs` to pre-process the KVS txn appends into a smaller number of appends.  This should help both the time spent in `blobref_validate()` and hopefully shorten the time spent in `malloc()` due to `json_deep_copy()`.

- Have "large valref" support similar to large directory support.

Short term, the first option above is easy and should just be done.

The second option is perhaps medium difficult, but should be doable in a reasonable time frame.

But ultimately, for very large jobs with tons of output, the first two options can only do so much.  So eventually the third option will perhaps have to be done.  But it is the one that will take the most time.  Hopefully this can be dealt with down the road.

As a side note, @grondo suggested we could add an option to "buffer all stdout/stderr until the job completes", so that there is a single write of data to the KVS.  This may be sufficient for most jobs.

**Comment by grondo** [comment] 2019-11-06 00:18
@chu11 -- here's my quick and dirty conversion of the output plugin to use the eventlogger interface, which batches the kvs txn for a configurable interval. Default for this test was 500ms, but it is configurable on the `flux mini run` command line with `flux mini run -o output.batch-timeout=5.0` for example.

The current implementation isn't ideal because `eventlogger_append` currently takes a context as a JSON string, so the code has to unpack the context from the json object, then call json_dumps(), but it will let you test different commit intervals.

If we ever went this route, when all EOFs are received the final eventlogger_append() should probably flush the batch by using `EVENTLOGGER_FLAG_WAIT` -- currently the shell will wait the full interval for the final batch (up to batch-timeout seconds.)



```diff
diff --git a/src/shell/output.c b/src/shell/output.c
index b801b12..763d745 100644
--- a/src/shell/output.c
+++ b/src/shell/output.c
@@ -56,6 +56,7 @@
 #include "svc.h"
 #include "internal.h"
 #include "builtins.h"
+#include "eventlogger.h"
 
 enum {
     FLUX_OUTPUT_TYPE_TERM = 1,
@@ -75,6 +76,8 @@ struct shell_output_type_file {
 
 struct shell_output {
     flux_shell_t *shell;
+    struct eventlogger *ev;
+    double batch_timeout;
     int refcount;
     int eof_pending;
     zlist_t *pending_writes;
@@ -334,31 +337,11 @@ error:
     return rc;
 }
 
-static void shell_output_kvs_completion (flux_future_t *f, void *arg)
-{
-    struct shell_output *out = arg;
-
-    /* Error failing to commit is a fatal error.  Should be cleaner in
-     * future. Issue #2378 */
-    if (flux_future_get (f, NULL) < 0)
-        shell_die_errno ("shell_output_kvs");
-    flux_future_destroy (f);
-
-    if (flux_shell_remove_completion_ref (out->shell, "output.kvs") < 0)
-        shell_log_errno ("flux_shell_remove_completion_ref");
-}
-
 static int shell_output_kvs (struct shell_output *out)
 {
     json_t *entry;
     size_t index;
-    flux_kvs_txn_t *txn = NULL;
-    flux_future_t *f = NULL;
-    int saved_errno;
-    int rc = -1;
 
-    if (!(txn = flux_kvs_txn_create ()))
-        goto error;
     json_array_foreach (out->output, index, entry) {
         json_t *context;
         const char *name;
@@ -378,40 +361,14 @@ static int shell_output_kvs (struct shell_output *out)
             else
                 output_type = out->stderr_type;
             if (output_type == FLUX_OUTPUT_TYPE_KVS) {
-                char *entrystr = eventlog_entry_encode (entry);
-                if (!entrystr) {
-                    shell_log_errno ("eventlog_entry_encode");
-                    goto error;
-                }
-                if (flux_kvs_txn_put (txn,
-                                      FLUX_KVS_APPEND,
-                                      "output",
-                                      entrystr) < 0) {
-                    free (entrystr);
-                    goto error;
-                }
-                free (entrystr);
+                char *s = json_dumps (context, JSON_COMPACT);
+                if (eventlogger_append (out->ev, 0, "output", "data", s) < 0)
+                    shell_log_errno ("eventlogger_append");
+                free (s);
             }
         }
     }
-    if (!(f = flux_kvs_commit (out->shell->h, NULL, 0, txn)))
-        goto error;
-    if (flux_future_then (f, -1, shell_output_kvs_completion, out) < 0)
-        goto error;
-    if (flux_shell_add_completion_ref (out->shell, "output.kvs") < 0) {
-        shell_log_errno ("flux_shell_remove_completion_ref");
-        goto error;
-    }
-    /* f memory responsibility of shell_output_kvs_completion()
-     * callback */
-    f = NULL;
-    rc = 0;
-error:
-    saved_errno = errno;
-    flux_kvs_txn_destroy (txn);
-    flux_future_destroy (f);
-    errno = saved_errno;
-    return rc;
+    return 0;
 }
 
 static int shell_output_write_fd (int fd, const void *buf, size_t len)
@@ -639,6 +596,7 @@ void shell_output_destroy (struct shell_output *out)
             }
             zhash_destroy (&out->fds);
         }
+        eventlogger_destroy (out->ev);
         free (out);
         errno = saved_errno;
     }
@@ -920,6 +878,51 @@ error:
     return rc;
 }
 
+static void output_ref (struct eventlogger *ev, void *arg)
+{
+    struct shell_output *out = arg;
+    flux_shell_add_completion_ref (out->shell, "output.txn");
+}
+
+
+static void output_unref (struct eventlogger *ev, void *arg)
+{
+    struct shell_output *out = arg;
+    flux_shell_remove_completion_ref (out->shell, "output.txn");
+}
+
+static int output_eventlogger_start (struct shell_output *out)
+{
+    flux_t *h = flux_shell_get_flux (out->shell);
+    struct eventlogger_ops ops = {
+        .busy = output_ref,
+        .idle = output_unref
+    };
+    int timeout;
+
+    out->batch_timeout = 0.5;
+
+    if (flux_shell_getopt_unpack (out->shell, "output",
+                                  "{s?f}",
+                                  "batch-timeout",
+                                  &out->batch_timeout) < 0) {
+        if (flux_shell_getopt_unpack (out->shell, "output",
+                                     "{s?i}",
+                                     "batch-timeout",
+                                     &timeout) == 0)
+            out->batch_timeout = timeout;
+        else
+            return shell_log_errno ("invalid output.batch-timeout option");
+    }
+
+    shell_log ("batch timeout = %.3fs", out->batch_timeout);
+
+    out->ev = eventlogger_create (h, out->batch_timeout, &ops, out);
+    if (!out->ev)
+        return shell_log_errno ("eventlogger_create");
+    return 0;
+}
+
 struct shell_output *shell_output_create (flux_shell_t *shell)
 {
     struct shell_output *out;
@@ -975,6 +978,8 @@ struct shell_output *shell_output_create (flux_shell_t *shell)
                     goto error;
             }
         }
+        if (output_eventlogger_start (out) < 0)
+            goto error;
         if (shell_output_header (out) < 0)
             goto error;
     }
```

**Closed** 2019-11-07 23:00 UTC

**Comment by chu11** [comment] 2019-11-08 04:25
For documentation purposes if anyone comes here in the future.  Commit https://github.com/flux-framework/flux-core/commit/c82af7b238802c54ff300a7e797491cb34d29905 documented the wrong issue.  The fix in commit https://github.com/flux-framework/flux-core/commit/c82af7b238802c54ff300a7e797491cb34d29905 is for issue #2500.
