### ISSUE TITLE
Potential job-manager/job-exec sync issue

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2275] opened 2019-07-29 17:14 UTC
I am not sure if this is an issue because with the following error message, the scheduler and job-manager seem to work fine. 

After submitting a bunch of jobs like
``` console
flux job submit test.C08.T3600.json
flux job submit test.C10.T3600.json
flux job submit test.C12.T3600.json
flux job submit test.C14.T3600.json
flux job submit test.C16.T3600.json
flux job submit test.C06.T3600.json
flux job submit test.C06.T7200.json
flux job submit test.C04.T10800.json
flux job submit test.C04.T14400.json
flux job submit test.C02.T14400.json
flux job submit test.C02.T18000.json
flux job submit test.C08.T3600.json
```

If I cancel these jobs rapidly
```console
flux job list | grep -v USERID | xargs -L 1 flux job cancel
```

Sometime, I am getting an error message
```console
ahn1@34f49f161b2c:/usr/src/t/queue_policy$ 2019-07-29T17:12:39.875594Z job-manager.err[0]: start response: id=2335287803904 not active: No such file or directory
2019-07-29T17:12:39.877059Z job-manager.err[0]: start response: id=2336009224192 not active: No such file or directory
```

**Comment by dongahn** [comment] 2019-07-29 17:40
Ok. Moved to flux-core.

**Comment by grondo** [comment] 2019-07-29 17:47
> flux-job: 323145957376: unknown job id

This second manifestation might just mean that the job has already become inactive by the time the cancel is sent? What is the job running?

**Comment by dongahn** [comment] 2019-07-29 17:52
Yeah, that probably is. It is just hostname.

**Comment by grondo** [comment] 2019-07-29 17:57
```
ahn1@34f49f161b2c:/usr/src/t/queue_policy$ flux job eventlog 247463936000
1564421679.806617 submit userid=7818 priority=16 flags=0
1564421679.821767 depend
1564421698.311600 alloc note="rank0/core[2-3]"
1564421698.314653 exception type="cancel" severity=0 userid=7818 note="S 7818 16 2019-07-29T17:34:39Z"
1564421698.315891 release ranks="all" final=true
1564421698.318746 free
1564421698.318766 clean
```

This may actually demonstrate a bug in the `start` protocol between job-manager and job-exec. (probably a bug in the job-exec handling of exception). There is no `start` event in the eventlog, so the exception is received after the job-manager sends the `start` request to `job-exec`, but before the job shells have started (or before the `start` response is received). There is a `release ranks=all` response without any `finish` event, so the `start` response that gets logged as `not active` is either a `finish` response coming out of order or is a duplicate `release` event.

Either way there is something to fix here. Thanks for tracking it down!

**Comment by dongahn** [comment] 2019-07-29 18:00
OK. Changed the issue title. Let me know if there is anything else you want me to do on this.

**Comment by garlick** [comment] 2019-07-30 14:19
I'm having trouble reproducing the "start response" error with this script:
```sh
#!/bin/bash
  
NJOBS=20

flux jobspec srun hostname >j
for i in $(seq 1 ${NJOBS}); do
    id[${i}]=$(flux job submit j)
done
for i in $(seq ${NJOBS} 1); do
    flux job cancel ${id[${i}]}
done
flux dmesg|grep "job-manager.err"
```
It'd be interesting to see what type of start response is failing, e.g.
```diff
diff --git a/src/modules/job-manager/start.c b/src/modules/job-manager/start.c
index aee3ef673..797aa1d2d 100644
--- a/src/modules/job-manager/start.c
+++ b/src/modules/job-manager/start.c
@@ -193,8 +193,8 @@ static void start_response_cb (flux_t *h, flux_msg_handler_t *mh,
         goto error;
     }
     if (!(job = queue_lookup_by_id (ctx->queue, id))) {
-        flux_log_error (h, "start response: id=%llu not active",
-                        (unsigned long long)id);
+        flux_log_error (h, "start response type=%s: id=%llu not active",
+                        type, (unsigned long long)id);
         goto error;
     }
     if (!strcmp (type, "start")) {
```
I'll keep trying.

**Comment by dongahn** [comment] 2019-07-30 15:33
Let me give my repro to you @garlick. You shouldn't keep trying...

**Comment by dongahn** [comment] 2019-07-30 17:24
@garlick: 

I think it has a lot to do with specific timing. The most determinist reproducer is in the target ball:
[repro.tar.txt](https://github.com/flux-framework/flux-core/files/3448111/repro.tar.txt)

I suffixed the filename with `.txt` because GitHub doesn't like a tarball pasted here. But this is a tar file and you should rename it by dropping `.txt` suffix. 

Start your flux instance and type in the following:

```console
$ ./trigger_bug.sh
```

```console
ahn1@e8c4ad044f15:/usr/src/t/queue_policy/repro$ ./trigger_bug.sh
57747177472
58418266112
59122909184
59760443392
60397977600
61001957376
61589159936
62142808064
62763565056
63434653696
64172851200
64810385408
2019-07-30T17:18:18.814574Z job-manager.err[0]: start response: id=62763565056 not active: No such file or directory
2019-07-30T17:18:18.838315Z job-manager.err[0]: start response: id=63434653696 not active: No such file or directory
```

While I was trying other reproducers, I think I found a bunch of other issues. I will post that here as well.

**Comment by dongahn** [comment] 2019-07-30 17:31
```bash
#!/bin/bash

NREPEATS=10
NJOBS=12

flux jobspec srun -n 2 hostname >j
for j in $(seq 1 ${NREPEATS}); do
   for i in $(seq 1 ${NJOBS}); do
       id[${i}]=$(flux job submit j)
   done
   flux job list | grep -v USERID | xargs -L 1 flux job cancel
   echo "Iteration"
   sleep 1
done


flux dmesg|grep "job-manager.err"
```

I modified your testing script to add some timing, outer loop to repeat and such. And ran this with my flux instance on my docker running on Mac OSX. I observed the following four error message types:

1. Operation not supported
```
 2019-07-30T17:26:06.472166Z job-exec.err[0]: 445988732928: emit_event: Operation not supported
```

2. Broken pipe 
```
2019-07-30T17:26:36.407126Z connector-local.err[0]: client_respond: client_send_nocopy: Broken pipe
2019-07-30T17:26:36.407141Z connector-local.err[0]: internal_req: local.sub: client_respond: Broken pipe
```

3. Assertion failure
```
flux-broker: msg_handler.c:396: flux_msg_handler_start: Assertion `mh->magic == HANDLER_MAGIC' failed.
flux-start: 0 (pid 3177) Aborted
``` 

4. Above start response error
```
2019-07-30T17:25:57.728328Z job-manager.err[0]: start response: id=299171315712 not active: No such file or directory 
```

**Comment by dongahn** [comment] 2019-07-30 17:33
Of this, I think #3 is most critical because it is a hard failure tearing down the entire Flux instance... The instance survived for other cases!

**Comment by garlick** [comment] 2019-07-30 19:42
Yikes.

No luck reproducing yet.

I  ran the tarball script, but the enclosed jobspec refers to your file system structure so I replaced the job submission portion with
```sh
for i in $(seq 1 12); do
    flux jobspec srun hostname | flux job submit
done
```
The other one you posted after hasn't triggered yet either.   I'll play with `taskset -c 0` to see if that is more like your VM.

**Comment by dongahn** [comment] 2019-07-30 20:42
> I ran the tarball script, but the enclosed jobspec refers to your file system structure so I replaced the job submission portion with

Ugh... Yeah I didn't realize there were environment variables and such in the job specs. I think what would be more relevant would be the core counts and wallclock being used... 

> The other one you posted after hasn't triggered yet either. I'll play with taskset -c 0 to see if that is more like your VM.

I don't know what VM Mac/osx docker uses underneath it -- maybe virtualbox.

**Comment by dongahn** [comment] 2019-07-30 20:43
@garlick: Are you using docker for your testing?

**Comment by garlick** [comment] 2019-07-30 20:44
> Are you using docker for your testing?

No but I will try!

**Comment by grondo** [comment] 2019-07-31 18:16
I was able to reproduce on fluke by replacing `flux submit` in a loop with `t/ingest/submitbench`.
Here's the modified script (must be run from top-level flux build directly, after "make check" so that submitbench is built):

```sh
#!/bin/bash

NREPEATS=10
NJOBS=12

flux jobspec srun -n 2 hostname >j
for j in $(seq 1 ${NREPEATS}); do
   t/ingest/submitbench -f 24 -r 100 j
   flux job list
   flux job list | grep -v USERID | xargs -L 1 flux job cancel
   echo "Iteration"
   sleep 1
done

flux dmesg|grep "job-manager.err"
```

I ran the script under `taskset -c 0-1`, but even without I eventually hit
```
lt-flux-broker: msg_handler.c:396: flux_msg_handler_start: Assertion `mh->magic == 0x44433322' failed.
flux-start: 0 (pid 10962) Aborted
```

**Comment by grondo** [comment] 2019-07-31 22:34
Opened a separate issue for the `flux_msg_handler_start` assertion failure.

Running the reproducer above and enhancing the logs to note the type of start response I caught the following errors:

```
019-07-31T22:31:30.000974Z job-manager.err[0]: start response type=start: id=7675878309888 not active: No such file or directory
2019-07-31T22:31:30.054065Z job-manager.err[0]: start response type=start: id=7675962195968 not active: No such file or directory
```

As expected, the issue looks like it is in the `job-exec` module, which is replying with a `start` start response *after* it has already sent `release=all` triggering job transition to the inactive state.

I've also caught some errors in the `alloc` protocol using this reproducer. Seems to be a really good stress test!

```
2019-07-31T22:33:52.091410Z sched-simple.err[0]: alloc received before previous one handled
2019-07-31T22:33:52.091427Z sched-simple.err[0]: alloc: flux_respond_error: Invalid argument
flux-job: 9999807938560: unknown job id
2019-07-31T22:33:54.068085Z sched-simple.err[0]: alloc received before previous one handled
2019-07-31T22:33:54.068099Z sched-simple.err[0]: alloc: flux_respond_error: Invalid argument

```

**Comment by grondo** [comment] 2019-08-01 17:23
This was too tricky to fix by v0.12.0 so I moved it out to the next release.

**Comment by dongahn** [comment] 2019-08-01 20:09
@grondo: yes, this sounds right.

**Comment by garlick** [comment] 2019-08-16 12:57
Please reopen if there is anything here not covered by
* #2309 job-exec: fix exception handling of jobs in transition states  (merged)
* #2279 job-manager: fatal exception might be ignored by job-manager or scheduler due to race()

**Closed by garlick** 2019-08-16 12:57 UTC
