### ISSUE TITLE
sched.alloc-response: id=fF1SDRy already allocated

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5829] opened 2024-03-25 21:04 UTC
Problem: in #5796, the `t2812-flux-job-last.t` test got stuck in the test for issue #4930:

```
 expecting success: 
  	flux job last "[:]" >lastdump.exp &&
  	flux dump dump.tgz &&
  	flux start -o,-Scontent.restore=dump.tgz \
  		flux job last "[:]" >lastdump.out &&
  	test_cmp lastdump.exp lastdump.out
  
  
  flux-dump: archived 1 keys
  flux-dump: archived 2 keys
  flux-dump: archived 3 keys
  flux-dump: archived 4 keys
  flux-dump: archived 5 keys
  flux-dump: archived 6 keys
  flux-dump: archived 7 keys
  flux-dump: archived 8 keys
  flux-dump: archived 9 keys
  flux-dump: archived 65 keys
  Mar 25 18:41:44.457761 job-manager.err[0]: replay warning: INACTIVE action failed on job fEyxE9d: Read-only file system
  Mar 25 18:41:44.785969 job-manager.err[0]: sched.alloc-response: id=fF1SDRy already allocated
```

**Comment by grondo** [comment] 2024-03-25 21:24
duplicate of #5815?

**Comment by garlick** [comment] 2024-03-25 21:31
Oh indeed, sorry, missed that one.

**Closed** 2024-03-25 21:32 UTC
