### ISSUE TITLE
Issues when testing manual installation

### ISSUE THREAD

**Issue by siserte** [flux-framework/flux-core#5449] opened 2023-09-12 06:37 UTC
I am getting errors when testing my flux (v0.51.0) installation.

```
$ flux start --test-size=4
flux-broker: src/zsock_option.inc:2200: zsock_set_curve_server: Assertion `rc == 0 || zmq_errno () == (156384712 + 53)' failed.
flux-broker: src/zsock_option.inc:2200: zsock_set_curve_server: Assertion `rc == 0 || zmq_errno () == (156384712 + 53)' failed.
flux-start: 0 (pid 119901) Aborted
flux-start: 1 (pid 119902) Aborted
flux-start: 3 (pid 119904) Killed
flux-start: 2 (pid 119903) Killed
```

Some information about my testbed:

ZMQ version 4.3.4
CZMQ version 4.2.1
GCC 8.4.0 

```
$ cat /etc/os-release
NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp2"

$ uname -a
Linux login0 4.4.120-92.70-default #1 SMP Wed Mar 14 15:59:43 UTC 2018 (52a83de) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by garlick** [comment] 2023-09-12 12:36
Is libzmq built `--with-libsodium` to get CURVE security enabled?

I'm a little confused because that czmq assertion should not happen unless czmq was built with CURVE support, since it is inside `#if defined (ZMQ_CURVE_SERVER)` and I think czmq detects whether libzmq has CURVE support at build time and sets that.  So I would expect that libzmq has it.  But  maybe a different libzmq is being picked up at run time that doesn't have CURVE support or is too old to work with that version of czmq?  (I see it is packaged for SLES 15)

Wasn't SLES 12-SP2 end of life some time ago?  That's not necessarily a problem but the potential for running with very old packages in combinations we haven't tested recently is a bit concerning.

**Comment by siserte** [comment] 2023-09-12 12:41
I compiled it with: 

`./configure --prefix=$HOME/apps/install/libzmq --with-libsodium=$HOME/apps/install/libsodium`

You're right. We are upgrading the cluster, but meanwhile SLES 12 is what we have.

Thanks.

**Comment by garlick** [comment] 2023-09-12 12:48
Thanks - so no possibility of flux picking up older/differently configured versions of libzmq or libsodium at runtime?  (like from system packages?)

**Comment by garlick** [comment] 2023-09-12 13:14
I'm scratching my head on this one.   How far do you get if you run `make check` in the flux-core tree?  I imagine you won't get too far but I'm wondering if some of the early unit tests might fail in ways that could provide insight?

**Comment by siserte** [comment] 2023-09-12 13:43
I reached here:

```
============================================================================
Testsuite summary for flux-core 0.51.0
============================================================================
# TOTAL: 328
# PASS:  326
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 2
============================================================================
See src/broker/test-suite.log
============================================================================
Makefile:1249: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/gpfs/home/bsc21/bsc21334/apps/source/flux-core/src/broker'
Makefile:1355: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/gpfs/home/bsc21/bsc21334/apps/source/flux-core/src/broker'
Makefile:1424: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/gpfs/home/bsc21/bsc21334/apps/source/flux-core/src/broker'
Makefile:516: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/gpfs/home/bsc21/bsc21334/apps/source/flux-core/src'
Makefile:594: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

Thanks

**Comment by grondo** [comment] 2023-09-12 13:58
Can you try
```
$ cd src/broker
$ make check
```
and share the full output? Or if you see which specific test is failing, run it by hand? E.g.:
```
$ cd src/broker
$ ./test_overlay.t
```
(if `test_overlay.t` were the failing test or tests)

**Comment by siserte** [comment] 2023-09-12 14:01
The same error obtained with flux start:

```
$ ./test_overlay.t
# info: test log message
# created single-0: rank 0 size 1 uuid 92002373-616f-4fe9-8014-5fb58316ad69
ok 1 - single-0: overlay_set_topology size=1 rank=0 works
ok 2 - single-0: overlay_get_size returns 1
ok 3 - single-0: overlay_get_rank returns 0
ok 4 - (null): overlay_get_default_critical_ranks works
ok 5 - 0: overlay_get_default_critical_ranks returned (null)
ok 6 - single-0: overlay_register_attrs works
ok 7 - single-0: tbon.parent-endpoint=NULL
ok 8 - single-0: rank=0
ok 9 - single-0: size=1
ok 10 - single-0: tbon.level=0
ok 11 - single-0: tbon.maxlevel=0
ok 12 - single-0: tbon.descendants=0
ok 13 - single-0: overlay_get_parent_uri returned NULL
ok 14 - single-0: overlay_get_bind_uri returned NULL
ok 15 - single-0: overlay_sendmsg event where=DOWN succeeds
ok 16 - single-0: overlay_sendmsg event where=UP fails with EHOSTUNREACH
ok 17 - single-0: overlay_sendmsg response where=DOWN fails with EHOSTUNREACH
ok 18 - single-0: overlay_sendmsg response where=ANY fails with EHOSTUNREACH
ok 19 - single-0: overlay_sendmsg response where=UP fails with EHOSTUNREACH
ok 20 - single-0: overlay_sendmsg request where=DOWN fails with EHOSTUNREACH
ok 21 - single-0: overlay_sendmsg request where=ANY fails with EHOSTUNREACH
ok 22 - single-0: overlay_sendmsg request where=UP fails with EHOSTUNREACH
ok 23 - single-0: overlay_get_child_peer_count returns 0
# created trio-0: rank 0 size 3 uuid f4c5cca5-a678-4b4b-b1f0-75c1d05dab90
ok 24 - trio-0: overlay_set_topology works
ok 25 - trio-0: overlay_cert_pubkey works
test_overlay.t: src/zsock_option.inc:2200: zsock_set_curve_server: Assertion `rc == 0 || zmq_errno () == (156384712 + 53)' failed.
Aborted
```

**Comment by grondo** [comment] 2023-09-12 14:09
Thanks, unfortunately that didn't give us any hints, and I'm not finding anyone else hitting that particular error with a google search... Perhaps @garlick will have another idea...

**Comment by grondo** [comment] 2023-09-12 14:14
Oh, maybe you could try running the unit tests of libzmq and czmq from your original build directories and make sure they pass.

**Comment by siserte** [comment] 2023-09-13 02:44
This is what I got:

```
Testsuite summary for zeromq 4.3.5
============================================================================
# TOTAL: 131
# PASS:  115
# SKIP:  16
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0


$ ./test_sodium
tests/test_sodium.cpp:80:test__zmq_curve_keypair__always__success:PASS
tests/test_sodium.cpp:82:test__zmq_curve_public__valid__success:PASS
tests/test_sodium.cpp:83:test__zmq_curve_public__invalid__failure_short:PASS
tests/test_sodium.cpp:84:test__zmq_curve_public__invalid__failure_long:PASS
```

-----------------------
4 Tests 0 Failures 0 Ignored
OK

But I do not have the CURVE tests... Am I missing something?

Thank you.

**Comment by grondo** [comment] 2023-09-13 14:12
Did you configure libzmq `--with-libsodium`?

**Comment by garlick** [comment] 2023-09-13 14:24
The Makefile.am conditionally compiles the curve test executable so maybe something went wrong at configure time?

`src/platform.hpp` contains some of the configured results.  For example I have:
```
/* Using curve encryption */
#define ZMQ_HAVE_CURVE 1
[snip]
/* Using libsodium for curve encryption */
#define ZMQ_USE_LIBSODIUM 1
```

**Comment by grondo** [comment] 2023-09-13 14:26
Ah, I just noticed that your tests report you are on zeromq version 4.3.5, but the latest tagged version is 4.3.4. Are you building from the development HEAD?

When I build from libzmq master I get: "CURVE provided by tweetnacl" and then:
```
$ ./test_security_curve 
CURVE encryption not installed, skipping test
```

Perhaps you can try using the v4.3.4 tag and see if that works better? It seems to configure with "CURVE provided by libsodium" for me...

**Comment by grondo** [comment] 2023-09-13 14:50
If I actually configure with `--with-libsodium` as I suggested, then I get " Using libsodium for CURVE security", so the issue is probably just missing `--with-libsodium` on your `./configure` as suggested by @garlick. (And sorry about the noise)

**Comment by siserte** [comment] 2023-09-13 16:04
This is weird.

I checked out to tag V4.3.4 and configured with libsodium.

```
bsc21334@login2 ~/apps/source/libzmq[(HEAD detached at v4.3.4)*]$ ./configure --prefix=$HOME/apps/install/libzmq --with-libsodium=$HOME/apps/install/libsodium > m.o
configure: WARNING: You are building an unreleased version of 0MQ and asciidoc or xmlto are not installed.
configure: WARNING: Documentation will not be built and manual pages will not be installed.
configure: WARNING: Cannot find libbsd
bsc21334@login2 ~/apps/source/libzmq[(HEAD detached at v4.3.4)*]$ grep -niI sodium m.o
```

Apart from the warnings, there is no occurrence of "sodium"in the configure output.

**Comment by grondo** [comment] 2023-09-13 16:20
`grep sodium config.log`  returns nothing? that seems very odd.

**Comment by garlick** [comment] 2024-08-22 17:35
We added a configure time check in #6189 for zeromq crypto so I think we can close this.

**Closed by garlick** 2024-08-22 17:35 UTC
