### ISSUE TITLE
job-manager: handle scheduler disconnect

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2955] opened 2020-05-23 15:10 UTC
Problem: unloading the scheduler is not immediately detectable by the job manager on an idle system, since detection is based on receiving an ENOSYS response from an alloc or free request.

Now that disconnect messages are generated for unloading modules, the job manager _should_ receive a disconnect because of the initial HELLO request.  It could use this to mark the scheduler disconnected proactively, instead of waiting for job state transition to trigger it.

**Comment by chu11** [comment] 2020-09-12 12:11
duplicate of #3030 ?

**Comment by chu11** [comment] 2020-11-02 17:42
i think this is a duplicate of 3030, closing

**Closed by chu11** 2020-11-02 17:42 UTC
